// ============================================================================
// workflow-agent — Host 插件构建脚本
// 文件：code/scripts/build-host.js
// 说明：将共享模块与 host 插件模块按依赖顺序拼接为：
//       A) dist/host-body.js —— 自包含 host 函数体（cordis_define 的 code.host
//          直接取文件内容：函数定义 + return { inject, apply }，无 module 依赖）
//       B) dist/host-bundle.js —— CommonJS 可加载版本（Node 验证用）
// 用法：node code/scripts/build-host.js
// ============================================================================

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..', '..') // workflow-agent/
const OUT_DIR = path.join(ROOT, 'code', 'plugins', 'workflow-host', 'dist')

// 拼接顺序：共享常量 → 解析器 → 引擎 → 持久化 → 工具 → RPC → 入口
const MODULES = [
  ['code/shared/workflow-schema.js', 'workflow-schema'],
  ['code/shared/workflow-parser.js', 'workflow-parser'],
  ['code/plugins/workflow-host/engine.js', 'engine'],
  ['code/plugins/workflow-host/storage.js', 'storage'],
  ['code/plugins/workflow-host/tools.js', 'tools'],
  ['code/plugins/workflow-host/rpc.js', 'rpc'],
]

// 读取模块源码并剥离条件导出块（宿主机体内无 module；Node 版本保留）
function readModule(rel, stripExport) {
  const p = path.join(ROOT, rel)
  let text = fs.readFileSync(p, 'utf8')
  if (stripExport) {
    text = text.replace(/if \(typeof module !== 'undefined'[\s\S]*$/, '')
  }
  return text
}

// 提取 index.js 中的 hostApply 函数体（供 cordis body 形态）
function readHostApply(stripExport) {
  const p = path.join(ROOT, 'code', 'plugins', 'workflow-host', 'index.js')
  let text = fs.readFileSync(p, 'utf8')
  const m = /function hostApply\(ctx\) \{[\s\S]*?\n\}/.exec(text)
  if (!m) throw new Error('index.js 中找不到 function hostApply')
  if (stripExport) text = text.replace(/if \(typeof module !== 'undefined'[\s\S]*$/, '')
  return stripExport ? m[0] : m[0]
}

function build() {
  // ── A) host-body.js：cordis_define 可用的函数体 ──
  const bodyParts = []
  bodyParts.push('// AUTO-GENERATED by code/scripts/build-host.js — host body for cordis_define')
  bodyParts.push('// 源文件: ' + MODULES.map((m) => m[0]).join(', ') + ' + index.js')
  bodyParts.push('')
  for (const [rel, name] of MODULES) {
    bodyParts.push('// ---- module: ' + name + ' ----')
    bodyParts.push(readModule(rel, true))
  }
  bodyParts.push('// ---- module: host entry ----')
  bodyParts.push(readHostApply(true))
  bodyParts.push('')
  bodyParts.push('return { inject: [\'fs\', \'timer\'], apply: hostApply }')
  const bodyOut = bodyParts.join('\n')
  fs.mkdirSync(OUT_DIR, { recursive: true })
  const bodyPath = path.join(OUT_DIR, 'host-body.js')
  fs.writeFileSync(bodyPath, bodyOut, 'utf8')

  // ── B) host-bundle.js：CommonJS 可加载版本 ──
  const bundleParts = []
  bundleParts.push('// AUTO-GENERATED by code/scripts/build-host.js — CommonJS bundle')
  bundleParts.push('')
  for (const [rel, name] of MODULES) {
    bundleParts.push('// ---- module: ' + name + ' ----')
    bundleParts.push(readModule(rel, false))
  }
  bundleParts.push('// ---- module: host entry ----')
  bundleParts.push(readHostApply(false))
  bundleParts.push('')
  bundleParts.push('module.exports = { host, hostApply }')
  const bundleOut = bundleParts.join('\n')
  const bundlePath = path.join(OUT_DIR, 'host-bundle.js')
  fs.writeFileSync(bundlePath, bundleOut, 'utf8')

  // ── C) host-verify.js：去注释紧凑版（验证用，减小 cordis_define 传参体积） ──
  const compact = bodyOut
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l !== '' && !l.startsWith('//') && !l.startsWith('/*'))
    .join('\n')
  const verifyPath = path.join(OUT_DIR, 'host-verify.js')
  fs.writeFileSync(verifyPath, compact, 'utf8')

  console.log('✔ 已生成 ' + bodyPath + ' (' + bodyOut.split('\n').length + ' 行)')
  console.log('✔ 已生成 ' + bundlePath + ' (' + bundleOut.split('\n').length + ' 行)')
  console.log('✔ 已生成 ' + verifyPath + ' (' + compact.split('\n').length + ' 行, ' + compact.length + ' chars)')
}

build()