// ============================================================================
// workflow-agent — Agent Preset 本地插件构建脚本〔已废弃 · DEPRECATED〕
// 文件：code/scripts/build-preset.js
//
// ⚠️ 本脚本已废弃（2026-09-13，Iter-Migration-Phase4 拍板），**禁止运行**。
//
// 废弃原因：本脚本是早期（3 模块时代）的 mjs 生成器，模板硬编码
//   `inject: ['fs', 'timer']` 与 5 个模块拼接，早已落后于现役 workflow-host.mjs
//   （6400+ 行、12 个 section）。**运行它会用陈旧模板整体覆盖现役 mjs**，
//   造成此前多轮迭代成果丢失（含 0.1.5 迁移改动）。
//
// 现役构建链（改源后按序执行）：
//   1) 改 section 源模块（code/shared/*、code/plugins/workflow-host/*、
//      code/plugins/workflow-host-preset/tools-preset.js 等）
//   2) node code/scripts/sync-modules.js [section ...]   ← 同步内联副本进 mjs
//   3) mjs 直编 section（apply 前言探针 / webserver-routes / A1 tap）手工编辑
//   4) node code/packages/workflow-host/build.js          ← 生成 npm 包 lib/index.js
//   5) node code/scripts/test-host.js                     ← 单测回归
//
// 本文件保留仅作历史参考；如需重新生成 mjs，应基于 sync-modules.js 的
// SOURCES 登记表扩展，而非复活本模板。
// ============================================================================

console.error('')
console.error('✗ build-preset.js 已废弃，禁止运行。')
console.error('  它会用陈旧模板（inject: [\'fs\', \'timer\']、5 模块）覆盖现役 workflow-host.mjs。')
console.error('')
console.error('  现役构建链：')
console.error('    1) 改 section 源模块（code/shared/*、code/plugins/**/tools-preset.js 等）')
console.error('    2) node code/scripts/sync-modules.js [section ...]')
console.error('    3) mjs 直编 section（apply 前言探针 / webserver-routes / A1 tap）手工编辑')
console.error('    4) node code/packages/workflow-host/build.js')
console.error('    5) node code/scripts/test-host.js')
console.error('')
process.exit(1)

/* eslint-disable */
// ── 以下为废弃的历史实现，保留作参考，永不执行 ──────────────────────────
const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..', '..') // workflow-agent/
const OUT_FILE = path.join(ROOT, 'code', 'agent-presets', 'workflow-orchestrator', 'workflow-host.mjs')

// 拼接顺序：共享常量 → 解析器 → 引擎 → 持久化 → preset 工具
const MODULES = [
  ['code/shared/workflow-schema.js', 'workflow-schema'],
  ['code/shared/workflow-parser.js', 'workflow-parser'],
  ['code/plugins/workflow-host/engine.js', 'engine'],
  ['code/plugins/workflow-host/storage.js', 'storage'],
  ['code/plugins/workflow-host-preset/tools-preset.js', 'tools-preset'],
]

function readModule(rel) {
  const p = path.join(ROOT, rel)
  let text = fs.readFileSync(p, 'utf8')
  // 剥离条件导出块（ESM 插件内无 module）
  text = text.replace(/if \(typeof module !== 'undefined'[\s\S]*$/, '')
  return text
}

function build() {
  const parts = []
  parts.push('// AUTO-GENERATED by code/scripts/build-preset.js — workflow-orchestrator host plugin')
  parts.push('// 源文件: ' + MODULES.map((m) => m[0]).join(', '))
  parts.push('// 形态：Agent Preset 本地插件（ESM），agent.cordis.yml 以 ./workflow-host.mjs 挂载。')
  parts.push('// 注册：ctx.tools.register（与 dsh-tool-workflow/custom-bash 一致）；')
  parts.push('//       落盘根默认取 exec.agent.session.header.cwd（会话工作区）。')
  parts.push('')

  // ── ESM 插件导出声明 ──
  parts.push("export const name = 'workflow-host'")
  parts.push("export const inject = ['fs', 'timer']")
  parts.push('')
  parts.push('export function apply(ctx, config) {')
  parts.push('  const engine = createWorkflowEngine()')
  parts.push("  const storage = createWorkflowStorage(ctx, engine)")
  parts.push('  if (storage) {')
  parts.push("    storage.load().catch(() => {})")
  parts.push('  }')
  parts.push("  if (ctx.get('fs')) {")
  parts.push('    registerWorkflowToolsPreset(ctx, engine, storage)')
  parts.push('  }')
  parts.push("  ctx.effect(() => () => {})")
  parts.push('}')
  parts.push('')

  // ── 模块源码（剥离导出） ──
  for (const [rel, name] of MODULES) {
    parts.push('// ---- module: ' + name + ' ----')
    parts.push(readModule(rel))
  }

  const out = parts.join('\n')
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
  fs.writeFileSync(OUT_FILE, out, 'utf8')
  console.log('✔ 已生成 ' + OUT_FILE + ' (' + out.split('\n').length + ' 行)')
}

build()