// ============================================================================
// workflow-agent — Agent Preset 本地插件构建脚本
// 文件：code/scripts/build-preset.js
// 说明：把共享模块（schema/parser/engine/storage）与 preset 形态工具
//       （ctx.tools.register，exec.cwd 默认落盘）拼接为单个 ESM 插件文件：
//       code/agent-presets/workflow-orchestrator/workflow-host.mjs
//       供 agent.cordis.yml 以 `name: ./workflow-host.mjs` 挂载。
// 用法：node code/scripts/build-preset.js
// ============================================================================

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..', '..') // workflow-agent/
const OUT_FILE = path.join(ROOT, 'code', 'agent-presets', 'workflow-orchestrator', 'workflow-host.mjs')

// 拼接顺序：共享常量 → 解析器 → 引擎 → 持久化 → preset 工具
const MODULES = [
  ['code/shared/workflow-schema.js', 'workflow-schema'],
  ['code/shared/workflow-parser.js', 'workflow-parser'],
  ['code/plugins/workflow-host/engine.js', 'engine'],
  ['code/plugins/workflow-host/storage.js', 'storage'],
  ['code/plugins/workflow-host-preset/tools-preset.js', 'tools-preset'],
]

function readModule(rel) {
  const p = path.join(ROOT, rel)
  let text = fs.readFileSync(p, 'utf8')
  // 剥离条件导出块（ESM 插件内无 module）
  text = text.replace(/if \(typeof module !== 'undefined'[\s\S]*$/, '')
  return text
}

function build() {
  const parts = []
  parts.push('// AUTO-GENERATED by code/scripts/build-preset.js — workflow-orchestrator host plugin')
  parts.push('// 源文件: ' + MODULES.map((m) => m[0]).join(', '))
  parts.push('// 形态：Agent Preset 本地插件（ESM），agent.cordis.yml 以 ./workflow-host.mjs 挂载。')
  parts.push('// 注册：ctx.tools.register（与 dsh-tool-workflow/custom-bash 一致）；')
  parts.push('//       落盘根默认取 exec.agent.session.header.cwd（会话工作区）。')
  parts.push('')

  // ── ESM 插件导出声明 ──
  parts.push("export const name = 'workflow-host'")
  parts.push("export const inject = ['fs', 'timer']")
  parts.push('')
  parts.push('export function apply(ctx, config) {')
  parts.push('  const engine = createWorkflowEngine()')
  parts.push("  const storage = createWorkflowStorage(ctx, engine)")
  parts.push('  if (storage) {')
  parts.push("    storage.load().catch(() => {})")
  parts.push('  }')
  parts.push("  if (ctx.get('fs')) {")
  parts.push('    registerWorkflowToolsPreset(ctx, engine, storage)')
  parts.push('  }')
  parts.push("  ctx.effect(() => () => {})")
  parts.push('}')
  parts.push('')

  // ── 模块源码（剥离导出） ──
  for (const [rel, name] of MODULES) {
    parts.push('// ---- module: ' + name + ' ----')
    parts.push(readModule(rel))
  }

  const out = parts.join('\n')
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
  fs.writeFileSync(OUT_FILE, out, 'utf8')
  console.log('✔ 已生成 ' + OUT_FILE + ' (' + out.split('\n').length + ' 行)')
}

build()