// @workflow-agent/workflow-host - Host Plugin (npm package)
// Auto-generated by build.js - DO NOT EDIT
// 提供工具注册（workflow_begin / workflow_status）+ webServer HTTP 路由（/wf/*）。
// 不再依赖 harness Builtin；RPC 处理器（workflow-rpc.mjs）已停用。

export const name = 'workflow-host'
export const inject = ['fs', 'tools', 'webServer']

export function apply(ctx) {
  // AUTO-GENERATED by code/scripts/build-preset.js — workflow-orchestrator host plugin
// 源文件: code/shared/workflow-schema.js, code/shared/workflow-parser.js, code/plugins/workflow-host/engine.js, code/plugins/workflow-host/storage.js, code/plugins/workflow-host-preset/tools-preset.js
// 形态：Agent Preset 本地插件（ESM），agent.cordis.yml 以 ./workflow-host.mjs 挂载。
// 注册：ctx.tools.register（与 dsh-tool-workflow/custom-bash 一致）；
//       落盘根默认取 exec.agent.session.header.cwd（会话工作区）。




function applyInternal(ctx) {
  // Iter-10：多实例注册表（instanceId → engine/storage，sessionId → 活跃实例）
  const registry = createInstanceRegistry(ctx, { createWorkflowEngine, createWorkflowStorage })
  // 单实例兼容绑定（显式 statePath/workspaceRoot 参数或无会话上下文时回退）
  const engine = createWorkflowEngine()
  const storage = createWorkflowStorage(ctx, engine)
  if (storage) {
    storage.load().catch(() => {})
  }
  if (ctx.get('tools')) {
    registerWorkflowToolsPreset(ctx, engine, storage, registry)
  }
  // Iter-5：webServer HTTP 路由（替代 harness RPC，供 Client 面板轮询状态）
  registerWebRoutes(ctx)
  ctx.effect(() => () => {})
}

// ---- module: workflow-schema ----
// ============================================================================
// workflow-agent — 共享 Schema 常量与校验规则
// 文件：code/shared/workflow-schema.js
// 说明：纯逻辑模块（无 DSH/Cordis 依赖），可被 Node 直接 require 测试，
//       宿主插件内联打包时按模块源码拼接。
// ============================================================================

// ── Task 类型枚举 ──────────────────────────────────────────────────────────
const TASK_TYPES = {
  LLM_TASK: 'llm-task',
  LOOP: 'loop',
  CONCURRENT: 'concurrent', // Iter-8：并发执行（同 loop 结构，迭代无依赖可并行）
  HUMAN_DECISION: 'human-decision', // 预留（后续迭代）
  EXTERNAL_AGENT: 'external-agent', // 预留（后续迭代）
}

// ── 字段默认值 ─────────────────────────────────────────────────────────────
const DEFAULTS = {
  timeout: 600, // 秒
  dependsOn: [],
  taskType: TASK_TYPES.LLM_TASK,
  retries: 0, // quality-gate max-retries 默认
  onFailure: 'block', // quality-gate on-failure 默认
  maxConcurrency: 1, // 工作流级最大并发数（Iter-7，默认串行）
}

// ── 必填字段校验规则 ────────────────────────────────────────────────────────
const REQUIRED = {
  llmTask: ['id', 'processor'],
  loop: ['id', 'processor', 'items-from', 'item-var'],
  concurrent: ['id', 'processor', 'items-from', 'item-var'], // Iter-8
  humanDecision: ['id', 'prompt'],
  externalAgent: ['id', 'agent'],
}

// ── 循环错误处理策略 ──────────────────────────────────────────────────────────
const ON_ERROR_VALUES = ['break', 'continue']

// ─ 支持 uality-gate on-failure  的策略值 ──────────────────────────────────
const ON_FAILURE_VALUES = ['retry', 'block', 'skip']

// ── 参数模板正则（${param_name} / ${item}） ────────────────────────────────
const PARAM_PATTERN = /\$\{(\w+)\}/g

// ── Task 运行时状态枚举 ─────────────────────────────────────────────────────
const TASK_STATUS = {
  PENDING: 'PENDING', // 未开始
  RUNNING: 'RUNNING', // 执行中
  DONE: 'DONE', // 完成（含 Gate PASS）
  FAILED: 'FAILED', // 失败（Gate FAIL 且重试耗尽 / block）
  SKIPPED: 'SKIPPED', // 跳过
}

// ── 工作流全局阶段枚举 ──────────────────────────────────────────────────────
const STAGE = {
  PENDING: 'PENDING', // 待启动
  RUNNING: 'RUNNING', // 运行中
  COMPLETED: 'COMPLETED', // 全部完成
  FAILED: 'FAILED', // 阻断失败
  PAUSED: 'PAUSED', // 暂停（后续迭代）
}

// ── 条件导出（Node 测试可用；宿主内联拼接时 module 未定义则跳过） ─────────

// ---- module: workflow-parser ----
// ============================================================================
// workflow-agent — 轻量 YAML 解析器 + 工作流文档结构化
// 文件：code/shared/workflow-parser.js
// 说明：无依赖纯逻辑片段（不包含 module.exports，供 Node 测试与宿主内联）。
//       实现的 YAML 子集：顶层 map、嵌套 map、block 列表（- item）、
//       内联列表（[a, b]）、标量（字符串/数字/布尔/null），引号剥离。
// ============================================================================

// ── 词法：行扫描 ────────────────────────────────────────────────────────────
function countIndent(line) {
  let n = 0
  while (n < line.length && (line[n] === ' ' || line[n] === '\t')) n++
  return n
}

function stripComment(line) {
  // 去除行尾注释（# 前有空白才视为注释，避免 url/说明内 #）
  const m = /(\s)#/.exec(line)
  return m ? line.slice(0, m.index) : line
}

function parseScalar(raw) {
  const s = String(raw).trim()
  if (s === '') return null
  if (s === 'null' || s === '~') return null
  if (s === 'true') return true
  if (s === 'false') return false
  // 数字
  if (/^-?\d+(\.\d+)?$/.test(s)) return Number(s)
  // 引号剥离
  if ((s[0] === '"' && s[s.length - 1] === '"') || (s[0] === "'" && s[s.length - 1] === "'")) {
    return s.slice(1, -1)
  }
  return s
}

// 内联列表 [a, b, c]
function parseInlineList(s) {
  const m = /\s*\[(.*)\]\s*$/.exec(s)
  if (!m) return null
  const inner = m[1]
  if (inner.trim() === '') return []
  return inner.split(',').map((part) => parseScalar(part))
}

// ── 语法：块解析 ────────────────────────────────────────────────────────────
// 解析从 start 开始、缩进 >= baseIndent 的行序列，返回 { value, next }
// value 可为普通对象（map）、数组（list）、或标量。
function parseBlock(lines, start, baseIndent) {
  const total = lines.length
  if (start >= total || countIndent(lines[start]) < baseIndent) {
    return { value: null, next: start }
  }
  const indent = countIndent(lines[start])

  // 列表块：- item （支持 - key: value 多行对象元素）
  if (/^\s*-\s+/.test(lines[start]) || /^\s*-$/.test(lines[start])) {
    const arr = []
    let i = start
    while (i < total) {
      const ln = lines[i]
      const ind = countIndent(ln)
      if (ind < indent || !/^\s*-/.test(ln)) break
      const rest = stripComment(ln.slice(ln.indexOf('-') + 1).trim())
      if (rest === '') {
        // 空 item：后续缩进行是嵌套块（map 或 list）
        const sub = parseBlock(lines, i + 1, indent + 1)
        arr.push(sub.value)
        i = sub.next
      } else if (rest.indexOf(':') !== -1) {
        // "- key: value"：多行对象元素的起始行
        const obj = {}
        const colon = rest.indexOf(':')
        const key = rest.slice(0, colon).trim()
        const val = stripComment(rest.slice(colon + 1).trim()).trim()
        if (val === '') {
          const sub = parseBlock(lines, i + 1, indent + 1)
          obj[key] = sub.value
          i = sub.next
        } else {
          const inline = parseInlineList(val)
          obj[key] = inline ? inline : parseScalar(val)
          i++
        }
        // 续行：缩进 > 列表缩进 的 map 键归属于当前元素
        const cont = parseBlock(lines, i, indent + 1)
        if (cont.value && typeof cont.value === 'object' && !Array.isArray(cont.value)) {
          Object.assign(obj, cont.value)
          i = cont.next
        }
        arr.push(obj)
      } else if (rest.indexOf('[') !== -1 && rest.indexOf(']') !== -1) {
        arr.push(parseInlineList(rest))
        i++
      } else {
        arr.push(parseScalar(rest))
        i++
      }
    }
    return { value: arr, next: i }
  }

  // map 块：key: value
  const obj = {}
  let i = start
  while (i < total) {
    const ln = lines[i]
    const ind = countIndent(ln)
    if (ind < indent || !/^\S/.test(ln.trim())) break
    const colon = ln.indexOf(':')
    if (colon === -1) {
      i++
      continue
    }
    const key = ln.slice(0, colon).trim()
    const rest = ln.slice(colon + 1).trim()
    const restClean = stripComment(rest).trim()
    if (restClean === '') {
      // value 在后续缩进行中
      const sub = parseBlock(lines, i + 1, indent + 1)
      obj[key] = sub.value
      i = sub.next
    } else {
      const inline = parseInlineList(restClean)
      if (inline) {
        obj[key] = inline
      } else {
        obj[key] = parseScalar(restClean)
      }
      i++
    }
  }
  return { value: obj, next: i }
}

function parseYaml(text) {
  const lines = String(text).split(/\r?\n/)
  const content = lines.filter((l) => l.trim() !== '' && !/^\s*#/.test(l))
  if (content.length === 0) return {}
  const r = parseBlock(content, 0, 0)
  return r.value || {}
}

// ── 工作流结构化与校验 ──────────────────────────────────────────────────────
// 输入：YAML 文本字符串；输出：结构化工作流对象（合法时）
// 结构：{ name, version, description, params, tasks:[...], errors:[...] }
function parseWorkflow(text) {
  const raw = parseYaml(text)
  const errors = []
  const warnings = []

  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return { name: null, version: null, description: null, params: {}, tasks: [], errors: ['工作流文件必须是一个 YAML 对象'], maxConcurrency: 1 }
  }

  const name = raw.name != null ? String(raw.name) : null
  if (!name) errors.push('缺少必填字段: name')

  const version = raw.version != null ? String(raw.version) : null

  // Iter-7：工作流级最大并发数（默认 1 = 串行）
  const maxConcurrency = raw['max-concurrency'] != null ? Number(raw['max-concurrency']) : 1
  if (!Number.isInteger(maxConcurrency) || maxConcurrency < 1) {
    errors.push('max-concurrency 必须是 >= 1 的整数，实际: ' + raw['max-concurrency'])
  }

  const params = {}
  if (raw.params && typeof raw.params === 'object' && !Array.isArray(raw.params)) {
    for (const k of Object.keys(raw.params)) {
      const p = raw.params[k]
      params[k] = {
        type: (p && p.type) || 'string',
        description: (p && p.description) || '',
        default: p && p.default !== undefined ? p.default : undefined,
      }
    }
  }

  const tasks = []
  if (!Array.isArray(raw.tasks) || raw.tasks.length === 0) {
    errors.push('缺少必填字段: tasks（至少 1 个 Task）')
  } else {
    const seenIds = new Set()
    raw.tasks.forEach((t, idx) => {
      if (!t || typeof t !== 'object') {
        errors.push('tasks[' + idx + '] 不是有效对象')
        return
      }
      const task = normalizeTask(t, idx, errors, warnings)
      if (task) {
        if (seenIds.has(task.id)) {
          errors.push('Task id 重复: ' + task.id)
        }
        seenIds.add(task.id)
        tasks.push(task)
      }
    })
    // depends-on 引用校验
    for (const t of tasks) {
      for (const dep of t.dependsOn) {
        if (!seenIds.has(dep)) {
          errors.push('Task "' + t.id + '" 的 depends-on 引用了不存在的 Task: ' + dep)
        }
      }
    }
  }

  return { name, version, description: raw.description || null, params, tasks, errors, warnings, maxConcurrency }
}

function normalizeTask(t, idx, errors) {
  const id = t.id != null ? String(t.id).trim() : ''
  if (!id) {
    errors.push('tasks[' + idx + '] 缺少必填字段: id')
    return null
  }
  const type = t.type || 'llm-task'

  // v1.1：inputs 为命名 map {key: 单路径 | 路径列表}，值保留原始形态传给宿主
  const inputsRaw = normalizeInputs(t.inputs)
  if (inputsRaw === null) {
    errors.push('Task "' + id + '" 的 inputs 必须是命名 map {key: 路径 | 路径列表}（v1.1 起不再支持列表形态）')
  }

  const base = {
    id,
    name: t.name != null ? String(t.name) : id,
    type,
    dependsOn: toArray(t['depends-on']),
    timeout: t.timeout != null ? Number(t.timeout) : 600,
    // 原始相对路径（保留给宿主解析绝对路径）
    processorRaw: t.processor != null ? String(t.processor) : null,
    inputsRaw: inputsRaw || {},
    outputsRaw: toArray(t.outputs),
  }

  // 质量门禁
  if (t['quality-gate'] != null) {
    const g = t['quality-gate']
    if (typeof g !== 'object' || Array.isArray(g)) {
      errors.push('Task "' + id + '" 的 quality-gate 必须是对象')
    } else {
      const onFailure = g['on-failure'] || 'block'
      if (['retry', 'block', 'skip'].indexOf(onFailure) === -1) {
        errors.push('Task "' + id + '" 的 quality-gate.on-failure 必须是 retry|block|skip，实际: ' + onFailure)
      }
      base.gateRaw = g.checker != null ? String(g.checker) : null
      base.gateOnFailure = onFailure
      base.gateMaxRetries = g['max-retries'] != null ? Number(g['max-retries']) : 0
    }
  }

  // 类型专属校验
  if (type === 'llm-task' || !type) {
    if (!base.processorRaw) errors.push('Task "' + id + '" 缺少必填字段: processor')
  } else if (type === 'loop') {
    if (!base.processorRaw) errors.push('Task "' + id + '" 缺少必填字段: processor')
    if (t['items-from'] == null) errors.push('Task "' + id + '" 缺少必填字段: items-from')
    if (t['item-var'] == null) errors.push('Task "' + id + '" 缺少必填字段: item-var')
    base.itemsFromRaw = t['items-from'] != null ? String(t['items-from']) : null
    base.itemVar = t['item-var'] != null ? String(t['item-var']) : 'item'
    // 循环错误处理策略
    const onError = t['on-error'] || 'break'
    if (['break', 'continue'].indexOf(onError) === -1) {
      errors.push('Task "' + id + '" 的 on-error 必须是 break|continue，实际: ' + onError)
    }
    base.onError = onError
  } else if (type === 'concurrent') {
    // Iter-8：并发执行（同 loop 结构，迭代无依赖可并行）
    if (!base.processorRaw) errors.push('Task "' + id + '" 缺少必填字段: processor')
    if (t['items-from'] == null) errors.push('Task "' + id + '" 缺少必填字段: items-from')
    if (t['item-var'] == null) errors.push('Task "' + id + '" 缺少必填字段: item-var')
    base.itemsFromRaw = t['items-from'] != null ? String(t['items-from']) : null
    base.itemVar = t['item-var'] != null ? String(t['item-var']) : 'item'
    base.maxConcurrency = t['max-concurrency'] != null ? Number(t['max-concurrency']) : null
  } else if (type === 'human-decision') {
    base.prompt = t.prompt != null ? String(t.prompt) : null
    if (!base.prompt) errors.push('Task "' + id + '" 缺少必填字段: prompt')
  } else if (type === 'external-agent') {
    base.agent = t.agent != null ? String(t.agent) : null
    if (!base.agent) errors.push('Task "' + id + '" 缺少必填字段: agent')
  } else {
    errors.push('Task "' + id + '" 的 type 不支持: ' + type)
  }

  return base
}

function toArray(v) {
  if (v == null) return []
  if (Array.isArray(v)) return v.map((x) => String(x))
  return [String(v)]
}

// v1.1：命名式 inputs。YAML 解出后为 {key: string | string[]}；
// 保留 map 形态与值的原生类型，仅确保 string[] 元素为字符串。
// 若输入是数组/标量（旧列表形态），视为无效并返回 null（字段用默认 {}）。
function normalizeInputs(v) {
  if (v == null) return {}
  if (typeof v !== 'object' || Array.isArray(v)) return null
  const out = {}
  for (const k of Object.keys(v)) {
    const val = v[k]
    if (Array.isArray(val)) {
      out[k] = val.map((x) => String(x))
    } else if (val != null) {
      out[k] = String(val)
    }
  }
  return out
}


// ---- module: engine ----
// ============================================================================
// workflow-agent — 工作流实例状态引擎
// 文件：code/plugins/workflow-host/engine.js
// 说明：纯内存状态管理（N 节点状态表、阶段、Gate 结果、重试计数、执行日志）。
//       宿主内联时，schema 常量（STAGE/TASK_STATUS）由前置拼接的
//       workflow-schema.js 提供；Node 独立测试时，下方兜底常量生效。
// ============================================================================

// 兜底常量：宿主内联时同作用域已有同名 const，let 声明不冲突。
let E_STAGE = typeof STAGE !== 'undefined' ? STAGE : {
  PENDING: 'PENDING', RUNNING: 'RUNNING', COMPLETED: 'COMPLETED', FAILED: 'FAILED', PAUSED: 'PAUSED',
}
let E_TASK_STATUS = typeof TASK_STATUS !== 'undefined' ? TASK_STATUS : {
  PENDING: 'PENDING', RUNNING: 'RUNNING', DONE: 'DONE', FAILED: 'FAILED', SKIPPED: 'SKIPPED',
}

// Task 运行时快照（供 UI 消费的最小字段集）
function taskSnapshot(t) {
  return {
    id: t.id,
    name: t.name,
    type: t.type,
    dependsOn: t.dependsOn || [],
    status: t.status,
    processor: t.processor || null,       // 处理器技能绝对路径（Client 读取 skill 文本用）
    gateChecker: (t.gate && t.gate.checker) || null, // 门禁技能绝对路径
    gateResult: t.gateResult || null,
    gateOnFailure: t.gateOnFailure || null,
    retries: t.retries || 0,
    _loopGroup: t._loopGroup || null,
    _loopItem: t._loopItem || null,
    _loopIndex: t._loopIndex ?? 0,
    _loopGroupName: t._loopGroupName || null,
    _onError: t._onError || null,
    // Iter-8：并发组元数据（Client DAG 分组渲染）
    _concurrentGroup: t._concurrentGroup || null,
    _concurrentGroupName: t._concurrentGroupName || null,
    _concurrentItem: t._concurrentItem || null,
    _concurrentIndex: t._concurrentIndex ?? 0,
    _concurrentMax: t._concurrentMax || null,
  }
}

// 全局快照（供 RPC / Tool 返回；指纹用于 Client 防抖）
function createWorkflowEngine() {
  const state = {
    workflow: null, // 工作流名称
    version: null,
    description: null,
    params: {},
    maxConcurrency: 1, // Iter-7：工作流级最大并发数
    active: false, // 是否有进行中的实例
    stage: E_STAGE.PENDING,
    tasks: [], // Task 运行时状态数组
    gateResult: null, // 最近 Gate 结果（PASS/FAIL）
    retries: 0, // 最近任务的重试计数
    error: null,
    updatedAt: 0,
    logs: [], // 结构化执行日志 [{ts, action, detail}]
    persist: null, // 最近一次持久化结果
  }

  function fingerprint() {
    const t = state.tasks.map((x) => x.id + ':' + x.status).join(',')
    return [state.stage, state.gateResult || '', state.retries, state.error || '', t].join('|')
  }

  function snapshot() {
    return {
      workflow: state.workflow,
      version: state.version,
      description: state.description,
      maxConcurrency: state.maxConcurrency,
      active: state.active,
      stage: state.stage,
      tasks: state.tasks.map(taskSnapshot),
      gateResult: state.gateResult,
      retries: state.retries,
      error: state.error,
      updatedAt: state.updatedAt,
      logs: state.logs.slice(-200), // 最多保留最近 200 条
      persist: state.persist,
      runnable: getRunnableTasks(), // Iter-7：当前就绪可并发执行的任务
      fingerprint: fingerprint(),
    }
  }

  // 启动新工作流：清空旧状态，按解析结果初始化 N 个 Task
  function begin(parsed) {
    state.workflow = parsed.name
    state.version = parsed.version
    state.description = parsed.description
    state.params = parsed.params || {}
    state.maxConcurrency = parsed.maxConcurrency || 1 // Iter-7：工作流级最大并发数
    state.active = true
    state.stage = E_STAGE.PENDING
    state.gateResult = null
    state.retries = 0
    state.error = null
    state.logs = [] // Iter-6：重新 begin 时清除历史日志，避免跨实例残留
    state.tasks = parsed.tasks.map((t) => ({
      id: t.id,
      name: t.name,
      type: t.type,
      dependsOn: t.dependsOn || [], // Iter-7：前驱依赖，供 getRunnableTasks 计算就绪
      status: E_TASK_STATUS.PENDING,
      processor: t.processor || null, // 绝对路径（由 tools 层解析后写入）
      outputs: t.outputs || [],
      gate: t.gate || null, // {checker, onFailure, maxRetries}
      gateResult: null,
      retries: 0,
      _loopGroup: t._loopGroup || null,
      _loopItem: t._loopItem || null,
      _loopIndex: t._loopIndex ?? 0,
      _loopGroupName: t._loopGroupName || null,
      _onError: t._onError || null,
      // Iter-8：并发组元数据（engine 组级并发控制 + Client DAG 分组渲染）
      _concurrentGroup: t._concurrentGroup || null,
      _concurrentGroupName: t._concurrentGroupName || null,
      _concurrentItem: t._concurrentItem || null,
      _concurrentIndex: t._concurrentIndex ?? 0,
      _concurrentMax: t._concurrentMax || null,
    }))
    state.updatedAt = Date.now()
    log('BEGIN', '工作流 "' + state.workflow + '" 已初始化，tasks=' + state.tasks.length)
  }

  // 更新单个 Task 状态
  function updateTask(taskId, patch) {
    const t = state.tasks.find((x) => x.id === taskId)
    if (!t) return false
    if (patch.status !== undefined) t.status = patch.status
    if (patch.gateResult !== undefined) t.gateResult = patch.gateResult
    if (patch.retries !== undefined) t.retries = patch.retries
    if (patch.error !== undefined) t.error = patch.error
    state.updatedAt = Date.now()
    log('TASK', taskId + ' -> ' + t.status)
    // Iter-6：任务 FAILED 后按 _onError 处理循环中断
    //   break    → 同组后续 PENDING 迭代标记 SKIPPED（中断）
    //   continue → 不中断，后续迭代继续执行
    if (t.status === E_TASK_STATUS.FAILED && t._onError === 'break') {
      processBreak(taskId)
    }
    return true
  }

  // Iter-7：返回就绪任务列表（dependsOn 全部完成 + 受 max-concurrency 限制）。
  // 就绪 = 所有前驱均 DONE 或 SKIPPED（FAILED 前驱不放行）；
  // 可用并发槽位 = maxConcurrency - 当前 RUNNING 数。
  function getRunnableTasks() {
    const running = state.tasks.filter((t) => t.status === E_TASK_STATUS.RUNNING).length
    const slots = Math.max(0, state.maxConcurrency - running)
    if (slots === 0) return []
    const finished = new Set(
      state.tasks
        .filter((t) => t.status === E_TASK_STATUS.DONE || t.status === E_TASK_STATUS.SKIPPED)
        .map((t) => t.id)
    )
    // 预计算每个并发组：组内 RUNNING 数 + 组级 max（Iter-8）
    const gRun = new Map()
    const gMax = new Map()
    state.tasks.forEach((t) => {
      if (!t._concurrentGroup) return
      gRun.set(t._concurrentGroup, (gRun.get(t._concurrentGroup) || 0) + (t.status === E_TASK_STATUS.RUNNING ? 1 : 0))
      if (!gMax.has(t._concurrentGroup)) gMax.set(t._concurrentGroup, t._concurrentMax || 1)
    })
    const result = []
    for (const t of state.tasks) {
      if (result.length >= slots) break
      if (t.status !== E_TASK_STATUS.PENDING) continue
      const deps = t.dependsOn || []
      if (!deps.every((d) => finished.has(d))) continue
      // Iter-8：并发组组级槽位——组内 RUNNING + 该组已列入 result 的数量 >= 组级 max 则不放行
      if (t._concurrentGroup) {
        const gInResult = result.filter((x) => x._concurrentGroup === t._concurrentGroup).length
        if ((gRun.get(t._concurrentGroup) || 0) + gInResult >= (gMax.get(t._concurrentGroup) || 1)) continue
      }
      result.push(t)
    }
    return result
  }

  function setStage(s) {
    state.stage = s
    state.updatedAt = Date.now()
    if (s === E_STAGE.COMPLETED || s === E_STAGE.FAILED) state.active = false
    log('STAGE', s)
  }

  function setGateResult(r) {
    state.gateResult = r
    state.updatedAt = Date.now()
    log('GATE', 'result=' + r)
  }

  function setRetries(n) {
    state.retries = n
    state.updatedAt = Date.now()
  }

  function setError(msg) {
    state.error = msg || null
    state.updatedAt = Date.now()
    if (msg) log('ERROR', msg)
  }

  function setPersist(r) {
    state.persist = r
  }

  // 当 task FAILED 且 _onError === 'break' 时，将同 _loopGroup 的 PENDING 任务标记为 SKIPPED
  function processBreak(taskId) {
    const failed = state.tasks.find((x) => x.id === taskId)
    if (!failed || !failed._loopGroup || failed._onError !== 'break') return false
    let skipped = 0
    state.tasks.forEach((t) => {
      if (t._loopGroup === failed._loopGroup && t.status === E_TASK_STATUS.PENDING && t.id !== taskId) {
        t.status = E_TASK_STATUS.SKIPPED
        t.error = '循环中断：前序迭代 "' + failed.id + '" 失败'
        skipped++
      }
    })
    if (skipped > 0) log('BREAK', '循环 "' + failed._loopGroup + '" 中断，跳过 ' + skipped + ' 个任务')
    return skipped > 0
  }

  function log(action, detail) {
    state.logs.push({ ts: Date.now(), action, detail })
    if (state.logs.length > 500) state.logs.splice(0, state.logs.length - 500)
  }

  function clear() {
    state.workflow = null
    state.version = null
    state.description = null
    state.params = {}
    state.active = false
    state.stage = E_STAGE.PENDING
    state.tasks = []
    state.gateResult = null
    state.retries = 0
    state.error = null
    state.logs = []
    state.updatedAt = Date.now()
  }

  // 从持久化 payload 恢复实例状态（storage.load 调用）
  function hydrate(j) {
    state.workflow = j.workflow
    state.version = j.version
    state.description = j.description
    state.params = j.params || {}
    state.maxConcurrency = j.maxConcurrency || 1 // Iter-7
    state.active = !!j.active
    state.stage = j.stage || E_STAGE.PENDING
    state.gateResult = j.gateResult || null
    state.retries = j.retries || 0
    state.error = j.error || null
    state.updatedAt = Date.now()
    state.logs = Array.isArray(j.logs) ? j.logs.slice(-200) : []
    state.tasks = Array.isArray(j.tasks) ? j.tasks.map((t, i) => ({
      id: t.id,
      name: t.name,
      type: t.type,
      dependsOn: Array.isArray(t.dependsOn) ? t.dependsOn : [],
      status: t.status || E_TASK_STATUS.PENDING,
      processor: t.processor || null,
      outputs: Array.isArray(t.outputs) ? t.outputs : [],
      gate: t.gate || null,
      gateResult: t.gateResult || null,
      retries: t.retries || 0,
      // Iter-6：恢复循环元数据（processBreak 与 Client DAG 分组依赖）
      _loopGroup: t._loopGroup || null,
      _loopItem: t._loopItem || null,
      _loopIndex: t._loopIndex ?? 0,
      _loopGroupName: t._loopGroupName || null,
      _onError: t._onError || null,
      // Iter-8：并发组元数据（engine 组级并发控制 + Client DAG 分组渲染）
      _concurrentGroup: t._concurrentGroup || null,
      _concurrentGroupName: t._concurrentGroupName || null,
      _concurrentItem: t._concurrentItem || null,
      _concurrentIndex: t._concurrentIndex ?? 0,
      _concurrentMax: t._concurrentMax || null,
    })) : []
    state.updatedAt = Date.now()
  }

  return {
    begin,
    clear,
    hydrate,
    updateTask,
    processBreak,
    getRunnableTasks,
    setStage,
    setGateResult,
    setRetries,
    setError,
    setPersist,
    snapshot,
  }
}


// ---- module: storage ----
// ============================================================================
// workflow-agent — 状态持久化
// 文件：code/plugins/workflow-host/storage.js
// 说明：工作流状态落盘/恢复。
//       修正记录（Iter-1 验收发现）：宿主插件没有 session 上下文，
//       sandboxPolicy.workspaceRoot 在宿主侧解析为「部署根」（DSH 安装目录），
//       直接使用会把状态写入安装目录。因此落盘位置不再依赖该 fallback，
//       改由 workflow_begin 调用方显式指定：
//         - setWorkspaceRoot(root)：状态默认写到 <root>/.workflow-agent/state.json
//         - setStatePath(path)    ：完全自定义状态文件路径
//       两者都未设置时 save() 返回错误、load() 返回 false（不抛异常、不写盘）。
// 依赖：ctx（fs）、engine（snapshot/setPersist/hydrate）。
// Iter-10：新增实例目录模式 setInstanceDir(dir)——落点 <dir>/state.json，
//          优先级高于 workspaceRoot 旧布局（<root>/.workflow-agent/state.json）。
// ============================================================================

function createWorkflowStorage(ctx, engine) {
  const sandboxPolicy = ctx.get('sandboxPolicy')

  let workspaceRoot = sandboxPolicy ? (sandboxPolicy.workspaceRoot || '') : ''
  let explicitStatePath = null
  let statePath = null
  let instanceDir = null // Iter-10：实例目录（优先级最高，落点 <instanceDir>/state.json）

  // 由调用方（workflow_begin）在运行时设置，替代宿主 fallback root
  function setWorkspaceRoot(root) {
    workspaceRoot = (root || '').replace(/\\/g, '/').replace(/\/+$/, '')
    statePath = null // 下次访问时重算
  }

  function setStatePath(p) {
    explicitStatePath = p ? String(p).replace(/\\/g, '/') : null
    statePath = null // 下次访问时重算
  }

  // Iter-10：实例目录模式（由 instance-store 的 beginInstance/hydrateLatest 设置）
  function setInstanceDir(dir) {
    instanceDir = dir ? String(dir).replace(/\\/g, '/').replace(/\/+$/, '') : null
    statePath = null
  }

  // 延迟计算状态文件绝对路径（首次读写时解析）
  async function ensurePath() {
    if (statePath) return statePath
    const fs = ctx.get('fs')
    if (!fs) return null
    if (explicitStatePath) {
      statePath = await fs.resolve(explicitStatePath)
      return statePath
    }
    if (instanceDir) {
      statePath = await fs.resolve(instanceDir + '/state.json')
      return statePath
    }
    if (!workspaceRoot) return null
    const dir = (workspaceRoot + '/.workflow-agent').replace(/\/+/g, '/')
    statePath = await fs.resolve(dir + '/state.json')
    return statePath
  }

  // 显式沙箱写策略：写策略根来自实例目录 > workspaceRoot > 状态文件父目录
  function writePolicy() {
    let root = instanceDir || workspaceRoot
    if (!root && explicitStatePath) {
      const idx = explicitStatePath.lastIndexOf('/')
      root = idx > 0 ? explicitStatePath.slice(0, idx) : explicitStatePath
    }
    return {
      mode: 'workspace-write',
      workspaceRoot: root || '',
    }
  }

  async function save() {
    const fs = ctx.get('fs')
    if (!fs) return 'err: no fs'
    try {
      const p = await ensurePath()
      if (!p) return 'err: no workspaceRoot/statePath（请由 workflow_begin 指定）'
      const snap = engine.snapshot()
      const payload = {
        workflow: snap.workflow,
        version: snap.version,
        description: snap.description,
        params: snap.params,
        active: snap.active,
        stage: snap.stage,
        tasks: snap.tasks,
        gateResult: snap.gateResult,
        retries: snap.retries,
        error: snap.error,
        updatedAt: snap.updatedAt,
        logs: snap.logs,
      }
      await fs.writeText(p, JSON.stringify(payload, null, 2), undefined, undefined, writePolicy())
      const r = 'ok'
      engine.setPersist(r)
      return r
    } catch (e) {
      const r = 'err: ' + ((e && e.message) || String(e))
      engine.setPersist(r)
      return r
    }
  }

  // 恢复：仅当存在有效状态文件时执行
  async function load() {
    const fs = ctx.get('fs')
    if (!fs) return false
    try {
      const p = await ensurePath()
      if (!p) return false
      const text = await fs.readText(p)
      const j = JSON.parse(text)
      if (!j || !j.workflow) return false
      engine.hydrate(j)
      return true
    } catch (e) {
      return false // 无之前状态
    }
  }

  return { save, load, setWorkspaceRoot, setStatePath, setInstanceDir }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { createWorkflowStorage }
}


// ---- module: instance-store ----
// ============================================================================
// workflow-agent — 实例注册表与目录布局（Iter-10 多实例存储）
// 文件：code/plugins/workflow-host/instance-store.js
// 说明：多实例的核心数据结构与目录约定。
//       目录布局（锚点 = session cwd；DSH 沙箱按 session 解析，"A session cwd
//       is its workspace-write boundary"，实例目录建在会话工作区内即拥有完全
//       本地读写权限；Iter-9 探针证实 fs 嵌套写/读回可用）：
//         <cwd>/.workflow-agent/instances/<instanceId>/
//           ├── instance.yaml   # 实例定义快照（源 YAML + 参数注释头，源定义只读）
//           ├── state.json      # engine snapshot（storage.setInstanceDir 落点）
//           ├── metadata.json   # { instanceId, workflowName, sessionId, ... }
//           ├── output/         # 每实例产物
//           └── logs/           # 每实例日志
//       实例 id = slug(workflowName) + '-' + uuid8（设计文档定稿；
//       Iter-9 证实 session id 唯一 guard，uuid8 天然防撞）。
//       metadata.json 是 instanceId↔sessionId 的主映射（重启后惰性 hydrate 依据：
//       session id 跨重启稳定，按 sessionId 精确匹配优先、createdAt 最新兜底）。
// 依赖：ctx（fs）；engine/storage 工厂由 deps 注入（便于 Node 单测）。
// ============================================================================

// ── 工作流名 → 实例 id 前缀（安全文件名片段）────────────────────────────────
function slugifyName(name) {
  const s = String(name || '').toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '')
  return s || 'wf'
}

// ── 8 位十六进制唯一后缀（时间尾 + 随机，实例级足够；目录重名由唯一性兜底）──
function makeUuid8() {
  return (Date.now().toString(16).slice(-4) + Math.random().toString(16).slice(2, 6)).slice(0, 8)
}

// ── 路径计算 ────────────────────────────────────────────────────────────────
function normalizeDir(p) {
  return String(p || '').replace(/\\/g, '/').replace(/\/+$/, '')
}

function instancesRootPath(cwd) {
  return (normalizeDir(cwd) + '/.workflow-agent/instances').replace(/\/+/g, '/')
}

function instanceDirPath(cwd, instanceId) {
  return instancesRootPath(cwd) + '/' + instanceId
}

// ── metadata.json 组装（lossless JSON；sessionId 缺省 null 而非 undefined）──
function composeMetadata(m) {
  return {
    instanceId: m.instanceId,
    workflowName: m.workflowName,
    sessionId: m.sessionId === undefined ? null : m.sessionId,
    sessionCwd: m.sessionCwd || null,
    sourcePath: m.sourcePath || null,
    params: m.params && typeof m.params === 'object' ? m.params : {},
    createdAt: m.createdAt || new Date().toISOString(),
  }
}

// ── 实例注册表：instanceId → {engine, storage, meta}；sessionId → 活跃实例 ──
function createInstanceRegistry(ctx, deps) {
  const engines = new Map()        // instanceId -> entry
  const activeBySession = new Map() // sessionId -> instanceId

  function get(instanceId) {
    return engines.get(instanceId)
  }

  function activeIdFor(sessionId) {
    return activeBySession.get(sessionId)
  }

  // 工具执行上下文 → sessionId（与 tools-preset 的 sessionCwd 同构）
  function sessionIdOf(exec) {
    try {
      const id = exec && exec.agent && exec.agent.session && exec.agent.session.header && exec.agent.session.header.id
      return typeof id === 'string' && id.length > 0 ? id : undefined
    } catch (e) {
      return undefined
    }
  }

  // ── 创建实例目录 + 引擎条目（workflow_begin 成功路径调用）────────────────
  async function beginInstance(opts) {
    const fs = ctx.get('fs')
    if (!fs) throw new Error('fs service unavailable')
    const cwd = normalizeDir(opts.cwd)
    if (!cwd) throw new Error('session cwd 未提供，无法创建实例目录')
    const workflowName = opts.workflowName || 'wf'
    const instanceId = slugifyName(workflowName) + '-' + makeUuid8()
    const dir = instanceDirPath(cwd, instanceId)
    const meta = composeMetadata({
      instanceId,
      workflowName,
      sessionId: opts.sessionId,
      sessionCwd: cwd,
      sourcePath: opts.sourcePath,
      params: opts.params,
    })
    // 目录 + 固定文件（fs.writeText 自动建父目录；Iter-9 探针 P7 已验证嵌套写）
    await fs.writeText(await fs.resolve(dir + '/metadata.json'), JSON.stringify(meta, null, 2))
    const header = [
      '# workflow 实例定义快照（参数化副本；源定义文件保持只读）',
      '# source: ' + (opts.sourcePath || '(inline workflowText)'),
      '# instanceId: ' + instanceId,
      '# createdAt: ' + meta.createdAt,
      '# params: ' + JSON.stringify(opts.params || {}),
      '',
    ].join('\n')
    await fs.writeText(await fs.resolve(dir + '/instance.yaml'), header + String(opts.sourceText || ''))
    await fs.writeText(await fs.resolve(dir + '/output/.gitkeep'), '')
    await fs.writeText(await fs.resolve(dir + '/logs/.gitkeep'), '')
    // 引擎 + 存储（engine 零改造；存储落点 = 实例目录 state.json）
    const engine = deps.createWorkflowEngine()
    const storage = deps.createWorkflowStorage(ctx, engine)
    storage.setInstanceDir(dir)
    const entry = { instanceId, dir, meta, engine, storage }
    engines.set(instanceId, entry)
    if (opts.sessionId) activeBySession.set(opts.sessionId, instanceId)
    return entry
  }

  // ── 会话当前活跃实例；未命中则按实例目录惰性恢复（DSH 重启后首次调用）────
  async function forSession(exec) {
    const sessionId = sessionIdOf(exec)
    const hit = sessionId ? activeBySession.get(sessionId) : undefined
    if (hit && engines.get(hit)) return engines.get(hit)
    const cwd = (function () {
      try {
        const c = exec && exec.agent && exec.agent.session && exec.agent.session.header && exec.agent.session.header.cwd
        return typeof c === 'string' && c ? c : undefined
      } catch (e) {
        return undefined
      }
    })()
    if (!cwd) return undefined
    const restored = await hydrateLatest(cwd, sessionId)
    if (!restored) return undefined
    if (sessionId) activeBySession.set(sessionId, restored.instanceId)
    return restored
  }

  // ── 扫描实例目录恢复最新实例（metadata.sessionId 精确匹配优先）────────────
  async function hydrateLatest(cwd, sessionId) {
    const fs = ctx.get('fs')
    if (!fs) return undefined
    let dirs = []
    try {
      const entries = await fs.listDir(await fs.resolve(instancesRootPath(cwd)))
      dirs = entries.filter(en => en.type === 'directory').map(en => en.name)
    } catch (e) {
      return undefined // 无 instances 目录（该 cwd 从未运行过实例）
    }
    const candidates = []
    for (const id of dirs) {
      try {
        const meta = JSON.parse(await fs.readText(await fs.resolve(instanceDirPath(cwd, id) + '/metadata.json')))
        if (!meta || meta.instanceId !== id) continue
        const state = JSON.parse(await fs.readText(await fs.resolve(instanceDirPath(cwd, id) + '/state.json')))
        if (!state || !state.workflow) continue
        candidates.push({ meta, state })
      } catch (e) { /* 残缺实例目录跳过 */ }
    }
    if (candidates.length === 0) return undefined
    const matched = sessionId ? candidates.find(c => c.meta.sessionId === sessionId) : null
    const best = matched || candidates.sort((a, b) => String(b.meta.createdAt || '').localeCompare(String(a.meta.createdAt || '')))[0]
    const dir = instanceDirPath(cwd, best.meta.instanceId)
    const engine = deps.createWorkflowEngine()
    const storage = deps.createWorkflowStorage(ctx, engine)
    storage.setInstanceDir(dir)
    engine.hydrate(best.state)
    const entry = { instanceId: best.meta.instanceId, dir, meta: best.meta, engine, storage }
    engines.set(entry.instanceId, entry)
    return entry
  }

  return {
    beginInstance,
    forSession,
    hydrateLatest,
    get,
    activeIdFor,
    sessionIdOf,
    engines,
    activeBySession,
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { slugifyName, makeUuid8, instancesRootPath, instanceDirPath, composeMetadata, createInstanceRegistry }
}

// ---- module: tools-preset ----
// ============================================================================
// workflow-agent — Host 模型工具（preset 本地插件版）
// 文件：code/plugins/workflow-host-preset/tools-preset.js
// 说明：与 plugins/workflow-host/tools.js 相同的两个工具定义，但注册方式改为
//       ctx.tools.register（preset 本地 .mjs 插件形态，custom-bash.mjs /
//       dsh-tool-workflow 先例），而非动态插件的 harness.defineTool。
//       另外从 exec.agent.session.header.cwd 取会话工作区作为默认落盘根，
//       解决宿主插件无会话上下文时写错目录的问题。
// 依赖：ctx（fs/exec）、engine、storage、schema/parser 常量（同作用域内联）。
// ============================================================================

// ── 相对路径解析（复用 PoC 逐级上探逻辑）───────────────────────────────────
function parentDir(p) {
  const norm = p.replace(/\\/g, '/')
  const idx = norm.lastIndexOf('/')
  if (idx <= 0) return null
  return norm.slice(0, idx)
}

// 从 YAML 所在目录逐级向上探测，取第一个真实存在的拼接；兜底用 YAML 目录
async function resolveRel(fs, base, rel) {
  let d = base
  while (d) {
    const cand = d + '/' + rel.replace(/\\/g, '/')
    try {
      const st = await fs.stat(await fs.resolve(cand))
      if (st) return cand
    } catch (e) { /* keep climbing */ }
    d = parentDir(d)
  }
  return base + '/' + rel.replace(/\\/g, '/')
}

// ── ${param} 注入 ───────────────────────────────────────────────────────────
// PARAM_PATTERN 默认由同作用域 schema 模块提供；独立加载（Node 直测）时兜底
let E_PARAM_PATTERN = typeof PARAM_PATTERN !== 'undefined' ? PARAM_PATTERN : /\$\{(\w+)\}/g
function injectParams(value, params) {
  if (typeof value !== 'string') return value
  return value.replace(E_PARAM_PATTERN, (whole, key) => {
    if (params && params[key] !== undefined) return String(params[key])
    return whole // 未提供则保留原样，由调用方提示
  })
}

function injectArray(list, params) {
  return (list || []).map((x) => injectParams(x, params))
}

// v1.1：命名式 inputs 注入。值为 string → 注入后返回 string；
// 值为 string[] → 逐项注入后返回 string[]。
function injectInputsMap(map, params) {
  const out = {}
  for (const k of Object.keys(map || {})) {
    const v = map[k]
    out[k] = Array.isArray(v) ? v.map((x) => injectParams(x, params)) : injectParams(v, params)
  }
  return out
}

// 工作流文件加载：优先 workflowPath（读文件），兜底 workflowText（直接用）
async function loadWorkflowSource(fs, args) {
  if (args.workflowPath) {
    const p = String(args.workflowPath)
    const text = await fs.readText(await fs.resolve(p))
    return { text, base: p.replace(/[\\/][^\\/]*$/, '') }
  }
  if (args.workflowText) {
    return { text: String(args.workflowText), base: undefined }
  }
  return null
}

// ── 循环展开：将 loop Task 展开为 N 个串行迭代实例 ────────────────────────
// items 参数：从 items-from 文件解析出的非空非注释行数组
// itemVar：迭代变量名（如 "module"），在 inputs/outputs 中解决 ${itemVar}
// params：已注入的工作流级参数
// loopTask：原始 loop Task 对象（含 inputsRaw/outputsRaw/processor/gate/dependsOn）
// prevDeps：【内部使用】前一个迭代的 id，用于构建串行依赖链
async function expandLoopTasks(fs, loopTask, items, itemVar, params) {
  const expanded = []
  const loopDeps = loopTask.dependsOn || []
  let prevId = null

  for (let i = 0; i < items.length; i++) {
    const item = String(items[i]).trim()
    if (!item) continue

    // 构建迭代参数（工作流 params + 当前 item）
    const iterParams = { ...params }
    iterParams[itemVar] = item

    // 安全 ID：loopTaskId/sanitized-item
    const sanitized = item.replace(/[^a-zA-Z0-9_\-]/g, '-').replace(/^-+|-+$/g, '') || ('iter-' + i)
    const iterId = loopTask.id + '/' + sanitized

    // inputs/outputs 重新注入（含 item 变量）
    const iterInputs = injectInputsMap(loopTask.inputsRaw || {}, iterParams)
    const iterOutputs = injectArray(loopTask.outputsRaw || [], iterParams)

    // processor 路径重新注入（含 item 变量——虽然通常不变）
    const iterProcessor = injectParams(loopTask.processor || '', iterParams)

    // gate 复制（同一 checker，独立执行）
    const iterGate = loopTask.gate ? {
      checker: loopTask.gate.checker,
      onFailure: loopTask.gate.onFailure,
      maxRetries: loopTask.gate.maxRetries,
    } : null

    expanded.push({
      id: iterId,
      name: (loopTask.name || loopTask.id) + ' - ' + item,
      type: 'llm-task',
      dependsOn: prevId ? [prevId] : loopDeps,
      timeout: loopTask.timeout || 600,
      processor: iterProcessor,
      inputs: iterInputs,
      outputs: iterOutputs,
      gate: iterGate,
      // 循环错误处理策略
      _onError: loopTask.onError || 'break',
      // 循环组元数据（供 Client DAG 分组渲染）
      _loopGroup: loopTask.id,
      _loopGroupName: loopTask.name || loopTask.id,
      _loopItem: item,
      _loopIndex: i,
    })
    prevId = iterId
  }

  return expanded
}

// Iter-8：并发展开——对 items 的每个 item 生成一个独立迭代，迭代之间无依赖（可并发，受组级 max 约束）
async function expandConcurrentTasks(fs, task, items, itemVar, params) {
  const expanded = []
  const loopDeps = task.dependsOn || []
  const gMax = task.maxConcurrency || items.length // 组级并发（默认 items 数量，全部并发）

  for (let i = 0; i < items.length; i++) {
    const item = String(items[i]).trim()
    if (!item) continue

    const iterParams = { ...params }
    iterParams[itemVar] = item

    const sanitized = item.replace(/[^a-zA-Z0-9_\-]/g, '-').replace(/^-+|-+$/g, '') || ('iter-' + i)
    const iterId = task.id + '/' + sanitized

    const iterInputs = injectInputsMap(task.inputsRaw || {}, iterParams)
    const iterOutputs = injectArray(task.outputsRaw || [], iterParams)
    const iterProcessor = injectParams(task.processor || '', iterParams)

    const iterGate = task.gate ? {
      checker: task.gate.checker,
      onFailure: task.gate.onFailure,
      maxRetries: task.gate.maxRetries,
    } : null

    expanded.push({
      id: iterId,
      name: (task.name || task.id) + ' - ' + item,
      type: 'llm-task',
      dependsOn: loopDeps, // ← 关键：无串行依赖链，都依赖原始前驱 → 可并发
      timeout: task.timeout || 600,
      processor: iterProcessor,
      inputs: iterInputs,
      outputs: iterOutputs,
      gate: iterGate,
      // 并发组元数据（Client DAG 分组渲染 + engine 组级并发控制）
      _concurrentGroup: task.id,
      _concurrentGroupName: task.name || task.id,
      _concurrentItem: item,
      _concurrentIndex: i,
      _concurrentMax: gMax,
    })
  }

  return expanded
}

// 从工具执行上下文取会话工作区（preset 挂载后 exec.agent 可用）
function sessionCwd(exec) {
  try {
    const cwd = exec && exec.agent && exec.agent.session && exec.agent.session.header && exec.agent.session.header.cwd
    return typeof cwd === 'string' && cwd.length > 0 ? cwd : undefined
  } catch (e) {
    return undefined
  }
}

// 注册工具：preset 本地插件形态（ctx.tools.register），不依赖 harness
// Iter-10：新增 registry 参数（instance-store 的 createInstanceRegistry 产物）。
//   - 会话上下文 + 无显式 statePath/workspaceRoot 参数 → 实例布局：
//     begin 时创建实例目录并绑定新 engine/storage；status 时按会话取活跃实例
//     （重启后惰性 hydrate）。快照附 instanceId 供调用方/前端识别。
//   - 显式 statePath/workspaceRoot 参数或无会话上下文 → 回退单实例绑定
//     （engine/storage 形参，保持既有行为与旧布局兼容）。
function registerWorkflowToolsPreset(ctx, engine, storage, registry) {
  const fs = ctx.get('fs')

  // ── 每次工具调用解析绑定的引擎/存储（避免跨会话闭包串扰，多会话并行安全）──
  async function bind(exec, args) {
    if (args && (args.statePath || args.workspaceRoot)) {
      return { engine, storage, instanceId: null }
    }
    if (registry) {
      const entry = await registry.forSession(exec)
      if (entry) return { engine: entry.engine, storage: entry.storage, instanceId: entry.instanceId }
    }
    return { engine, storage, instanceId: null }
  }

  function withInstanceId(snapshot, b) {
    if (b && b.instanceId) snapshot.instanceId = b.instanceId
    return snapshot
  }

  // ── workflow_begin ────────────────────────────────────────────────────────
  const beginTool = {
    name: 'workflow_begin',
    description: '解析并启动一个工作流定义（YAML）。参数 workflowPath 为本机绝对路径；或传 workflowText 直接给 YAML 文本。可选 params 对象注入工作流级 ${param} 模板变量。可选 workspaceRoot / statePath 指定状态落盘位置（兼容旧单实例布局）；默认在当前会话工作区创建实例目录 <cwd>/.workflow-agent/instances/<workflowName-uuid8>/（instance.yaml/state.json/metadata.json/output/logs），状态写入实例目录。成功返回解析出的任务列表（含处理技能绝对路径、门禁配置、instanceId）与初始 PENDING 状态；定义不合法时返回 errors 列表。',
    parameters: {
      type: 'object',
      additionalProperties: true,
      properties: {
        workflowPath: { type: 'string', description: '工作流 YAML 的绝对路径' },
        workflowText: { type: 'string', description: '工作流 YAML 文本（与 workflowPath 二选一）' },
        workspaceRoot: { type: 'string', description: '（兼容旧布局）状态落盘根目录；默认走实例目录布局' },
        statePath: { type: 'string', description: '（兼容旧布局）完全自定义的状态文件绝对路径' },
        params: {
          type: 'object',
          additionalProperties: true,
          description: '工作流参数，替换字段中的 ${param_name}',
        },
      },
    },
    output: {
      schema: { type: 'object', additionalProperties: true },
      render(_a, v) {
        return [{ type: 'text', text: JSON.stringify(v, null, 2) }]
      },
    },
    async execute(args, exec) {
      // 初始绑定（错误路径也要能落盘）
      let b = await bind(exec, args)
      try {
        if (!fs) throw new Error('fs service unavailable')
        if (args && args.workspaceRoot && b.storage) b.storage.setWorkspaceRoot(String(args.workspaceRoot))
        if (args && args.statePath && b.storage) b.storage.setStatePath(String(args.statePath))
        // 未显式指定 workspaceRoot 时，从会话上下文取工作区（legacy 单实例布局落点）
        if ((!args || !args.workspaceRoot) && b.storage) {
          const cwd = sessionCwd(exec)
          if (cwd) b.storage.setWorkspaceRoot(cwd)
        }
        const src = await loadWorkflowSource(fs, args)
        if (!src) throw new Error('需要 workflowPath 或 workflowText 参数')
        const parsed = parseWorkflow(src.text)
        const params = (args && args.params) || {}
        if (parsed.errors && parsed.errors.length > 0) {
          b.engine.setError('workflow 定义不合法: ' + parsed.errors.join('; '))
          await b.storage.save()
          const s = b.engine.snapshot()
          s.workflowBeginErrors = parsed.errors
          return withInstanceId(s, b)
        }
        // 注入 params + 解析相对路径为绝对路径
        const tasks = await Promise.all(parsed.tasks.map(async (t) => {
          const out = { ...t }
          out.inputs = injectInputsMap(t.inputsRaw, params)
          out.outputs = injectArray(t.outputsRaw, params)
          if (t.processorRaw) {
            const procRel = injectParams(t.processorRaw, params)
            out.processor = src.base ? await resolveRel(fs, src.base, procRel) : procRel
          }
          if (t.gateRaw) {
            const gateRel = injectParams(t.gateRaw, params)
            out.gate = {
              checker: src.base ? await resolveRel(fs, src.base, gateRel) : gateRel,
              onFailure: t.gateOnFailure,
              maxRetries: t.gateMaxRetries,
            }
          }
          if (t.itemsFromRaw) {
            const itemsRel = injectParams(t.itemsFromRaw, params)
            out.itemsFrom = src.base ? await resolveRel(fs, src.base, itemsRel) : itemsRel
            out.itemsFromRaw = t.itemsFromRaw // 保留原始值供循环展开二次注入
            out.itemVar = t.itemVar
          }
          return out
        }))
        parsed.tasks = tasks

        // ── 循环/并发展开 ──
        const finalTasks = []
        for (const t of tasks) {
          if (t.type === 'loop' && t.itemsFrom && t.itemVar) {
            // 循环：读取 items-from 文件，串行展开（迭代之间有依赖链）
            const text = await fs.readText(await fs.resolve(t.itemsFrom))
            const items = text.split(/\r?\n/).map(l => l.trim()).filter(l => l && !l.startsWith('#'))
            if (items.length === 0) {
              b.engine.setError('循环 Task "' + t.id + '" 的 items-from 文件为空: ' + t.itemsFrom)
              await b.storage.save()
              return withInstanceId(b.engine.snapshot(), b)
            }
            const iterations = await expandLoopTasks(fs, t, items, t.itemVar, params)
            finalTasks.push(...iterations)
          } else if (t.type === 'concurrent' && t.itemsFrom && t.itemVar) {
            // Iter-8：并发——读取 items-from 文件，迭代之间无依赖（可并发，受组级 max 约束）
            const text = await fs.readText(await fs.resolve(t.itemsFrom))
            const items = text.split(/\r?\n/).map(l => l.trim()).filter(l => l && !l.startsWith('#'))
            if (items.length === 0) {
              b.engine.setError('并发 Task "' + t.id + '" 的 items-from 文件为空: ' + t.itemsFrom)
              await b.storage.save()
              return withInstanceId(b.engine.snapshot(), b)
            }
            const iterations = await expandConcurrentTasks(fs, t, items, t.itemVar, params)
            finalTasks.push(...iterations)
          } else {
            finalTasks.push(t)
          }
        }
        parsed.tasks = finalTasks

        // ── Iter-10：多实例布局——成功路径创建实例目录并切换绑定 ──
        // （解析/展开失败不建实例目录；显式 statePath/workspaceRoot 参数走旧布局）
        if (registry && !args.statePath && !args.workspaceRoot) {
          const cwd = sessionCwd(exec)
          if (cwd) {
            const entry = await registry.beginInstance({
              cwd,
              sessionId: registry.sessionIdOf(exec),
              workflowName: parsed.name,
              sourceText: src.text,
              sourcePath: args.workflowPath || null,
              params,
            })
            b = { engine: entry.engine, storage: entry.storage, instanceId: entry.instanceId }
          }
        }

        b.engine.begin(parsed)
        b.engine.setError(null)
        const r = await b.storage.save()
        b.engine.setPersist(r)
        return withInstanceId(b.engine.snapshot(), b)
      } catch (error) {
        b.engine.setError(error.message)
        await b.storage.save()
        return withInstanceId(b.engine.snapshot(), b)
      }
    },
  }
  ctx.tools.register(beginTool)

  // ── workflow_status ───────────────────────────────────────────────────────
  const statusTool = {
    name: 'workflow_status',
    description: '按编排进展更新工作流状态并同步持久化与 UI：stage（PENDING|RUNNING|COMPLETED|FAILED）、gateResult（PASS|FAIL）、task/tasktatus 更新单个任务（PENDING|RUNNING|DONE|FAILED|SKIPPED）、retries 重试计数、error 错误信息。状态写入当前会话活跃实例目录的 state.json（重启后自动从实例目录恢复）。每次调用返回最新快照（含 instanceId）。',
    parameters: {
      type: 'object',
      additionalProperties: true,
      properties: {
        stage: { type: 'string', description: '全局阶段' },
        gateResult: { type: 'string', description: '门禁结果 PASS 或 FAIL' },
        task: { type: 'string', description: '要更新的任务 id' },
        taskStatus: { type: 'string', description: '该任务状态' },
        retries: { type: 'number', description: '失败重试计数' },
        error: { type: 'string', description: '错误信息' },
      },
    },
    output: {
      schema: { type: 'object', additionalProperties: true },
      render(_a, v) {
        return [{ type: 'text', text: JSON.stringify(v, null, 2) }]
      },
    },
    async execute(args, exec) {
      const b = await bind(exec, args)
      try {
        if (!args) args = {}
        if (args.stage) b.engine.setStage(String(args.stage))
        if (args.gateResult) b.engine.setGateResult(String(args.gateResult))
        if (typeof args.retries === 'number') b.engine.setRetries(args.retries)
        if (args.error !== undefined) b.engine.setError(args.error ? String(args.error) : null)
        if (args.task && args.taskStatus) {
          b.engine.updateTask(String(args.task), { status: String(args.taskStatus) })
        }
        const r = await b.storage.save()
        b.engine.setPersist(r)
        return withInstanceId(b.engine.snapshot(), b)
      } catch (error) {
        b.engine.setError(error.message)
        return withInstanceId(b.engine.snapshot(), b)
      }
    },
  }
  ctx.tools.register(statusTool)
}

// 供 Node 独立验证（与宿主体内同构）：{ registerWorkflowToolsPreset, resolveRel, injectParams, injectArray, injectInputsMap, sessionCwd }
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { registerWorkflowToolsPreset, resolveRel, injectParams, injectArray, injectInputsMap, sessionCwd, expandLoopTasks, expandConcurrentTasks }
}

// ---- module: webserver-routes ----
// ============================================================================
// workflow-agent — Host webServer HTTP 路由（Iter-5，替代 harness RPC）
// 文件：code/agent-presets/workflow-orchestrator/workflow-host.mjs 末尾
// 说明：注册 /wf/* 前缀路由，供 Client 面板轮询状态/读取技能/验证工作区。
//       参考先例：@linxin666/dsh-tool-describe-image（npm 包 + webServer + fetch）。
// 依赖：ctx.get('webServer')、ctx.get('fs')。webServer 不存在时静默跳过
//       （路由注册是可选能力，不影响工具注册）。
// ============================================================================

// ── loopback 信任围栏（仿 describe-image 的 shared/host/loopback）──────────
// IPv4 127/8、::1、IPv4-mapped ::ffff:127/8，加上浏览器 same-origin 标记
function isLoopbackAddress(address) {
  if (address === undefined || address === null) return false
  const normalized = String(address).toLowerCase()
  if (normalized === '::1') return true
  if (normalized.startsWith('::ffff:')) {
    return isIPv4Loopback(normalized.slice('::ffff:'.length))
  }
  return isIPv4Loopback(normalized)
}

function isIPv4Loopback(v4) {
  const parts = v4.split('.')
  return parts.length === 4
    && parts[0] === '127'
    && parts.every(part => /^\d{1,3}$/.test(part) && Number(part) <= 255)
}

function isLoopbackHostname(hostname) {
  if (hostname === 'localhost' || hostname === '[::1]') return true
  return isIPv4Loopback(hostname)
}

function isLoopbackRequest(request) {
  if (!isLoopbackAddress(request.socket && request.socket.remoteAddress)) return false
  const host = request.headers && request.headers.host
  if (typeof host !== 'string') return false
  let hostUrl
  try {
    hostUrl = new URL('http://' + host)
  } catch (e) {
    return false
  }
  if (!isLoopbackHostname(hostUrl.hostname)) return false
  if (request.headers['sec-fetch-site'] === 'cross-site') return false
  const origin = request.headers.origin
  if (origin === undefined) return true
  try {
    return new URL(origin).host === hostUrl.host
  } catch (e) {
    return false
  }
}

// ── JSON 响应辅助 ──────────────────────────────────────────────────────────
function writeJson(res, status, body) {
  const payload = JSON.stringify(body)
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' })
  res.end(payload)
}

// ── 从指定工作区读取 state.json（与 workflow-rpc.mjs 的 loadState 同构）────
// Iter-10：支持实例布局。优先级：instances/<instanceId>（精确）→
// instances/ 下 metadata.createdAt 最新的实例 → 旧单实例布局回退。
async function loadStateFromFile(fs, workspaceRoot, instanceId) {
  if (!fs) return { state: null, error: 'fs service unavailable' }
  try {
    const root = (workspaceRoot || '').replace(/\\/g, '/').replace(/\/+$/, '')
    if (!root) return { state: null, error: 'workspaceRoot not specified' }
    const instancesRoot = root + '/.workflow-agent/instances'
    if (instanceId) {
      const resolved = await fs.resolve(instancesRoot + '/' + instanceId + '/state.json')
      const state = JSON.parse(await fs.readText(resolved))
      return { state, error: null, instanceId }
    }
    let dirs = []
    try {
      const entries = await fs.listDir(await fs.resolve(instancesRoot))
      dirs = entries.filter(en => en.type === 'directory').map(en => en.name)
    } catch (e) { dirs = [] } // 无 instances 目录
    if (dirs.length > 0) {
      let best = null
      for (const id of dirs) {
        try {
          const meta = JSON.parse(await fs.readText(await fs.resolve(instancesRoot + '/' + id + '/metadata.json')))
          if (!best || String(meta.createdAt || '') > String(best.createdAt || '')) best = { id, createdAt: meta.createdAt }
        } catch (e) { /* 残缺实例目录跳过 */ }
      }
      if (best) {
        const resolved = await fs.resolve(instancesRoot + '/' + best.id + '/state.json')
        const state = JSON.parse(await fs.readText(resolved))
        return { state, error: null, instanceId: best.id }
      }
    }
    // 旧单实例布局回退（demo 数据兼容）
    const statePath = root + '/.workflow-agent/state.json'
    const resolved = await fs.resolve(statePath)
    const state = JSON.parse(await fs.readText(resolved))
    return { state, error: null }
  } catch (e) {
    return { state: null, error: e && e.message ? e.message : String(e) }
  }
}

// ── 注册 /wf/* 路由 ────────────────────────────────────────────────────────
// GET /wf/status?workspaceRoot=...   → 工作流状态快照 {state, error}
// GET /wf/skill?path=...             → 技能文件全文 {text, error}
// GET /wf/config?workspaceRoot=...   → 验证工作区 {valid, workspaceRoot, error}
function registerWebRoutes(ctx) {
  const webserver = ctx.get('webServer')
  if (!webserver) return // 可选能力：webServer 不存在时静默跳过
  const fs = ctx.get('fs')

  webserver.register({
    kind: 'prefix',
    path: '/wf',
    handler: async (req, res) => {
      // loopback 围栏优先：LAN/跨站调用一律 403
      if (!isLoopbackRequest(req)) {
        writeJson(res, 403, { error: 'forbidden: loopback-only' })
        return
      }
      let pathname = '/'
      let search = ''
      try {
        const url = new URL(req.url || '/', 'http://x')
        pathname = url.pathname
        search = url.search
      } catch (e) {
        writeJson(res, 400, { error: 'malformed url' })
        return
      }
      const query = new URLSearchParams(search)

      if (pathname === '/wf/status') {
        const result = await loadStateFromFile(fs, query.get('workspaceRoot') || '', query.get('instanceId') || '')
        writeJson(res, 200, result)
        return
      }

      if (pathname === '/wf/skill') {
        if (!fs) {
          writeJson(res, 200, { text: null, error: 'fs service unavailable' })
          return
        }
        try {
          const path = query.get('path') || ''
          if (!path) {
            writeJson(res, 200, { text: null, error: 'no file path provided' })
            return
          }
          const resolved = await fs.resolve(path)
          const text = await fs.readText(resolved)
          writeJson(res, 200, { text, error: null })
        } catch (e) {
          writeJson(res, 200, { text: null, error: e && e.message ? e.message : String(e) })
        }
        return
      }

      if (pathname === '/wf/config') {
        const root = (query.get('workspaceRoot') || '').replace(/\\/g, '/').replace(/\/+$/, '')
        if (root && fs) {
          try {
            let valid = false
            let error = null
            try {
              await fs.resolve(root + '/.workflow-agent/state.json')
              valid = true
            } catch (eLegacy) {
              // Iter-10：实例布局也算有效工作区（存在实例目录即可）
              try {
                const entries = await fs.listDir(await fs.resolve(root + '/.workflow-agent/instances'))
                valid = entries.some(en => en.type === 'directory')
                if (!valid) error = 'no instance directories under ' + root + '/.workflow-agent/instances'
              } catch (eInst) {
                error = 'state.json not found at ' + root + '/.workflow-agent/state.json'
              }
            }
            if (valid) writeJson(res, 200, { valid: true, workspaceRoot: root })
            else writeJson(res, 200, { valid: false, workspaceRoot: root, error })
          } catch (e) {
            writeJson(res, 200, { valid: false, workspaceRoot: root, error: e && e.message ? e.message : String(e) })
          }
        } else {
          writeJson(res, 200, { valid: false, workspaceRoot: root, error: 'workspaceRoot not provided' })
        }
        return
      }

      writeJson(res, 404, { error: 'not found: ' + pathname })
    },
  })
}

// 供 Node 独立验证（与宿主体内同构）：{ registerWorkflowToolsPreset, resolveRel, injectParams, injectArray, injectInputsMap, sessionCwd, registerWebRoutes, loadStateFromFile, createWorkflowStorage, slugifyName, makeUuid8, instancesRootPath, instanceDirPath, composeMetadata, createInstanceRegistry }
// （Iter-10 起实例注册表源码在 code/plugins/workflow-host/instance-store.js，Node 测试直接 require 源模块）

  
  // 执行初始化
  applyInternal(ctx)
}
