#!/usr/bin/env node
/**
 * Workflow Agent Host 插件 - 构建脚本（npm 包版）
 * 
 * 将 workflow-host.mjs 转换为 npm 包格式（CommonJS）。
 * 注意：RPC 处理器（workflow-rpc.mjs）不包含在 npm 包中，
 * 因为 harness Builtin 仅在动态插件中可用。RPC 保留在
 * agent preset 的本地插件中。
 * 
 * 用法: node build.js
 */

const fs = require('fs')
const path = require('path')

console.log('Building @workflow-agent/workflow-host (npm package, tools only, CommonJS)...')

// 读取源文件（仅 host 部分，不含 RPC）
const hostPath = path.join(__dirname, '..', '..', 'agent-presets', 'workflow-orchestrator', 'workflow-host.mjs')

let hostCode = fs.readFileSync(hostPath, 'utf-8')

// 移除原始 export 语句，转换为内部代码
// 注意：workflow-host.mjs 的 apply 签名可能是 (ctx) 或 (ctx, config)
hostCode = hostCode
  .replace(/^export const name = .*$/m, '')
  .replace(/^export const inject = .*$/m, '')
  .replace(/^export function apply\(ctx\)\s*\{/m, 'function applyInternal(ctx) {')
  .replace(/^export function apply\(ctx, config\)\s*\{/m, 'function applyInternal(ctx) {')
  // 移除 Iter-13 添加的 ESM 具名导出（CommonJS 不需要）
  .replace(/^export \{ registerWebRoutes, loadStateFromFile \}$/m, '')

// 生成 npm 包格式的插件（CommonJS）
// 注意：inject 包含实际使用的服务（fs 用于文件操作，tools 用于工具注册，
// webServer 用于 HTTP 路由 — Iter-5 替代 harness RPC）
// harness 是动态插件 Builtin，npm 包不可用；RPC 处理器由 webServer 路由替代
const outputCode = `// @workflow-agent/workflow-host - Host Plugin (npm package)
// Auto-generated by build.js - DO NOT EDIT
// 提供工具注册（workflow_begin / workflow_status）+ webServer HTTP 路由（/wf/*）。
// 不再依赖 harness Builtin；RPC 处理器（workflow-rpc.mjs）已停用。

const name = 'workflow-host'
const inject = ['fs', 'tools', 'webServer', 'subagents', 'agents']

function apply(ctx) {
  ${hostCode}
  
  // 执行初始化
  applyInternal(ctx)
}

module.exports = { name, inject, apply }
`

// 确保 lib 目录存在
const libDir = path.join(__dirname, 'lib')
fs.mkdirSync(libDir, { recursive: true })

// 写入 lib/index.js
const outputPath = path.join(libDir, 'index.js')
fs.writeFileSync(outputPath, outputCode, 'utf-8')

console.log('✓ Built lib/index.js (CommonJS)')
console.log(`  Host source: ${hostCode.length} chars`)
console.log(`  Output: ${outputCode.length} chars`)
console.log('')
console.log('Note: RPC handlers replaced by webServer routes (Iter-5).')
console.log('      workflow-rpc.mjs in agent-presets is retired.')
console.log('')
console.log('Build complete!')
