// AUTO-GENERATED by code/scripts/build-preset.js — workflow-orchestrator host plugin
// 源文件: code/shared/workflow-schema.js, code/shared/workflow-parser.js, code/plugins/workflow-host/engine.js, code/plugins/workflow-host/storage.js, code/plugins/workflow-host-preset/tools-preset.js
// 形态：Agent Preset 本地插件（ESM），agent.cordis.yml 以 ./workflow-host.mjs 挂载。
// 注册：ctx.tools.register（与 dsh-tool-workflow/custom-bash 一致）；
//       落盘根默认取 exec.agent.session.header.cwd（会话工作区）。

export const name = 'workflow-host'
export const inject = ['fs', 'tools']

export function apply(ctx) {
  const engine = createWorkflowEngine()
  const storage = createWorkflowStorage(ctx, engine)
  if (storage) {
    storage.load().catch(() => {})
  }
  if (ctx.get('tools')) {
    registerWorkflowToolsPreset(ctx, engine, storage)
  }
  // Iter-5：webServer HTTP 路由（替代 harness RPC，供 Client 面板轮询状态）
  registerWebRoutes(ctx)
  ctx.effect(() => () => {})
}

// ---- module: workflow-schema ----
// ============================================================================
// workflow-agent — 共享 Schema 常量与校验规则
// 文件：code/shared/workflow-schema.js
// 说明：纯逻辑模块（无 DSH/Cordis 依赖），可被 Node 直接 require 测试，
//       宿主插件内联打包时按模块源码拼接。
// ============================================================================

// ── Task 类型枚举 ──────────────────────────────────────────────────────────
const TASK_TYPES = {
  LLM_TASK: 'llm-task',
  LOOP: 'loop',
  HUMAN_DECISION: 'human-decision', // 预留（后续迭代）
  EXTERNAL_AGENT: 'external-agent', // 预留（后续迭代）
}

// ── 字段默认值 ─────────────────────────────────────────────────────────────
const DEFAULTS = {
  timeout: 600, // 秒
  dependsOn: [],
  taskType: TASK_TYPES.LLM_TASK,
  retries: 0, // quality-gate max-retries 默认
  onFailure: 'block', // quality-gate on-failure 默认
}

// ── 必填字段校验规则 ────────────────────────────────────────────────────────
const REQUIRED = {
  llmTask: ['id', 'processor'],
  loop: ['id', 'processor', 'items-from', 'item-var'],
  humanDecision: ['id', 'prompt'],
  externalAgent: ['id', 'agent'],
}

// ── 循环错误处理策略 ──────────────────────────────────────────────────────────
const ON_ERROR_VALUES = ['break', 'continue']

// ─ 支持 uality-gate on-failure  的策略值 ──────────────────────────────────
const ON_FAILURE_VALUES = ['retry', 'block', 'skip']

// ── 参数模板正则（${param_name} / ${item}） ────────────────────────────────
const PARAM_PATTERN = /\$\{(\w+)\}/g

// ── Task 运行时状态枚举 ─────────────────────────────────────────────────────
const TASK_STATUS = {
  PENDING: 'PENDING', // 未开始
  RUNNING: 'RUNNING', // 执行中
  DONE: 'DONE', // 完成（含 Gate PASS）
  FAILED: 'FAILED', // 失败（Gate FAIL 且重试耗尽 / block）
  SKIPPED: 'SKIPPED', // 跳过
}

// ── 工作流全局阶段枚举 ──────────────────────────────────────────────────────
const STAGE = {
  PENDING: 'PENDING', // 待启动
  RUNNING: 'RUNNING', // 运行中
  COMPLETED: 'COMPLETED', // 全部完成
  FAILED: 'FAILED', // 阻断失败
  PAUSED: 'PAUSED', // 暂停（后续迭代）
}

// ── 条件导出（Node 测试可用；宿主内联拼接时 module 未定义则跳过） ─────────

// ---- module: workflow-parser ----
// ============================================================================
// workflow-agent — 轻量 YAML 解析器 + 工作流文档结构化
// 文件：code/shared/workflow-parser.js
// 说明：无依赖纯逻辑片段（不包含 module.exports，供 Node 测试与宿主内联）。
//       实现的 YAML 子集：顶层 map、嵌套 map、block 列表（- item）、
//       内联列表（[a, b]）、标量（字符串/数字/布尔/null），引号剥离。
// ============================================================================

// ── 词法：行扫描 ────────────────────────────────────────────────────────────
function countIndent(line) {
  let n = 0
  while (n < line.length && (line[n] === ' ' || line[n] === '\t')) n++
  return n
}

function stripComment(line) {
  // 去除行尾注释（# 前有空白才视为注释，避免 url/说明内 #）
  const m = /(\s)#/.exec(line)
  return m ? line.slice(0, m.index) : line
}

function parseScalar(raw) {
  const s = String(raw).trim()
  if (s === '') return null
  if (s === 'null' || s === '~') return null
  if (s === 'true') return true
  if (s === 'false') return false
  // 数字
  if (/^-?\d+(\.\d+)?$/.test(s)) return Number(s)
  // 引号剥离
  if ((s[0] === '"' && s[s.length - 1] === '"') || (s[0] === "'" && s[s.length - 1] === "'")) {
    return s.slice(1, -1)
  }
  return s
}

// 内联列表 [a, b, c]
function parseInlineList(s) {
  const m = /\s*\[(.*)\]\s*$/.exec(s)
  if (!m) return null
  const inner = m[1]
  if (inner.trim() === '') return []
  return inner.split(',').map((part) => parseScalar(part))
}

// ── 语法：块解析 ────────────────────────────────────────────────────────────
// 解析从 start 开始、缩进 >= baseIndent 的行序列，返回 { value, next }
// value 可为普通对象（map）、数组（list）、或标量。
function parseBlock(lines, start, baseIndent) {
  const total = lines.length
  if (start >= total || countIndent(lines[start]) < baseIndent) {
    return { value: null, next: start }
  }
  const indent = countIndent(lines[start])

  // 列表块：- item （支持 - key: value 多行对象元素）
  if (/^\s*-\s+/.test(lines[start]) || /^\s*-$/.test(lines[start])) {
    const arr = []
    let i = start
    while (i < total) {
      const ln = lines[i]
      const ind = countIndent(ln)
      if (ind < indent || !/^\s*-/.test(ln)) break
      const rest = stripComment(ln.slice(ln.indexOf('-') + 1).trim())
      if (rest === '') {
        // 空 item：后续缩进行是嵌套块（map 或 list）
        const sub = parseBlock(lines, i + 1, indent + 1)
        arr.push(sub.value)
        i = sub.next
      } else if (rest.indexOf(':') !== -1) {
        // "- key: value"：多行对象元素的起始行
        const obj = {}
        const colon = rest.indexOf(':')
        const key = rest.slice(0, colon).trim()
        const val = stripComment(rest.slice(colon + 1).trim()).trim()
        if (val === '') {
          const sub = parseBlock(lines, i + 1, indent + 1)
          obj[key] = sub.value
          i = sub.next
        } else {
          const inline = parseInlineList(val)
          obj[key] = inline ? inline : parseScalar(val)
          i++
        }
        // 续行：缩进 > 列表缩进 的 map 键归属于当前元素
        const cont = parseBlock(lines, i, indent + 1)
        if (cont.value && typeof cont.value === 'object' && !Array.isArray(cont.value)) {
          Object.assign(obj, cont.value)
          i = cont.next
        }
        arr.push(obj)
      } else if (rest.indexOf('[') !== -1 && rest.indexOf(']') !== -1) {
        arr.push(parseInlineList(rest))
        i++
      } else {
        arr.push(parseScalar(rest))
        i++
      }
    }
    return { value: arr, next: i }
  }

  // map 块：key: value
  const obj = {}
  let i = start
  while (i < total) {
    const ln = lines[i]
    const ind = countIndent(ln)
    if (ind < indent || !/^\S/.test(ln.trim())) break
    const colon = ln.indexOf(':')
    if (colon === -1) {
      i++
      continue
    }
    const key = ln.slice(0, colon).trim()
    const rest = ln.slice(colon + 1).trim()
    const restClean = stripComment(rest).trim()
    if (restClean === '') {
      // value 在后续缩进行中
      const sub = parseBlock(lines, i + 1, indent + 1)
      obj[key] = sub.value
      i = sub.next
    } else {
      const inline = parseInlineList(restClean)
      if (inline) {
        obj[key] = inline
      } else {
        obj[key] = parseScalar(restClean)
      }
      i++
    }
  }
  return { value: obj, next: i }
}

function parseYaml(text) {
  const lines = String(text).split(/\r?\n/)
  const content = lines.filter((l) => l.trim() !== '' && !/^\s*#/.test(l))
  if (content.length === 0) return {}
  const r = parseBlock(content, 0, 0)
  return r.value || {}
}

// ── 工作流结构化与校验 ──────────────────────────────────────────────────────
// 输入：YAML 文本字符串；输出：结构化工作流对象（合法时）
// 结构：{ name, version, description, params, tasks:[...], errors:[...] }
function parseWorkflow(text) {
  const raw = parseYaml(text)
  const errors = []
  const warnings = []

  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return { name: null, version: null, description: null, params: {}, tasks: [], errors: ['工作流文件必须是一个 YAML 对象'] }
  }

  const name = raw.name != null ? String(raw.name) : null
  if (!name) errors.push('缺少必填字段: name')

  const version = raw.version != null ? String(raw.version) : null

  const params = {}
  if (raw.params && typeof raw.params === 'object' && !Array.isArray(raw.params)) {
    for (const k of Object.keys(raw.params)) {
      const p = raw.params[k]
      params[k] = {
        type: (p && p.type) || 'string',
        description: (p && p.description) || '',
        default: p && p.default !== undefined ? p.default : undefined,
      }
    }
  }

  const tasks = []
  if (!Array.isArray(raw.tasks) || raw.tasks.length === 0) {
    errors.push('缺少必填字段: tasks（至少 1 个 Task）')
  } else {
    const seenIds = new Set()
    raw.tasks.forEach((t, idx) => {
      if (!t || typeof t !== 'object') {
        errors.push('tasks[' + idx + '] 不是有效对象')
        return
      }
      const task = normalizeTask(t, idx, errors, warnings)
      if (task) {
        if (seenIds.has(task.id)) {
          errors.push('Task id 重复: ' + task.id)
        }
        seenIds.add(task.id)
        tasks.push(task)
      }
    })
    // depends-on 引用校验
    for (const t of tasks) {
      for (const dep of t.dependsOn) {
        if (!seenIds.has(dep)) {
          errors.push('Task "' + t.id + '" 的 depends-on 引用了不存在的 Task: ' + dep)
        }
      }
    }
  }

  return { name, version, description: raw.description || null, params, tasks, errors, warnings }
}

function normalizeTask(t, idx, errors) {
  const id = t.id != null ? String(t.id).trim() : ''
  if (!id) {
    errors.push('tasks[' + idx + '] 缺少必填字段: id')
    return null
  }
  const type = t.type || 'llm-task'

  // v1.1：inputs 为命名 map {key: 单路径 | 路径列表}，值保留原始形态传给宿主
  const inputsRaw = normalizeInputs(t.inputs)
  if (inputsRaw === null) {
    errors.push('Task "' + id + '" 的 inputs 必须是命名 map {key: 路径 | 路径列表}（v1.1 起不再支持列表形态）')
  }

  const base = {
    id,
    name: t.name != null ? String(t.name) : id,
    type,
    dependsOn: toArray(t['depends-on']),
    timeout: t.timeout != null ? Number(t.timeout) : 600,
    // 原始相对路径（保留给宿主解析绝对路径）
    processorRaw: t.processor != null ? String(t.processor) : null,
    inputsRaw: inputsRaw || {},
    outputsRaw: toArray(t.outputs),
  }

  // 质量门禁
  if (t['quality-gate'] != null) {
    const g = t['quality-gate']
    if (typeof g !== 'object' || Array.isArray(g)) {
      errors.push('Task "' + id + '" 的 quality-gate 必须是对象')
    } else {
      const onFailure = g['on-failure'] || 'block'
      if (['retry', 'block', 'skip'].indexOf(onFailure) === -1) {
        errors.push('Task "' + id + '" 的 quality-gate.on-failure 必须是 retry|block|skip，实际: ' + onFailure)
      }
      base.gateRaw = g.checker != null ? String(g.checker) : null
      base.gateOnFailure = onFailure
      base.gateMaxRetries = g['max-retries'] != null ? Number(g['max-retries']) : 0
    }
  }

  // 类型专属校验
  if (type === 'llm-task' || !type) {
    if (!base.processorRaw) errors.push('Task "' + id + '" 缺少必填字段: processor')
  } else if (type === 'loop') {
    if (!base.processorRaw) errors.push('Task "' + id + '" 缺少必填字段: processor')
    if (t['items-from'] == null) errors.push('Task "' + id + '" 缺少必填字段: items-from')
    if (t['item-var'] == null) errors.push('Task "' + id + '" 缺少必填字段: item-var')
    base.itemsFromRaw = t['items-from'] != null ? String(t['items-from']) : null
    base.itemVar = t['item-var'] != null ? String(t['item-var']) : 'item'
    // 循环错误处理策略
    const onError = t['on-error'] || 'break'
    if (['break', 'continue'].indexOf(onError) === -1) {
      errors.push('Task "' + id + '" 的 on-error 必须是 break|continue，实际: ' + onError)
    }
    base.onError = onError
  } else if (type === 'human-decision') {
    base.prompt = t.prompt != null ? String(t.prompt) : null
    if (!base.prompt) errors.push('Task "' + id + '" 缺少必填字段: prompt')
  } else if (type === 'external-agent') {
    base.agent = t.agent != null ? String(t.agent) : null
    if (!base.agent) errors.push('Task "' + id + '" 缺少必填字段: agent')
  } else {
    errors.push('Task "' + id + '" 的 type 不支持: ' + type)
  }

  return base
}

function toArray(v) {
  if (v == null) return []
  if (Array.isArray(v)) return v.map((x) => String(x))
  return [String(v)]
}

// v1.1：命名式 inputs。YAML 解出后为 {key: string | string[]}；
// 保留 map 形态与值的原生类型，仅确保 string[] 元素为字符串。
// 若输入是数组/标量（旧列表形态），视为无效并返回 null（字段用默认 {}）。
function normalizeInputs(v) {
  if (v == null) return {}
  if (typeof v !== 'object' || Array.isArray(v)) return null
  const out = {}
  for (const k of Object.keys(v)) {
    const val = v[k]
    if (Array.isArray(val)) {
      out[k] = val.map((x) => String(x))
    } else if (val != null) {
      out[k] = String(val)
    }
  }
  return out
}


// ---- module: engine ----
// ============================================================================
// workflow-agent — 工作流实例状态引擎
// 文件：code/plugins/workflow-host/engine.js
// 说明：纯内存状态管理（N 节点状态表、阶段、Gate 结果、重试计数、执行日志）。
//       宿主内联时，schema 常量（STAGE/TASK_STATUS）由前置拼接的
//       workflow-schema.js 提供；Node 独立测试时，下方兜底常量生效。
// ============================================================================

// 兜底常量：宿主内联时同作用域已有同名 const，let 声明不冲突。
let E_STAGE = typeof STAGE !== 'undefined' ? STAGE : {
  PENDING: 'PENDING', RUNNING: 'RUNNING', COMPLETED: 'COMPLETED', FAILED: 'FAILED', PAUSED: 'PAUSED',
}
let E_TASK_STATUS = typeof TASK_STATUS !== 'undefined' ? TASK_STATUS : {
  PENDING: 'PENDING', RUNNING: 'RUNNING', DONE: 'DONE', FAILED: 'FAILED', SKIPPED: 'SKIPPED',
}

// Task 运行时快照（供 UI 消费的最小字段集）
function taskSnapshot(t) {
  return {
    id: t.id,
    name: t.name,
    type: t.type,
    status: t.status,
    processor: t.processor || null,       // 处理器技能绝对路径（Client 读取 skill 文本用）
    gateChecker: (t.gate && t.gate.checker) || null, // 门禁技能绝对路径
    gateResult: t.gateResult || null,
    gateOnFailure: t.gateOnFailure || null,
    retries: t.retries || 0,
    _loopGroup: t._loopGroup || null,
    _loopItem: t._loopItem || null,
    _loopIndex: t._loopIndex ?? 0,
    _loopGroupName: t._loopGroupName || null,
    _onError: t._onError || null,
  }
}

// 全局快照（供 RPC / Tool 返回；指纹用于 Client 防抖）
function createWorkflowEngine() {
  const state = {
    workflow: null, // 工作流名称
    version: null,
    description: null,
    params: {},
    active: false, // 是否有进行中的实例
    stage: E_STAGE.PENDING,
    tasks: [], // Task 运行时状态数组
    gateResult: null, // 最近 Gate 结果（PASS/FAIL）
    retries: 0, // 最近任务的重试计数
    error: null,
    updatedAt: 0,
    logs: [], // 结构化执行日志 [{ts, action, detail}]
    persist: null, // 最近一次持久化结果
  }

  function fingerprint() {
    const t = state.tasks.map((x) => x.id + ':' + x.status).join(',')
    return [state.stage, state.gateResult || '', state.retries, state.error || '', t].join('|')
  }

  function snapshot() {
    return {
      workflow: state.workflow,
      version: state.version,
      description: state.description,
      active: state.active,
      stage: state.stage,
      tasks: state.tasks.map(taskSnapshot),
      gateResult: state.gateResult,
      retries: state.retries,
      error: state.error,
      updatedAt: state.updatedAt,
      logs: state.logs.slice(-200), // 最多保留最近 200 条
      persist: state.persist,
      fingerprint: fingerprint(),
    }
  }

  // 启动新工作流：清空旧状态，按解析结果初始化 N 个 Task
  function begin(parsed) {
    state.workflow = parsed.name
    state.version = parsed.version
    state.description = parsed.description
    state.params = parsed.params || {}
    state.active = true
    state.stage = E_STAGE.PENDING
    state.gateResult = null
    state.retries = 0
    state.error = null
    state.logs = [] // Iter-6：重新 begin 时清除历史日志，避免跨实例残留
    state.tasks = parsed.tasks.map((t) => ({
      id: t.id,
      name: t.name,
      type: t.type,
      status: E_TASK_STATUS.PENDING,
      processor: t.processor || null, // 绝对路径（由 tools 层解析后写入）
      outputs: t.outputs || [],
      gate: t.gate || null, // {checker, onFailure, maxRetries}
      gateResult: null,
      retries: 0,
      _loopGroup: t._loopGroup || null,
      _loopItem: t._loopItem || null,
      _loopIndex: t._loopIndex ?? 0,
      _loopGroupName: t._loopGroupName || null,
      _onError: t._onError || null,
    }))
    state.updatedAt = Date.now()
    log('BEGIN', '工作流 "' + state.workflow + '" 已初始化，tasks=' + state.tasks.length)
  }

  // 更新单个 Task 状态
  function updateTask(taskId, patch) {
    const t = state.tasks.find((x) => x.id === taskId)
    if (!t) return false
    if (patch.status !== undefined) t.status = patch.status
    if (patch.gateResult !== undefined) t.gateResult = patch.gateResult
    if (patch.retries !== undefined) t.retries = patch.retries
    if (patch.error !== undefined) t.error = patch.error
    state.updatedAt = Date.now()
    log('TASK', taskId + ' -> ' + t.status)
    // Iter-6：任务 FAILED 后按 _onError 处理循环中断
    //   break    → 同组后续 PENDING 迭代标记 SKIPPED（中断）
    //   continue → 不中断，后续迭代继续执行
    if (t.status === E_TASK_STATUS.FAILED && t._onError === 'break') {
      processBreak(taskId)
    }
    return true
  }

  // Iter-6：返回下一个可运行任务（跳过 SKIPPED 与非 PENDING 任务）
  // 串行架构下由编排 Agent 调用 workflow_status 后自行推导；本函数供
  // 未来并发引擎（Iter-7）复用，SKIPPED 任务天然不满足 status===PENDING。
  function getNextRunnableTask() {
    return state.tasks.find((t) => t.status === E_TASK_STATUS.PENDING) || null
  }

  function setStage(s) {
    state.stage = s
    state.updatedAt = Date.now()
    if (s === E_STAGE.COMPLETED || s === E_STAGE.FAILED) state.active = false
    log('STAGE', s)
  }

  function setGateResult(r) {
    state.gateResult = r
    state.updatedAt = Date.now()
    log('GATE', 'result=' + r)
  }

  function setRetries(n) {
    state.retries = n
    state.updatedAt = Date.now()
  }

  function setError(msg) {
    state.error = msg || null
    state.updatedAt = Date.now()
    if (msg) log('ERROR', msg)
  }

  function setPersist(r) {
    state.persist = r
  }

  // 当 task FAILED 且 _onError === 'break' 时，将同 _loopGroup 的 PENDING 任务标记为 SKIPPED
  function processBreak(taskId) {
    const failed = state.tasks.find((x) => x.id === taskId)
    if (!failed || !failed._loopGroup || failed._onError !== 'break') return false
    let skipped = 0
    state.tasks.forEach((t) => {
      if (t._loopGroup === failed._loopGroup && t.status === E_TASK_STATUS.PENDING && t.id !== taskId) {
        t.status = E_TASK_STATUS.SKIPPED
        t.error = '循环中断：前序迭代 "' + failed.id + '" 失败'
        skipped++
      }
    })
    if (skipped > 0) log('BREAK', '循环 "' + failed._loopGroup + '" 中断，跳过 ' + skipped + ' 个任务')
    return skipped > 0
  }

  function log(action, detail) {
    state.logs.push({ ts: Date.now(), action, detail })
    if (state.logs.length > 500) state.logs.splice(0, state.logs.length - 500)
  }

  function clear() {
    state.workflow = null
    state.version = null
    state.description = null
    state.params = {}
    state.active = false
    state.stage = E_STAGE.PENDING
    state.tasks = []
    state.gateResult = null
    state.retries = 0
    state.error = null
    state.logs = []
    state.updatedAt = Date.now()
  }

  // 从持久化 payload 恢复实例状态（storage.load 调用）
  function hydrate(j) {
    state.workflow = j.workflow
    state.version = j.version
    state.description = j.description
    state.params = j.params || {}
    state.active = !!j.active
    state.stage = j.stage || E_STAGE.PENDING
    state.gateResult = j.gateResult || null
    state.retries = j.retries || 0
    state.error = j.error || null
    state.updatedAt = Date.now()
    state.logs = Array.isArray(j.logs) ? j.logs.slice(-200) : []
    state.tasks = Array.isArray(j.tasks) ? j.tasks.map((t, i) => ({
      id: t.id,
      name: t.name,
      type: t.type,
      status: t.status || E_TASK_STATUS.PENDING,
      processor: t.processor || null,
      outputs: Array.isArray(t.outputs) ? t.outputs : [],
      gate: t.gate || null,
      gateResult: t.gateResult || null,
      retries: t.retries || 0,
      // Iter-6：恢复循环元数据（processBreak 与 Client DAG 分组依赖）
      _loopGroup: t._loopGroup || null,
      _loopItem: t._loopItem || null,
      _loopIndex: t._loopIndex ?? 0,
      _loopGroupName: t._loopGroupName || null,
      _onError: t._onError || null,
    })) : []
    state.updatedAt = Date.now()
  }

  return {
    begin,
    clear,
    hydrate,
    updateTask,
    processBreak,
    getNextRunnableTask,
    setStage,
    setGateResult,
    setRetries,
    setError,
    setPersist,
    snapshot,
  }
}


// ---- module: storage ----
// ============================================================================
// workflow-agent — 状态持久化
// 文件：code/plugins/workflow-host/storage.js
// 说明：工作流状态落盘/恢复。
//       修正记录（Iter-1 验收发现）：宿主插件没有 session 上下文，
//       sandboxPolicy.workspaceRoot 在宿主侧解析为「部署根」（DSH 安装目录），
//       直接使用会把状态写入安装目录。因此落盘位置不再依赖该 fallback，
//       改由 workflow_begin 调用方显式指定：
//         - setWorkspaceRoot(root)：状态默认写到 <root>/.workflow-agent/state.json
//         - setStatePath(path)    ：完全自定义状态文件路径
//       两者都未设置时 save() 返回错误、load() 返回 false（不抛异常、不写盘）。
// 依赖：ctx（fs）、engine（snapshot/setPersist/hydrate）。
// ============================================================================

function createWorkflowStorage(ctx, engine) {
  const sandboxPolicy = ctx.get('sandboxPolicy')

  let workspaceRoot = sandboxPolicy ? (sandboxPolicy.workspaceRoot || '') : ''
  let explicitStatePath = null
  let statePath = null

  // 由调用方（workflow_begin）在运行时设置，替代宿主 fallback root
  function setWorkspaceRoot(root) {
    workspaceRoot = (root || '').replace(/\\/g, '/').replace(/\/+$/, '')
    statePath = null // 下次访问时重算
  }

  function setStatePath(p) {
    explicitStatePath = p ? String(p).replace(/\\/g, '/') : null
    statePath = null // 下次访问时重算
  }

  // 延迟计算状态文件绝对路径（首次读写时解析）
  async function ensurePath() {
    if (statePath) return statePath
    const fs = ctx.get('fs')
    if (!fs) return null
    if (explicitStatePath) {
      statePath = await fs.resolve(explicitStatePath)
      return statePath
    }
    if (!workspaceRoot) return null
    const dir = (workspaceRoot + '/.workflow-agent').replace(/\/+/g, '/')
    statePath = await fs.resolve(dir + '/state.json')
    return statePath
  }

  // 显式沙箱写策略：写策略根来自调用方指定的 workspaceRoot 或状态文件父目录
  function writePolicy() {
    let root = workspaceRoot
    if (!root && explicitStatePath) {
      const idx = explicitStatePath.lastIndexOf('/')
      root = idx > 0 ? explicitStatePath.slice(0, idx) : explicitStatePath
    }
    return {
      mode: 'workspace-write',
      workspaceRoot: root || '',
    }
  }

  async function save() {
    const fs = ctx.get('fs')
    if (!fs) return 'err: no fs'
    try {
      const p = await ensurePath()
      if (!p) return 'err: no workspaceRoot/statePath（请由 workflow_begin 指定）'
      const snap = engine.snapshot()
      const payload = {
        workflow: snap.workflow,
        version: snap.version,
        description: snap.description,
        params: snap.params,
        active: snap.active,
        stage: snap.stage,
        tasks: snap.tasks,
        gateResult: snap.gateResult,
        retries: snap.retries,
        error: snap.error,
        updatedAt: snap.updatedAt,
        logs: snap.logs,
      }
      await fs.writeText(p, JSON.stringify(payload, null, 2), undefined, undefined, writePolicy())
      const r = 'ok'
      engine.setPersist(r)
      return r
    } catch (e) {
      const r = 'err: ' + ((e && e.message) || String(e))
      engine.setPersist(r)
      return r
    }
  }

  // 恢复：仅当存在有效状态文件时执行
  async function load() {
    const fs = ctx.get('fs')
    if (!fs) return false
    try {
      const p = await ensurePath()
      if (!p) return false
      const text = await fs.readText(p)
      const j = JSON.parse(text)
      if (!j || !j.workflow) return false
      engine.hydrate(j)
      return true
    } catch (e) {
      return false // 无之前状态
    }
  }

  return { save, load, setWorkspaceRoot, setStatePath }
}


// ---- module: tools-preset ----
// ============================================================================
// workflow-agent — Host 模型工具（preset 本地插件版）
// 文件：code/plugins/workflow-host-preset/tools-preset.js
// 说明：与 plugins/workflow-host/tools.js 相同的两个工具定义，但注册方式改为
//       ctx.tools.register（preset 本地 .mjs 插件形态，custom-bash.mjs /
//       dsh-tool-workflow 先例），而非动态插件的 harness.defineTool。
//       另外从 exec.agent.session.header.cwd 取会话工作区作为默认落盘根，
//       解决宿主插件无会话上下文时写错目录的问题。
// 依赖：ctx（fs/exec）、engine、storage、schema/parser 常量（同作用域内联）。
// ============================================================================

// ── 相对路径解析（复用 PoC 逐级上探逻辑）───────────────────────────────────
function parentDir(p) {
  const norm = p.replace(/\\/g, '/')
  const idx = norm.lastIndexOf('/')
  if (idx <= 0) return null
  return norm.slice(0, idx)
}

// 从 YAML 所在目录逐级向上探测，取第一个真实存在的拼接；兜底用 YAML 目录
async function resolveRel(fs, base, rel) {
  let d = base
  while (d) {
    const cand = d + '/' + rel.replace(/\\/g, '/')
    try {
      const st = await fs.stat(await fs.resolve(cand))
      if (st) return cand
    } catch (e) { /* keep climbing */ }
    d = parentDir(d)
  }
  return base + '/' + rel.replace(/\\/g, '/')
}

// ── ${param} 注入 ───────────────────────────────────────────────────────────
// PARAM_PATTERN 默认由同作用域 schema 模块提供；独立加载（Node 直测）时兜底
let E_PARAM_PATTERN = typeof PARAM_PATTERN !== 'undefined' ? PARAM_PATTERN : /\$\{(\w+)\}/g
function injectParams(value, params) {
  if (typeof value !== 'string') return value
  return value.replace(E_PARAM_PATTERN, (whole, key) => {
    if (params && params[key] !== undefined) return String(params[key])
    return whole // 未提供则保留原样，由调用方提示
  })
}

function injectArray(list, params) {
  return (list || []).map((x) => injectParams(x, params))
}

// v1.1：命名式 inputs 注入。值为 string → 注入后返回 string；
// 值为 string[] → 逐项注入后返回 string[]。
function injectInputsMap(map, params) {
  const out = {}
  for (const k of Object.keys(map || {})) {
    const v = map[k]
    out[k] = Array.isArray(v) ? v.map((x) => injectParams(x, params)) : injectParams(v, params)
  }
  return out
}

// 工作流文件加载：优先 workflowPath（读文件），兜底 workflowText（直接用）
async function loadWorkflowSource(fs, args) {
  if (args.workflowPath) {
    const p = String(args.workflowPath)
    const text = await fs.readText(await fs.resolve(p))
    return { text, base: p.replace(/[\\/][^\\/]*$/, '') }
  }
  if (args.workflowText) {
    return { text: String(args.workflowText), base: undefined }
  }
  return null
}

// ── 循环展开：将 loop Task 展开为 N 个串行迭代实例 ────────────────────────
// items 参数：从 items-from 文件解析出的非空非注释行数组
// itemVar：迭代变量名（如 "module"），在 inputs/outputs 中解决 ${itemVar}
// params：已注入的工作流级参数
// loopTask：原始 loop Task 对象（含 inputsRaw/outputsRaw/processor/gate/dependsOn）
// prevDeps：【内部使用】前一个迭代的 id，用于构建串行依赖链
async function expandLoopTasks(fs, loopTask, items, itemVar, params) {
  const expanded = []
  const loopDeps = loopTask.dependsOn || []
  let prevId = null

  for (let i = 0; i < items.length; i++) {
    const item = String(items[i]).trim()
    if (!item) continue

    // 构建迭代参数（工作流 params + 当前 item）
    const iterParams = { ...params }
    iterParams[itemVar] = item

    // 安全 ID：loopTaskId/sanitized-item
    const sanitized = item.replace(/[^a-zA-Z0-9_\-]/g, '-').replace(/^-+|-+$/g, '') || ('iter-' + i)
    const iterId = loopTask.id + '/' + sanitized

    // inputs/outputs 重新注入（含 item 变量）
    const iterInputs = injectInputsMap(loopTask.inputsRaw || {}, iterParams)
    const iterOutputs = injectArray(loopTask.outputsRaw || [], iterParams)

    // processor 路径重新注入（含 item 变量——虽然通常不变）
    const iterProcessor = injectParams(loopTask.processor || '', iterParams)

    // gate 复制（同一 checker，独立执行）
    const iterGate = loopTask.gate ? {
      checker: loopTask.gate.checker,
      onFailure: loopTask.gate.onFailure,
      maxRetries: loopTask.gate.maxRetries,
    } : null

    expanded.push({
      id: iterId,
      name: (loopTask.name || loopTask.id) + ' - ' + item,
      type: 'llm-task',
      dependsOn: prevId ? [prevId] : loopDeps,
      timeout: loopTask.timeout || 600,
      processor: iterProcessor,
      inputs: iterInputs,
      outputs: iterOutputs,
      gate: iterGate,
      // 循环错误处理策略
      _onError: loopTask.onError || 'break',
      // 循环组元数据（供 Client DAG 分组渲染）
      _loopGroup: loopTask.id,
      _loopGroupName: loopTask.name || loopTask.id,
      _loopItem: item,
      _loopIndex: i,
    })
    prevId = iterId
  }

  return expanded
}

// 从工具执行上下文取会话工作区（preset 挂载后 exec.agent 可用）
function sessionCwd(exec) {
  try {
    const cwd = exec && exec.agent && exec.agent.session && exec.agent.session.header && exec.agent.session.header.cwd
    return typeof cwd === 'string' && cwd.length > 0 ? cwd : undefined
  } catch (e) {
    return undefined
  }
}

// 注册工具：preset 本地插件形态（ctx.tools.register），不依赖 harness
function registerWorkflowToolsPreset(ctx, engine, storage) {
  const fs = ctx.get('fs')

  // ── workflow_begin ────────────────────────────────────────────────────────
  const beginTool = {
    name: 'workflow_begin',
    description: '解析并启动一个工作流定义（YAML）。参数 workflowPath 为本机绝对路径；或传 workflowText 直接给 YAML 文本。可选 params 对象注入工作流级 ${param} 模板变量。可选 workspaceRoot（推荐：传会话工作区根，如 C:/Users/<user>/dsh_workspace）决定状态文件默认落盘位置 <root>/.workflow-agent/state.json；或直接传 statePath 完全指定状态文件路径。未传 workspaceRoot 时自动使用当前会话工作区。成功返回解析出的任务列表（含处理技能绝对路径、门禁配置）与初始 PENDING 状态；定义不合法时返回 errors 列表。',
    parameters: {
      type: 'object',
      additionalProperties: true,
      properties: {
        workflowPath: { type: 'string', description: '工作流 YAML 的绝对路径' },
        workflowText: { type: 'string', description: '工作流 YAML 文本（与 workflowPath 二选一）' },
        workspaceRoot: { type: 'string', description: '状态落盘根目录（默认取会话工作区）' },
        statePath: { type: 'string', description: '完全自定义的状态文件绝对路径（优先级高于 workspaceRoot）' },
        params: {
          type: 'object',
          additionalProperties: true,
          description: '工作流参数，替换字段中的 ${param_name}',
        },
      },
    },
    output: {
      schema: { type: 'object', additionalProperties: true },
      render(_a, v) {
        return [{ type: 'text', text: JSON.stringify(v, null, 2) }]
      },
    },
    async execute(args, exec) {
      try {
        if (!fs) throw new Error('fs service unavailable')
        if (args && args.workspaceRoot && storage) storage.setWorkspaceRoot(String(args.workspaceRoot))
        if (args && args.statePath && storage) storage.setStatePath(String(args.statePath))
        // 未显式指定 workspaceRoot 时，从会话上下文取工作区
        if ((!args || !args.workspaceRoot) && storage) {
          const cwd = sessionCwd(exec)
          if (cwd) storage.setWorkspaceRoot(cwd)
        }
        const src = await loadWorkflowSource(fs, args)
        if (!src) throw new Error('需要 workflowPath 或 workflowText 参数')
        const parsed = parseWorkflow(src.text)
        const params = (args && args.params) || {}
        if (parsed.errors && parsed.errors.length > 0) {
          engine.setError('workflow 定义不合法: ' + parsed.errors.join('; '))
          await storage.save()
          const s = engine.snapshot()
          s.workflowBeginErrors = parsed.errors
          return s
        }
        // 注入 params + 解析相对路径为绝对路径
        const tasks = await Promise.all(parsed.tasks.map(async (t) => {
          const out = { ...t }
          out.inputs = injectInputsMap(t.inputsRaw, params)
          out.outputs = injectArray(t.outputsRaw, params)
          if (t.processorRaw) {
            const procRel = injectParams(t.processorRaw, params)
            out.processor = src.base ? await resolveRel(fs, src.base, procRel) : procRel
          }
          if (t.gateRaw) {
            const gateRel = injectParams(t.gateRaw, params)
            out.gate = {
              checker: src.base ? await resolveRel(fs, src.base, gateRel) : gateRel,
              onFailure: t.gateOnFailure,
              maxRetries: t.gateMaxRetries,
            }
          }
          if (t.itemsFromRaw) {
            const itemsRel = injectParams(t.itemsFromRaw, params)
            out.itemsFrom = src.base ? await resolveRel(fs, src.base, itemsRel) : itemsRel
            out.itemsFromRaw = t.itemsFromRaw // 保留原始值供循环展开二次注入
            out.itemVar = t.itemVar
          }
          return out
        }))
        parsed.tasks = tasks

        // ── 循环展开：将 loop Task 替换为 N 个串行迭代实例 ──
        const finalTasks = []
        for (const t of tasks) {
          if (t.type === 'loop' && t.itemsFrom && t.itemVar) {
            // 读取 items-from 文件
            const text = await fs.readText(await fs.resolve(t.itemsFrom))
            const items = text.split(/\r?\n/).map(l => l.trim()).filter(l => l && !l.startsWith('#'))
            if (items.length === 0) {
              engine.setError('循环 Task "' + t.id + '" 的 items-from 文件为空: ' + t.itemsFrom)
              await storage.save()
              return engine.snapshot()
            }
            const iterations = await expandLoopTasks(fs, t, items, t.itemVar, params)
            finalTasks.push(...iterations)
          } else {
            finalTasks.push(t)
          }
        }
        parsed.tasks = finalTasks
        engine.begin(parsed)
        engine.setError(null)
        const r = await storage.save()
        engine.setPersist(r)
        return engine.snapshot()
      } catch (error) {
        engine.setError(error.message)
        await storage.save()
        return engine.snapshot()
      }
    },
  }
  ctx.tools.register(beginTool)

  // ── workflow_status ───────────────────────────────────────────────────────
  const statusTool = {
    name: 'workflow_status',
    description: '按编排进展更新工作流状态并同步持久化与 UI：stage（PENDING|RUNNING|COMPLETED|FAILED）、gateResult（PASS|FAIL）、task/tasktatus 更新单个任务（PENDING|RUNNING|DONE|FAILED|SKIPPED）、retries 重试计数、error 错误信息。每次调用返回最新快照。',
    parameters: {
      type: 'object',
      additionalProperties: true,
      properties: {
        stage: { type: 'string', description: '全局阶段' },
        gateResult: { type: 'string', description: '门禁结果 PASS 或 FAIL' },
        task: { type: 'string', description: '要更新的任务 id' },
        taskStatus: { type: 'string', description: '该任务状态' },
        retries: { type: 'number', description: '失败重试计数' },
        error: { type: 'string', description: '错误信息' },
      },
    },
    output: {
      schema: { type: 'object', additionalProperties: true },
      render(_a, v) {
        return [{ type: 'text', text: JSON.stringify(v, null, 2) }]
      },
    },
    async execute(args, exec) {
      try {
        if (!args) args = {}
        if (args.stage) engine.setStage(String(args.stage))
        if (args.gateResult) engine.setGateResult(String(args.gateResult))
        if (typeof args.retries === 'number') engine.setRetries(args.retries)
        if (args.error !== undefined) engine.setError(args.error ? String(args.error) : null)
        if (args.task && args.taskStatus) {
          engine.updateTask(String(args.task), { status: String(args.taskStatus) })
        }
        const r = await storage.save()
        engine.setPersist(r)
        return engine.snapshot()
      } catch (error) {
        engine.setError(error.message)
        return engine.snapshot()
      }
    },
  }
  ctx.tools.register(statusTool)
}

// ---- module: webserver-routes ----
// ============================================================================
// workflow-agent — Host webServer HTTP 路由（Iter-5，替代 harness RPC）
// 文件：code/agent-presets/workflow-orchestrator/workflow-host.mjs 末尾
// 说明：注册 /wf/* 前缀路由，供 Client 面板轮询状态/读取技能/验证工作区。
//       参考先例：@linxin666/dsh-tool-describe-image（npm 包 + webServer + fetch）。
// 依赖：ctx.get('webServer')、ctx.get('fs')。webServer 不存在时静默跳过
//       （路由注册是可选能力，不影响工具注册）。
// ============================================================================

// ── loopback 信任围栏（仿 describe-image 的 shared/host/loopback）──────────
// IPv4 127/8、::1、IPv4-mapped ::ffff:127/8，加上浏览器 same-origin 标记
function isLoopbackAddress(address) {
  if (address === undefined || address === null) return false
  const normalized = String(address).toLowerCase()
  if (normalized === '::1') return true
  if (normalized.startsWith('::ffff:')) {
    return isIPv4Loopback(normalized.slice('::ffff:'.length))
  }
  return isIPv4Loopback(normalized)
}

function isIPv4Loopback(v4) {
  const parts = v4.split('.')
  return parts.length === 4
    && parts[0] === '127'
    && parts.every(part => /^\d{1,3}$/.test(part) && Number(part) <= 255)
}

function isLoopbackHostname(hostname) {
  if (hostname === 'localhost' || hostname === '[::1]') return true
  return isIPv4Loopback(hostname)
}

function isLoopbackRequest(request) {
  if (!isLoopbackAddress(request.socket && request.socket.remoteAddress)) return false
  const host = request.headers && request.headers.host
  if (typeof host !== 'string') return false
  let hostUrl
  try {
    hostUrl = new URL('http://' + host)
  } catch (e) {
    return false
  }
  if (!isLoopbackHostname(hostUrl.hostname)) return false
  if (request.headers['sec-fetch-site'] === 'cross-site') return false
  const origin = request.headers.origin
  if (origin === undefined) return true
  try {
    return new URL(origin).host === hostUrl.host
  } catch (e) {
    return false
  }
}

// ── JSON 响应辅助 ──────────────────────────────────────────────────────────
function writeJson(res, status, body) {
  const payload = JSON.stringify(body)
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' })
  res.end(payload)
}

// ── 从指定工作区读取 state.json（与 workflow-rpc.mjs 的 loadState 同构）────
async function loadStateFromFile(fs, workspaceRoot) {
  if (!fs) return { state: null, error: 'fs service unavailable' }
  try {
    const root = (workspaceRoot || '').replace(/\\/g, '/').replace(/\/+$/, '')
    if (!root) return { state: null, error: 'workspaceRoot not specified' }
    const statePath = root + '/.workflow-agent/state.json'
    const resolved = await fs.resolve(statePath)
    const text = await fs.readText(resolved)
    const state = JSON.parse(text)
    return { state, error: null }
  } catch (e) {
    return { state: null, error: e && e.message ? e.message : String(e) }
  }
}

// ── 注册 /wf/* 路由 ────────────────────────────────────────────────────────
// GET /wf/status?workspaceRoot=...   → 工作流状态快照 {state, error}
// GET /wf/skill?path=...             → 技能文件全文 {text, error}
// GET /wf/config?workspaceRoot=...   → 验证工作区 {valid, workspaceRoot, error}
function registerWebRoutes(ctx) {
  const webserver = ctx.get('webServer')
  if (!webserver) return // 可选能力：webServer 不存在时静默跳过
  const fs = ctx.get('fs')

  webserver.register({
    kind: 'prefix',
    path: '/wf',
    handler: async (req, res) => {
      // loopback 围栏优先：LAN/跨站调用一律 403
      if (!isLoopbackRequest(req)) {
        writeJson(res, 403, { error: 'forbidden: loopback-only' })
        return
      }
      let pathname = '/'
      let search = ''
      try {
        const url = new URL(req.url || '/', 'http://x')
        pathname = url.pathname
        search = url.search
      } catch (e) {
        writeJson(res, 400, { error: 'malformed url' })
        return
      }
      const query = new URLSearchParams(search)

      if (pathname === '/wf/status') {
        const result = await loadStateFromFile(fs, query.get('workspaceRoot') || '')
        writeJson(res, 200, result)
        return
      }

      if (pathname === '/wf/skill') {
        if (!fs) {
          writeJson(res, 200, { text: null, error: 'fs service unavailable' })
          return
        }
        try {
          const path = query.get('path') || ''
          if (!path) {
            writeJson(res, 200, { text: null, error: 'no file path provided' })
            return
          }
          const resolved = await fs.resolve(path)
          const text = await fs.readText(resolved)
          writeJson(res, 200, { text, error: null })
        } catch (e) {
          writeJson(res, 200, { text: null, error: e && e.message ? e.message : String(e) })
        }
        return
      }

      if (pathname === '/wf/config') {
        const root = (query.get('workspaceRoot') || '').replace(/\\/g, '/').replace(/\/+$/, '')
        if (root && fs) {
          try {
            await fs.resolve(root + '/.workflow-agent/state.json')
            writeJson(res, 200, { valid: true, workspaceRoot: root })
          } catch (e) {
            writeJson(res, 200, { valid: false, workspaceRoot: root, error: 'state.json not found at ' + root + '/.workflow-agent/state.json' })
          }
        } else {
          writeJson(res, 200, { valid: false, workspaceRoot: root, error: 'workspaceRoot not provided' })
        }
        return
      }

      writeJson(res, 404, { error: 'not found: ' + pathname })
    },
  })
}

// 供 Node 独立验证（与宿主体内同构）：{ registerWorkflowToolsPreset, resolveRel, injectParams, injectArray, injectInputsMap, sessionCwd, registerWebRoutes, loadStateFromFile }
