#!/usr/bin/env node
/**
 * Workflow Agent Client UI Monitor - 构建脚本
 * 
 * 将 src/client.js 转换为 DSH 格式的 lib/client.js
 * 
 * 用法: node build.js
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

console.log('Building @workflow-agent/client-ui-monitor...')

// 读取源代码
const srcPath = join(__dirname, 'src', 'client.js')
let srcCode = readFileSync(srcPath, 'utf-8')

// 移除 export 关键字，转换为内部函数
srcCode = srcCode.replace(/^export function register\(ctx\) \{/m, 'function register(ctx) {')

// 生成 DSH 模块格式
const clientCode = `// @workflow-agent/client-ui-monitor - Client UI Plugin
// Auto-generated by build.js - DO NOT EDIT
window.__ModuleLoader__.load({
  id: "@workflow-agent/client-ui-monitor",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    
    const React = require("react");
    
    // Iter-5：不再 require host —— host 是动态插件闭包注入符号，
    // npm 包从 @deepseek-ai/dsh-client-runtime 无法获得。
    // Client 改用 fetch() 调用 Host 侧 webServer HTTP 路由（/wf/*）。
    
    // Plugin code starts here
    ${srcCode}
    
    // Plugin code ends here
    
    function apply(ctx) {
      register(ctx);
    }
    
    const inject = ['slots'];
    
    exports.apply = apply;
    exports.inject = inject;
    
    return module.exports;
  }
});
`

// 写入 lib/client.js
const libPath = join(__dirname, 'lib', 'client.js')
writeFileSync(libPath, clientCode, 'utf-8')

console.log('✓ Built lib/client.js')
console.log(`  Source: ${srcCode.length} chars`)
console.log(`  Output: ${clientCode.length} chars`)
console.log('\nBuild complete!')
