// @workflow-agent/client-ui-monitor - Client UI Plugin
// Auto-generated by build.js - DO NOT EDIT
window.__ModuleLoader__.load({
  id: "@workflow-agent/client-ui-monitor",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    
    const React = require("react");
    
    // Iter-5：不再 require host —— host 是动态插件闭包注入符号，
    // npm 包从 @deepseek-ai/dsh-client-runtime 无法获得。
    // Client 改用 fetch() 调用 Host 侧 webServer HTTP 路由（/wf/*）。
    
    // Plugin code starts here
    // Workflow Agent DAG 监控面板 - npm 包版本
// 从动态插件 wff-9/pkg-14 迁移而来

function register(ctx) {
  const slots = ctx.get('slots')
  if (!slots) return

  // ── 模块级数据层（防止 remount 闪烁）────────────────────────────
  let latest = null, lastError = null
  const listeners = new Set()
  let pollingActive = false, wfRoot = '', wfLoaded = false
  // Iter-12：cwd 跟随 + 实例列表（activeRoot=当前轮询锚点；wfInstanceId=面板选择）
  let activeRoot = null, wfInstances = [], wfInstanceId = ''
  // Iter-19：当前会话派生状态（/wf/list 返回；create 按钮 gating 用）
  let wfSessionState = null
  // Iter-23(A3)：Case I 停止无效提示（/wf/list stopHint；状态触发：RUNNING+主 idle+子会话在跑）
  let wfStopHint = null
  // Iter-20：当前会话 id（/wf/list 查询用，路由据此返回轻量 sessionState）
  let wfSessionId = ''
  // Iter-13：列表加载器引用（面板创建成功后即时刷新）
  let wfListLoader = null
  // Iter-20(S5)：当前会话是否为 workflow-orchestrator 预设（预设门控；false 时短路轮询）
  let wfSessionActive = false
  // Iter-21(R3)：会话切换检测（activeRoot 相同也需重置并重拉，消除状态残留）
  let wfLastSessionId = ''
  // Iter-21：控制中间态——Start/Stop/Resume 点击后进入 Starting/Stopping/Resuming（按钮禁用显示对应文案），
  // 直到 agent 真正把实例切到目标 stage 才清掉、DAG 才切换。防 LLM 等待期重复点击。
  let wfPendingCmd = null, wfPendingAt = 0
  // Iter-21(R3)：稳定组件类型——session 更新（subagent 创建等）会频繁触发 factory 重渲染，
  // 若 WorkflowView 每次重定义会 remount（闪烁 + 局部状态丢失）。用模块级缓存一次。
  let WfComponent = null

  function fingerprint(state) {
    if (!state || !state.tasks) return ''
    const t = state.tasks.map(x => x.id + ':' + x.status).join(',')
    return [state.stage || '', state.gateResult || '', state.retries || 0, t].join('|')
  }

  function publish(state) {
    // /wf/status 返回包装 {state,error,instanceId}；fingerprint 应从嵌套 state 取 tasks/stage（否则去重恒失效 → 每 2s 无谓重渲染）
    const inner = state && state.state ? state.state : state
    const fp = inner ? fingerprint(inner) : ''
    if (fp && latest && latest.__fp === fp) return
    if (state) state.__fp = fp
    latest = state; lastError = state ? null : 'disconnected'
    listeners.forEach(fn => { try { fn() } catch(e) {} })
  }

  // ── 实例列表轮询 ─────────────────────────────────────────────
  let listPollingTimer = null
  function startListPolling() {
    if (!activeRoot || !wfSessionActive) return
    // 清理旧的轮询
    if (listPollingTimer) {
      clearInterval(listPollingTimer)
    }
    
    const loadList = async () => {
      if (!activeRoot || !wfSessionActive) return
      try {
        const resp = await fetch('/wf/list?workspaceRoot=' + encodeURIComponent(activeRoot) + (wfSessionId ? '&sessionId=' + encodeURIComponent(wfSessionId) : ''))
        const r = await resp.json()
        wfInstances = r && Array.isArray(r.instances) ? r.instances : []
        wfSessionState = r && r.sessionState ? r.sessionState : null
        wfStopHint = r && r.stopHint && r.stopHint.active ? r.stopHint : null // Iter-23(A3)
        listeners.forEach(fn => { try { fn() } catch (e2) {} })
      } catch (e) {
        // 静默失败，下次轮询重试
      }
    }
    
    // 立即加载一次
    loadList()
    // 每 10 秒轮询
    listPollingTimer = setInterval(loadList, 10000)
  }

  // ── 轮询逻辑 ───────────────────────────────────────────────────
  ctx.effect(() => {
    if (pollingActive) return
    pollingActive = true
    let stop = false

    window.__wfSetRoot = r => { wfRoot = r }

    const refresh = async () => {
      if (stop || !wfSessionActive) return
      try {
        // Iter-5：webServer HTTP 路由替代 harness RPC（host.call）
        // Iter-20：只查询**本会话绑定实例**（不存在→空态）；绝不取"工作区最新实例"
        const boundId = wfInstances.find(it => it.sessionId === wfSessionId)
        const q = '/wf/status?workspaceRoot=' + encodeURIComponent(wfRoot || '') + (boundId ? '&instanceId=' + encodeURIComponent(boundId.instanceId) : '')
        const resp = await fetch(q)
        const s = await resp.json()
        if (!stop) publish(s)
      } catch(e) {
        if (!stop) {
          lastError = e && e.message ? e.message : String(e)
          listeners.forEach(fn => { try { fn() } catch(e2) {} })
        }
      }
    }

    refresh()
    // 浏览器原生定时器（npm 包 Client 半边无 timer 服务；官方 client 插件同用 setInterval）
    const d = window.setInterval(refresh, 2000)

    return () => {
      stop = true
      pollingActive = false
      window.clearInterval(d)
      delete window.__wfSetRoot
    }
  })

  // ── 颜色映射 ────────────────────────────────────────────────────
  const C = {
    PENDING: '#9ca3af',
    RUNNING: '#3b82f6',
    DONE: '#22c55e',
    FAILED: '#ef4444',
    SKIPPED: '#f59e0b'
  }

  // ── LoopGroup 节点组件 ─────────────────────────────────────────
  function LoopGroupNode(props) {
    const { x, y, gW, gH, group, selectedId, onSelect, isExpanded, onToggle } = props
    const items = group.items, total = items.length
    const counts = { PENDING: 0, RUNNING: 0, DONE: 0, FAILED: 0, SKIPPED: 0 }
    items.forEach(t => { counts[t.status] = (counts[t.status] || 0) + 1 })
    const aggStatus = counts.RUNNING > 0 ? 'RUNNING' : counts.FAILED > 0 ? 'FAILED' : counts.SKIPPED > 0 ? 'SKIPPED' : counts.DONE === total ? 'DONE' : 'PENDING'
    const mc = C[aggStatus] || C.PENDING
    const isSel = selectedId === group.key

    const segs = []
    const segTypes = ['DONE','RUNNING','FAILED','SKIPPED','PENDING']
    segTypes.forEach(st => { if (counts[st] > 0) segs.push({ c: C[st], n: counts[st] }) })

    const tx = x + 8, ty = y + 16, barY = y + 33, countY = y + 45
    const barW = gW - 16
    const els = [
      React.createElement('rect', {
        key: 'bg', x, y, width: gW, height: gH, rx: 8,
        fill: mc, opacity: 0.92,
        stroke: isSel ? '#fff' : 'transparent',
        strokeWidth: isSel ? 3 : 0,
        cursor: 'pointer',
        onClick: () => onSelect(group.key)
      }),
      React.createElement('text', {
        key: 'tt', x: tx, y: ty, fill: '#fff', fontSize: 11, fontWeight: 600
      }, (props.label || '\u21BB ') + group.name + ' (' + total + ')'),
    ]

    // 进度条
    if (segs.length > 0) {
      els.push(
        React.createElement('rect', {
          key: 'pb', x: tx, y: barY, width: barW, height: 6, rx: 3,
          fill: 'rgba(0,0,0,0.2)'
        })
      )
      let segX = tx
      segs.forEach((s, i) => {
        const segW = Math.max(s.n / total * barW, 8)
        els.push(React.createElement('rect', {
          key: 'ps' + i, x: segX, y: barY, width: segW, height: 6, rx: 3, fill: s.c
        }))
        segX += segW
      })
    }

    // 计数标签
    const countStr = ['DONE','RUNNING','FAILED','SKIPPED'].map(st => {
      const c = counts[st]
      if (!c) return ''
      const sym = st === 'DONE' ? '\u2713' : st === 'RUNNING' ? '\u25CF' : st === 'FAILED' ? '\u2717' : '\u23ED'
      return c + sym
    }).filter(Boolean).join(' ')
    els.push(React.createElement('text', {
      key: 'ct', x: tx, y: countY, fill: 'rgba(255,255,255,0.9)', fontSize: 9
    }, countStr))

    // 展开/折叠图标
    els.push(
      React.createElement('text', {
        key: 'ex', x: x + gW - 8, y: ty, textAnchor: 'end', fill: '#fff', fontSize: 11, cursor: 'pointer',
        onClick: (e) => { e.stopPropagation(); onToggle() }
      }, isExpanded ? '\u25B2' : '\u25B6'),
    )

    return els
  }

  // ── DAG 画布组件 ───────────────────────────────────────────────
  const DagCanvas = React.memo(function DagCanvas(props) {
    const { stage, gateResult, tasks, selectedId, onSelect, workflowName, retries, error } = props
    const mc = stage === 'COMPLETED' ? (gateResult === 'FAIL' ? C.FAILED : C.DONE) : stage === 'FAILED' ? C.FAILED : stage === 'RUNNING' ? C.RUNNING : C.PENDING

    // 构建流程节点：start + 普通task / 垂直组(dependsOn相同无框) / loop折叠框 / concurrent折叠框 + end（Iter-8）
    const flat = Array.isArray(tasks) ? tasks : []
    const flowNodes = [], loopGroups = [], concGroups = []
    const depKeyOf = (t) => JSON.stringify((t.dependsOn || []).slice().sort())

    // start 节点（流程起点）
    flowNodes.push({ type: 'start' })

    for (let gi = 0; gi < flat.length;) {
      const t = flat[gi]
      if (t._loopGroup) {
        // loop 折叠框
        const g = { key: t._loopGroup, name: t._loopGroupName || t._loopGroup, items: [] }
        while (gi < flat.length && flat[gi]._loopGroup === g.key) { g.items.push(flat[gi]); gi++ }
        loopGroups.push(g)
        flowNodes.push({ type: 'loop', group: g })
      } else if (t._concurrentGroup) {
        // Iter-8：concurrent 折叠框（⚡ 并发）
        const g = { key: t._concurrentGroup, name: t._concurrentGroupName || t._concurrentGroup, items: [] }
        while (gi < flat.length && flat[gi]._concurrentGroup === g.key) { g.items.push(flat[gi]); gi++ }
        concGroups.push(g)
        flowNodes.push({ type: 'concgroup', group: g })
      } else {
        // 垂直组：连续多个 dependsOn 相同的 task（无线框，垂直排列，可并发）
        const depKey = depKeyOf(t)
        let j = gi + 1
        while (j < flat.length && !flat[j]._loopGroup && !flat[j]._concurrentGroup && depKeyOf(flat[j]) === depKey) j++
        if (j - gi > 1) {
          flowNodes.push({ type: 'vertgroup', tasks: flat.slice(gi, j), key: 'vg-' + t.id })
          gi = j
        } else {
          flowNodes.push({ type: 'task', task: t })
          gi++
        }
      }
    }

    // end 节点（流程终点）
    flowNodes.push({ type: 'end' })

    const gW = 132, gH = 46, gHLoop = 64, gap = 44, pad = 24
    const gapV = 8, padV = 10 // Iter-7：并发组内垂直间隔 + 组框内 padding
    let svgX = pad
    const svgChildren = []

    // 展开状态
    const [expanded, setExpanded] = React.useState({})
    const toggleGroup = React.useCallback(key => {
      setExpanded(prev => {
        const n = {}
        for (const k in prev) n[k] = prev[k]
        n[key] = !prev[key]
        return n
      })
    }, [])

    // 最高节点高度（统一垂直中心 + SVG 高度）
    const nodeHeightOf = (fn) => {
      if (fn.type === 'loop' || fn.type === 'concgroup') return gHLoop
      if (fn.type === 'vertgroup') return 2 * padV + fn.tasks.length * gH + (fn.tasks.length - 1) * gapV
      return gH
    }
    const maxH = flowNodes.reduce((mx, fn) => Math.max(mx, nodeHeightOf(fn)), 0)
    const centerY = maxH / 2 + pad

    // 节点位置
    const nodePositions = []

    flowNodes.forEach((fn, fi) => {
      const h = nodeHeightOf(fn)
      const cy = fn.type === 'start' || fn.type === 'end' ? centerY - gH / 2 : centerY - h / 2

      if (fn.type === 'task') {
        const t = fn.task
        const isSel = selectedId === t.id
        svgChildren.push(
          React.createElement('rect', {
            key: 'r' + t.id, x: svgX, y: cy, width: gW, height: h, rx: 8,
            fill: C[t.status] || C.PENDING, opacity: 0.92,
            stroke: isSel ? '#fff' : 'transparent', strokeWidth: isSel ? 3 : 0,
            cursor: 'pointer', onClick: () => onSelect(t.id)
          }),
          React.createElement('text', {
            key: 't' + t.id, x: svgX + gW / 2, y: cy + h / 2 + 5,
            textAnchor: 'middle', fill: '#fff', fontSize: 12, fontWeight: 600
          }, t.name || t.id),
          React.createElement('text', {
            key: 'u' + t.id, x: svgX + gW / 2, y: cy + h / 2 + 18,
            textAnchor: 'middle', fill: 'rgba(255,255,255,0.85)', fontSize: 10
          }, t.id),
        )
      } else if (fn.type === 'start') {
        // start 节点（绿色实心小圆点，流程起点）
        const cx = svgX + gW / 2
        svgChildren.push(
          React.createElement('circle', { key: 'st', cx, cy: centerY, r: 12, fill: '#22c55e' }),
        )
      } else if (fn.type === 'end') {
        // end 节点（红色空心小圆圈，流程终点）
        const cx = svgX + gW / 2
        svgChildren.push(
          React.createElement('circle', { key: 'en', cx, cy: centerY, r: 12, fill: 'none', stroke: '#ef4444', strokeWidth: 3 }),
        )
      } else if (fn.type === 'loop') {
        // Loop 组节点
        const g = fn.group
        const lgEls = LoopGroupNode({
          x: svgX, y: cy, gW, gH: gHLoop, group: g,
          selectedId, onSelect, isExpanded: !!expanded[g.key], onToggle: () => toggleGroup(g.key)
        })
        svgChildren.push(...lgEls)
      } else if (fn.type === 'concgroup') {
        // Iter-8：concurrent 节点——复用 LoopGroupNode（实线 + 进度 + 状态 + 可展开），标注 ⚡ 并发
        const g = fn.group
        const cgEls = LoopGroupNode({
          x: svgX, y: cy, gW, gH: gHLoop, group: g,
          selectedId, onSelect, isExpanded: !!expanded['cc-' + g.key], onToggle: () => toggleGroup('cc-' + g.key),
          label: '\u26A1 并发 '
        })
        svgChildren.push(...cgEls)
      } else {
        // Iter-8：依赖同一前驱的节点——垂直并列，无线框（各自独立，可并发）
        fn.tasks.forEach((t, i) => {
          const ty = cy + padV + i * (gH + gapV)
          const isSel = selectedId === t.id
          svgChildren.push(
            React.createElement('rect', {
              key: 'r' + t.id, x: svgX + 4, y: ty, width: gW - 8, height: gH, rx: 6,
              fill: C[t.status] || C.PENDING, opacity: 0.92,
              stroke: isSel ? '#fff' : 'transparent', strokeWidth: isSel ? 3 : 0,
              cursor: 'pointer', onClick: () => onSelect(t.id)
            }),
            React.createElement('text', {
              key: 't' + t.id, x: svgX + gW / 2, y: ty + gH / 2 + 5,
              textAnchor: 'middle', fill: '#fff', fontSize: 12, fontWeight: 600
            }, t.name || t.id),
            React.createElement('text', {
              key: 'u' + t.id, x: svgX + gW / 2, y: ty + gH / 2 + 18,
              textAnchor: 'middle', fill: 'rgba(255,255,255,0.85)', fontSize: 10
            }, t.id),
          )
        })
      }

      nodePositions.push({
        x: svgX, w: gW, h,
        type: fn.type,
        key: fn.type === 'start' || fn.type === 'end' ? fn.type
          : fn.type === 'loop' || fn.type === 'concgroup' ? fn.group.key
          : fn.type === 'vertgroup' ? fn.key
          : fn.task.id
      })
      svgX += gW + gap

      // 箭头（统一 centerY，对准所有节点中心）
      if (fi < flowNodes.length - 1) {
        svgChildren.push(
          React.createElement('line', {
            key: 'a' + fi,
            x1: svgX - gap + 3, y1: centerY,
            x2: svgX - 3, y2: centerY,
            stroke: '#94a3b8', strokeWidth: 2, markerEnd: 'url(#da)'
          }),
        )
      }
    })

    // 箭头标记
    if (flowNodes.length > 0) {
      svgChildren.push(
        React.createElement('defs', { key: 'd' },
          React.createElement('marker', {
            id: 'da', viewBox: '0 0 10 10', refX: 9, refY: 5,
            markerWidth: 7, markerHeight: 7, orient: 'auto-start-reverse'
          },
          React.createElement('path', { d: 'M 0 0 L 10 5 L 0 10 z', fill: '#94a3b8' }))))
    }

    const svgW = flowNodes.length ? pad * 2 + flowNodes.reduce((s, fn, i) => s + (i > 0 ? gap : 0) + gW, 0) : 0
    const svgH = maxH + 2 * pad

    // 展开的列表（SVG 下方）
    const listElems = []
    loopGroups.forEach(g => {
      if (!expanded[g.key]) return
      const pos = nodePositions.find(p => p.type === 'loop' && p.key === g.key)
      if (!pos) return
      const listX = pos.x
      const listW = gW
      listElems.push(
        React.createElement('div', {
          key: 'll' + g.key,
          style: {
            marginLeft: listX + 'px',
            width: listW + 'px',
            background: 'rgba(148,163,184,0.05)',
            border: '1px solid rgba(148,163,184,0.2)',
            borderTop: 'none',
            borderBottomLeftRadius: 8, borderBottomRightRadius: 8,
            padding: '4px 0',
            fontSize: 12,
          },
        }, g.items.map((t, i) => {
          const sel = selectedId === t.id
          return React.createElement('div', {
            key: t.id, onClick: () => onSelect(t.id),
            style: {
              display: 'flex', alignItems: 'center', gap: 6, padding: '3px 10px',
              cursor: 'pointer', background: sel ? 'rgba(59,130,246,0.1)' : 'transparent',
            },
          }, [
            React.createElement('span', {
              style: { width: 8, height: 8, borderRadius: 4, background: C[t.status] || C.PENDING, flexShrink: 0 }
            }),
            React.createElement('span', { style: { flex: 1, color: '#475569' } }, (i + 1) + '. ' + (t.name || t.id)),
            React.createElement('span', { style: { color: '#64748b', fontSize: 11 } }, t.status),
          ])
        }))
      )
    })

    // Iter-8：concurrent 组展开列表（SVG 下方，同 loop）
    concGroups.forEach(g => {
      if (!expanded['cc-' + g.key]) return
      const pos = nodePositions.find(p => p.type === 'concgroup' && p.key === g.key)
      if (!pos) return
      const listX = pos.x
      const listW = gW
      listElems.push(
        React.createElement('div', {
          key: 'cl' + g.key,
          style: {
            marginLeft: listX + 'px',
            width: listW + 'px',
            background: 'rgba(59,130,246,0.05)',
            border: '1px solid rgba(59,130,246,0.2)',
            borderTop: 'none',
            borderBottomLeftRadius: 8, borderBottomRightRadius: 8,
            padding: '4px 0',
            fontSize: 12,
          },
        }, g.items.map((t, i) => {
          const sel = selectedId === t.id
          return React.createElement('div', {
            key: t.id, onClick: () => onSelect(t.id),
            style: {
              display: 'flex', alignItems: 'center', gap: 6, padding: '3px 10px',
              cursor: 'pointer', background: sel ? 'rgba(59,130,246,0.1)' : 'transparent',
            },
          }, [
            React.createElement('span', {
              style: { width: 8, height: 8, borderRadius: 4, background: C[t.status] || C.PENDING, flexShrink: 0 }
            }),
            React.createElement('span', { style: { flex: 1, color: '#475569' } }, (i + 1) + '. ' + (t.name || t.id)),
            React.createElement('span', { style: { color: '#64748b', fontSize: 11 } }, t.status),
          ])
        }))
      )
    })

    return React.createElement('div', { style: { padding: '14px 18px 10px' } }, [
      // 状态栏
      React.createElement('div', {
        key: 'sb',
        style: { display: 'flex', alignItems: 'center', gap: 14, marginBottom: 8, fontSize: 12, color: '#64748b', flexWrap: 'wrap' },
      }, [
        React.createElement('span', { key: 'w', style: { fontWeight: 600, color: '#334155' } }, workflowName || '-'),
        React.createElement('span', { key: 's' }, 'S: ', React.createElement('span', { style: { color: mc, fontWeight: 700 } },
          (stage || '-') + ' ' + (stage === 'PENDING' ? 'Pd' : stage === 'RUNNING' ? 'Rn' : stage === 'COMPLETED' ? 'Cp' : 'Fl'))),
        React.createElement('span', { key: 'g' }, 'G: ', gateResult
          ? React.createElement('span', { style: { color: gateResult === 'PASS' ? C.DONE : C.FAILED, fontWeight: 700 } }, gateResult)
          : '-'),
        retries > 0 ? React.createElement('span', { key: 'r' }, 'R: ' + retries) : null,
        error ? React.createElement('span', { key: 'e', style: { color: C.FAILED } }, error) : null,
      ]),
      // SVG 流程图
      flowNodes.length > 0 ? React.createElement('svg', {
        key: 'svg', width: svgW, height: svgH,
        xmlns: 'http://www.w3.org/2000/svg',
        style: { background: 'rgba(148,163,184,0.08)', borderRadius: 8, width: '100%', maxWidth: svgW, marginBottom: 0 },
      }, svgChildren) : null,
      // 展开的列表
      React.createElement('div', { key: 'lx', style: { position: 'relative', marginTop: -4 } }, listElems),
    ])
  })

  // ── Slot 注册 ──────────────────────────────────────────────────
  slots.inject('conversation.view', () => {
    return slots.register(
      { name: 'conversation.view', id: 'workflow', order: 25, label: () => 'Workflow' },
      function WorkflowViewFactory(props) {
        const workspaceHook = props.useWorkspaces
        const sessionId = props.sessionId
        wfSessionId = (sessionId === undefined || sessionId === null) ? '' : String(sessionId)
        const useSessions = props.useSessions
        // Iter-12：跟随当前 session 的 cwd（切 session → 实例目录跟随）
        const sessionCwd = useSessions
          ? useSessions((s) => (sessionId === undefined || sessionId === null) ? undefined : (s.byId && s.byId[sessionId] ? s.byId[sessionId].cwd : undefined))
          : undefined
        // Iter-15：提取 parentSessionId（用于 subagent session 的消息注入）
        const parentSessionId = useSessions
          ? useSessions((s) => (sessionId === undefined || sessionId === null) ? undefined : (s.byId && s.byId[sessionId] ? s.byId[sessionId].parentSessionId : undefined))
          : undefined
        // Iter-20(S5)：当前会话 agent preset（预设门控；仅 workflow-orchestrator 显示面板）
        const sessionPreset = useSessions
          ? useSessions((s) => (sessionId === undefined || sessionId === null) ? undefined : (s.byId && s.byId[sessionId] ? s.byId[sessionId].agentPreset : undefined))
          : undefined
        // Iter-21(R2)：子会话（origin==='subagent'）一律占位，不显示工作流面板
        const sessionOrigin = useSessions
          ? useSessions((s) => (sessionId === undefined || sessionId === null) ? undefined : (s.byId && s.byId[sessionId] ? s.byId[sessionId].origin : undefined))
          : undefined
        const isWorkflowSession = sessionPreset === 'workflow-orchestrator' && sessionOrigin !== 'subagent'
        wfSessionActive = isWorkflowSession

        if (!WfComponent) {
          WfComponent = function(props) {
            const sessionId = props.sessionId
            const isWorkflowSession = props.isWorkflowSession
            const sessionCwd = props.sessionCwd
            const parentSessionId = props.parentSessionId
            const workspaceHook = props.workspaceHook
          const [, forceUpdate] = React.useReducer(x => x + 1, 0)
          const [selectedId, setSelectedId] = React.useState(null)

          React.useEffect(() => {
            listeners.add(forceUpdate)
            return () => listeners.delete(forceUpdate)
          }, [])

          // Iter-20(S5)：非编排会话 → 停止实例列表轮询（状态轮询由 wfSessionActive 短路）
          React.useEffect(() => {
            if (isWorkflowSession) {
              // Iter-21(R3)：成为 workflow 会话（如 preset 异步加载 false→true）→ 启动列表轮询
              if (activeRoot) startListPolling()
            } else {
              if (listPollingTimer) { clearInterval(listPollingTimer); listPollingTimer = null }
            }
            return () => {}
          }, [isWorkflowSession])

          // ── Iter-12：workspaceRoot 解析——session cwd 优先，回退当前工作区首项 ──
          React.useEffect(() => {
            let next = null
            if (typeof sessionCwd === 'string' && sessionCwd) {
              next = String(sessionCwd).replace(/\\/g, '/')
              // 如果是相对路径，转换为绝对路径
              if (!next.startsWith('/')) {
                next = '/home/zhaokai/Projects/dsh_projects/' + next
              }
            }
            if (!next && workspaceHook) {
              try {
                const wsList = workspaceHook()
                if (wsList && wsList.data && Array.isArray(wsList.data.items) && wsList.data.items.length > 0) {
                  next = String(wsList.data.items[0].path).replace(/\\/g, '/')
                }
              } catch (e) {}
            }
            if (!next || next === activeRoot) return
            activeRoot = next
            wfRoot = next
            wfLoaded = true
            latest = null; lastError = null
            wfInstances = []; wfInstanceId = ''
            if (typeof window.__wfSetRoot === 'function') window.__wfSetRoot(next)
            listeners.forEach(fn => { try { fn() } catch (e2) {} })
            // 启动实例列表轮询
            startListPolling()
          }, [sessionCwd, workspaceHook])

          // ── Iter-21(R3)：会话切换（含同工作区 cwd 不变）→ 重置会话派生态并重拉列表 ──
          React.useEffect(() => {
            const sid = (sessionId === undefined || sessionId === null) ? '' : String(sessionId)
            if (sid === wfLastSessionId) return
            wfLastSessionId = sid
            // 仅重置派生态（gating 用）；不重置 wfInstances（工作区级列表，同工作区仍有效/避免采用池空）
            // 不重置 latest（由 /wf/status 按新 boundId 更新，避免 DAG 闪空白）
            wfSessionState = null; wfInstanceId = ''; wfStopHint = null
            // 仅 workflow 会话重拉列表；非编排会话保持占位 + 短路轮询
            if (isWorkflowSession && activeRoot) startListPolling()
            listeners.forEach(fn => { try { fn() } catch (e) {} })
          }, [sessionId, isWorkflowSession])

          // ── Iter-12：实例列表轮询（只读；选择经 wfInstanceId 参与 status 轮询）──
          // 注意：轮询在 workspaceRoot 解析 effect 里启动，不依赖 React state
          // 这里只负责清理
          React.useEffect(() => {
            return () => {
              if (wfListLoader) {
                wfListLoader.stop = true
                wfListLoader = null
              }
            }
          }, [])

          const snap = latest
          const stateData = (snap && snap.state) ? snap.state : null
          const tasks = stateData && Array.isArray(stateData.tasks) ? stateData.tasks : []
          const hasData = stateData && stateData.workflow

          // ── Iter-13：面板创建（"+" + 表单；hooks 全部置于条件返回之前）────
          const [formOpen, setFormOpen] = React.useState(false)
          const [adoptOpen, setAdoptOpen] = React.useState(false) // Iter-20：采用未绑定实例
          const [tplOpts, setTplOpts] = React.useState([])
          const [tplSel, setTplSel] = React.useState('custom')
          const [yamlText, setYamlText] = React.useState('')
          const [pathText, setPathText] = React.useState('')
          const [paramsText, setParamsText] = React.useState('{}')
          const [busy, setBusy] = React.useState(false)
          const [formErr, setFormErr] = React.useState('')

          React.useEffect(() => {
            if (!formOpen || !activeRoot) return
            let stop = false
            fetch('/wf/templates?workspaceRoot=' + encodeURIComponent(activeRoot))
              .then(r => r.json())
              .then(r => {
                if (stop) return
                const opts = [{ v: 'custom', label: '自定义路径…' }]
                ;(r.builtin || []).forEach(t => opts.push({ v: 'builtin:' + t.name, label: '[内置] ' + (t.description || t.name), t }))
                ;(r.workspace || []).forEach(w => opts.push({ v: 'ws:' + w.path, label: '[工作区] ' + w.name }))
                setTplOpts(opts)
                if (opts.length > 1) { setTplSel(opts[1].v); setYamlText(opts[1].t ? opts[1].t.yaml : '') }
              })
              .catch(() => {})
            return () => { stop = true }
          }, [formOpen, activeRoot])

          const openForm = () => { setFormErr(''); setFormOpen(true) }
          const pickTpl = (v) => {
            setTplSel(v)
            const opt = tplOpts.find(o => o.v === v)
            setYamlText(opt && opt.t ? opt.t.yaml : '')
          }
          const submitCreate = async () => {
            setFormErr(''); setBusy(true)
            try {
              let params = {}
              try { params = paramsText.trim() ? JSON.parse(paramsText) : {} } catch (e) { throw new Error('params 不是合法 JSON') }
              const payload = { workspaceRoot: activeRoot, params, sessionId } // Iter-19：面板创建即绑定当前 sessionId
              if (tplSel === 'custom') {
                if (!pathText.trim()) throw new Error('请填写 workflowPath')
                payload.workflowPath = pathText.trim()
              } else if (tplSel.startsWith('ws:')) {
                payload.workflowPath = tplSel.slice(3)
              } else if (tplSel.startsWith('builtin:')) {
                if (!yamlText.trim()) throw new Error('模板内容为空')
                payload.workflowText = yamlText
              }
              const resp = await fetch('/wf/create', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) })
              const r = await resp.json()
              if (!resp.ok) throw new Error((r && r.error) || ('HTTP ' + resp.status))
              setFormOpen(false)
              if (typeof wfListLoader === 'function') wfListLoader()
              // Iter-19：CONFLICT 自愈告知——新建时自动解绑了冲突旧实例
              if (r && Array.isArray(r.recoveredConflict) && r.recoveredConflict.length > 0) {
                alert('检测到工作区存在实例绑定冲突（同一会话被多实例占用）。已自动解绑冲突实例 [' + r.recoveredConflict.join(', ') + '] 回未绑定池；当前实例已绑定本会话。如非预期请在实例列表查看。')
              }
            } catch (e) {
              setFormErr(e && e.message ? e.message : String(e))
            } finally {
              setBusy(false)
            }
          }

          const fieldStyle = { border: '1px solid rgba(148,163,184,0.4)', borderRadius: 6, padding: '4px 8px', background: 'rgba(148,163,184,0.08)', color: 'inherit', fontSize: 12, width: '100%', boxSizing: 'border-box' }
          const monoStyle = Object.assign({}, fieldStyle, { fontFamily: 'monospace', resize: 'vertical' })
          const btnStyle = { border: '1px solid rgba(148,163,184,0.4)', background: 'transparent', color: 'inherit', borderRadius: 6, padding: '3px 12px', cursor: 'pointer', fontSize: 12 }

          // Iter-15：面板控制按钮（Start/Stop/Reset）
          const controlBtns = []
          const currentStage = stateData && stateData.stage
          // Iter-20：当前实例 = 本会话绑定实例（snap 优先，其次 wfInstances 中绑本会话的实例）
          const boundInstance = wfInstances.find(it => it.sessionId === wfSessionId)
          const currentInstanceId = (snap && snap.instanceId) || (boundInstance && boundInstance.instanceId) || ''
          const sessionBound = !!(wfSessionState && wfSessionState.state === 'BOUND')

          // Iter-21：控制中间态终止——stage 已从 origin 移开（操作完成）或超时兜底
          if (wfPendingCmd && currentStage) {
            const originOk = wfPendingCmd === 'start'
              ? (currentStage === 'CREATED' || currentStage === 'PENDING')
              : wfPendingCmd === 'stop' ? (currentStage === 'RUNNING')
              : (currentStage === 'STOPPED')
            if (!originOk || (wfPendingAt && Date.now() - wfPendingAt > 30000)) {
              wfPendingCmd = null; wfPendingAt = 0
            }
          }
          
          // Start 按钮（仅本会话已绑定实例（BOUND）且为可启动态时显示）
          if (sessionBound && (!currentStage || currentStage === 'CREATED' || currentStage === 'PENDING')) {
            if (wfPendingCmd === 'start') {
              // Iter-21：中间态——agent 尚未把实例切到 RUNNING，禁用并显示"启动中…"
              controlBtns.push(React.createElement('button', {
                key: 'start', title: '启动中…', disabled: true,
                style: { border: '1px solid rgba(148,163,184,0.35)', background: 'transparent', color: '#94a3b8', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'default' }
              }, '启动中…'))
            } else {
              controlBtns.push(React.createElement('button', {
                key: 'start', title: '启动实例',
                onClick: async () => {
                  if (!currentInstanceId || !activeRoot) return
                  wfPendingCmd = 'start'; wfPendingAt = Date.now()
                  try {
                    const resp = await fetch('/wf/start', {
                      method: 'POST',
                      headers: { 'Content-Type': 'application/json' },
                      body: JSON.stringify({ 
                        workspaceRoot: activeRoot, 
                        instanceId: currentInstanceId,
                        sessionId: sessionId, // 传递当前 session ID
                        parentSessionId: parentSessionId // 传递 parent session ID（用于 subagent session）
                      })
                    })
                    if (!resp.ok) {
                      const err = await resp.json()
                      alert('启动失败: ' + (err.error || '未知错误'))
                    }
                  } catch (e) {
                    alert('启动失败: ' + e.message)
                  }
                },
                style: { border: '1px solid rgba(34,197,94,0.5)', background: 'rgba(34,197,94,0.1)', color: '#22c55e', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'pointer' }
              }, '▶ Start'))
            }
          }
          
          // Stop 按钮（仅 RUNNING 时显示；PENDING 属待启动，非执行中）
          if (sessionBound && currentStage === 'RUNNING') {
            if (wfPendingCmd === 'stop') {
              // Iter-21：中间态——agent 尚未把实例切到 STOPPED，禁用并显示"停止中…"
              controlBtns.push(React.createElement('button', {
                key: 'stop', title: '停止中…', disabled: true,
                style: { border: '1px solid rgba(148,163,184,0.35)', background: 'transparent', color: '#94a3b8', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'default' }
              }, '停止中…'))
            } else {
              controlBtns.push(React.createElement('button', {
                key: 'stop', title: '停止实例',
                onClick: async () => {
                  if (!currentInstanceId || !activeRoot) return
                  wfPendingCmd = 'stop'; wfPendingAt = Date.now()
                  try {
                    const resp = await fetch('/wf/stop', {
                      method: 'POST',
                      headers: { 'Content-Type': 'application/json' },
                      body: JSON.stringify({ workspaceRoot: activeRoot, instanceId: currentInstanceId, sessionId: sessionId, parentSessionId: parentSessionId }) // Iter-21：带 session 供消息注入
                    })
                    if (!resp.ok) {
                      const err = await resp.json()
                      alert('停止失败: ' + (err.error || '未知错误'))
                    }
                  } catch (e) {
                    alert('停止失败: ' + e.message)
                  }
                },
                style: { border: '1px solid rgba(239,68,68,0.5)', background: 'rgba(239,68,68,0.1)', color: '#ef4444', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'pointer' }
              }, '⏹ Stop'))
            }
          }
          
          // Iter-21(R5)：Resume 按钮（STOPPED 时显示；续跑保 DONE）
          if (sessionBound && currentStage === 'STOPPED') {
            if (wfPendingCmd === 'resume') {
              // Iter-21：中间态——agent 尚未把实例切到 RUNNING，禁用并显示"恢复中…"
              controlBtns.push(React.createElement('button', {
                key: 'resume', title: '恢复中…', disabled: true,
                style: { border: '1px solid rgba(148,163,184,0.35)', background: 'transparent', color: '#94a3b8', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'default' }
              }, '恢复中…'))
            } else {
              controlBtns.push(React.createElement('button', {
                key: 'resume', title: '恢复实例（续跑，保留已完成）',
                onClick: async () => {
                  if (!currentInstanceId || !activeRoot) return
                  wfPendingCmd = 'resume'; wfPendingAt = Date.now()
                  try {
                    const resp = await fetch('/wf/resume', {
                      method: 'POST',
                      headers: { 'Content-Type': 'application/json' },
                      body: JSON.stringify({ workspaceRoot: activeRoot, instanceId: currentInstanceId, sessionId: sessionId, parentSessionId: parentSessionId }) // Iter-21：带 session 供消息注入
                    })
                    if (!resp.ok) {
                      const err = await resp.json()
                      alert('恢复失败: ' + (err.error || '未知错误'))
                    }
                  } catch (e) {
                    alert('恢复失败: ' + e.message)
                  }
                },
                style: { border: '1px solid rgba(59,130,246,0.5)', background: 'rgba(59,130,246,0.1)', color: '#3b82f6', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'pointer' }
              }, '▶ Resume'))
            }
          }
          
          // Reset 按钮（STOPPED、COMPLETED、FAILED 时显示）
          if (sessionBound && (currentStage === 'STOPPED' || currentStage === 'COMPLETED' || currentStage === 'FAILED')) {
            controlBtns.push(React.createElement('button', {
              key: 'reset', title: '重置实例（清空状态，保留产物）',
              onClick: async () => {
                if (!currentInstanceId || !activeRoot) return
                if (!confirm('确定要重置实例吗？状态将被清空，产物文件保留。')) return
                try {
                  const resp = await fetch('/wf/reset', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ workspaceRoot: activeRoot, instanceId: currentInstanceId, sessionId: sessionId, parentSessionId: parentSessionId }) // Iter-22(S4)：带 session 供"已重置"消息注入
                  })
                  if (!resp.ok) {
                    const err = await resp.json()
                    alert('重置失败: ' + (err.error || '未知错误'))
                  }
                } catch (e) {
                  alert('重置失败: ' + e.message)
                }
              },
              style: { border: '1px solid rgba(245,158,11,0.5)', background: 'rgba(245,158,11,0.1)', color: '#f59e0b', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'pointer' }
            }, '↻ Reset'))
          }

          // Iter-19：创建按钮仅当会话 UNBOUND（无绑定实例）时显示
          const canCreate = !wfSessionState || wfSessionState.state === 'UNBOUND'
          const plusBtn = canCreate ? React.createElement('button', {
            key: 'plus', title: '新建 workflow 实例（只创建，不启动）', onClick: openForm,
            style: { border: '1px solid rgba(148,163,184,0.35)', background: 'transparent', color: 'inherit', borderRadius: 6, padding: '1px 9px', fontSize: 14, cursor: 'pointer', lineHeight: '18px' }
          }, '+ 创建') : null
          // Iter-20(R3)：会话 UNBOUND 时提供"采用"入口（选未绑定实例并绑定本会话）
          const adoptBtn = canCreate ? React.createElement('button', {
            key: 'adopt', title: '采用一个未绑定实例（绑定本会话）', onClick: () => { if (activeRoot) startListPolling(); setAdoptOpen(true) }, // Iter-21：打开即刷新列表，避免采用池空/延迟;孤儿可采纳(需 S3 recoverOrphan)属 Iter-22
            style: { border: '1px solid rgba(59,130,246,0.5)', background: 'rgba(59,130,246,0.1)', color: '#3b82f6', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'pointer', lineHeight: '18px' }
          }, '采用') : null
          // 会话 UNBOUND → 显示 创建/采用；已绑定 → 显示状态机控制按钮
          const toolbar = React.createElement('div', {
            key: 'tb', style: { display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: 6, padding: '6px 12px 0' }
          }, canCreate ? [plusBtn, adoptBtn] : controlBtns)

          const formOverlay = !formOpen ? null : React.createElement('div', {
            style: { position: 'fixed', top: 0, right: 0, bottom: 0, left: 0, background: 'rgba(0,0,0,0.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50 },
            onClick: () => setFormOpen(false)
          }, React.createElement('div', {
            style: { background: 'var(--dsw-alias-bg-base, #1e293b)', color: 'var(--dsw-alias-label-primary, #e2e8f0)', borderRadius: 10, padding: 16, width: 460, maxWidth: '92vw', display: 'flex', flexDirection: 'column', gap: 8, fontSize: 12 },
            onClick: (e) => e.stopPropagation()
          }, [
            React.createElement('div', { key: 't', style: { fontSize: 13, fontWeight: 600 } }, '新建 workflow 实例（只创建，不启动）'),
            React.createElement('label', { key: 'l1' }, '模板 / 来源'),
            React.createElement('select', { key: 's1', value: tplSel, onChange: e => pickTpl(e.target.value), style: fieldStyle },
              tplOpts.map(o => React.createElement('option', { key: o.v, value: o.v }, o.label))
            ),
            tplSel === 'custom' ? React.createElement('input', { key: 'p', value: pathText, onChange: e => setPathText(e.target.value), placeholder: 'workflow YAML 绝对路径', style: fieldStyle }) : null,
            tplSel.indexOf('builtin:') === 0 ? React.createElement('textarea', { key: 'y', value: yamlText, onChange: e => setYamlText(e.target.value), rows: 10, style: monoStyle, spellCheck: false }) : null,
            React.createElement('label', { key: 'l2' }, 'params（JSON，可选）'),
            React.createElement('textarea', { key: 'pj', value: paramsText, onChange: e => setParamsText(e.target.value), rows: 3, style: monoStyle, spellCheck: false }),
            formErr ? React.createElement('div', { key: 'err', style: { color: '#f87171', whiteSpace: 'pre-wrap' } }, formErr) : null,
            React.createElement('div', { key: 'btns', style: { display: 'flex', justifyContent: 'flex-end', gap: 8 } }, [
              React.createElement('button', { key: 'c', onClick: () => setFormOpen(false), style: btnStyle }, '取消'),
              React.createElement('button', { key: 'o', onClick: submitCreate, disabled: busy, style: Object.assign({}, btnStyle, { background: '#3b82f6', color: '#fff', border: 'none' }) }, busy ? '创建中…' : '创建'),
            ]),
          ]))

          // Iter-20(S5)：非 workflow-orchestrator 会话 → 占位（不显示面板/控件）
          if (!isWorkflowSession) {
            return React.createElement('div', {
              style: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', minHeight: 420, color: '#9ca3af', fontSize: 13 }
            }, '此会话不是 Workflow 编排会话，无监控面板。')
          }
          // Iter-20(S5)：BROKEN → 环境异常告警（隐藏操作按钮）
          if (wfSessionState && wfSessionState.state === 'BROKEN') {
            return React.createElement('div', {
              style: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8, height: '100%', minHeight: 420, color: '#ef4444', fontSize: 13 }
            }, [
              React.createElement('div', { key: 't', style: { fontWeight: 600, fontSize: 14 } }, '⚠ 环境异常，需新建 workflow 会话'),
              React.createElement('div', { key: 'r', style: { color: '#9ca3af', fontSize: 12, textAlign: 'center', maxWidth: 420 } },
                wfSessionState.reason ? ('原因：' + wfSessionState.reason) : '工作流工作区损坏或存在绑定冲突，无法继续使用当前实例。'),
            ])
          }
          // Iter-20(S5)：DONE（归档声明本会话）→ 已归档提示（不可再启动）
          if (wfSessionState && wfSessionState.state === 'DONE') {
            return React.createElement('div', {
              style: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', minHeight: 420, color: '#9ca3af', fontSize: 13 }
            }, '该工作流实例已归档（完成）。如需新建请开启新的 Workflow 编排会话。')
          }

          if (!wfLoaded) {
            return React.createElement('div', {
              style: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', minHeight: 420, color: '#9ca3af', fontSize: 13 }
            }, '...')
          }

          if (!wfRoot) {
            return React.createElement('div', {
              style: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', minHeight: 420, color: '#9ca3af', fontSize: 13, flexDirection: 'column', gap: 8 }
            }, [
              React.createElement('span', { key: 'a' }, 'No workspace'),
              React.createElement('span', { key: 'b', style: { fontSize: 11 } }, 'Open a workspace first')
            ])
          }


          // ── Iter-20(R3)：移除常驻实例切换条；改为"采用"弹窗（可选未绑定实例并绑定本会话）──
          const poolInstances = wfInstances.filter(it => it.sessionId == null)
          const instBar = null // R3：不再常驻展示实例列表
          const doAdopt = async (pid) => {
            if (!sessionId || !activeRoot) { alert('无会话上下文，无法采用'); return }
            try {
              const resp = await fetch('/wf/adopt', {
                method: 'POST', headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ workspaceRoot: activeRoot, instanceId: pid, sessionId })
              })
              const r = await resp.json()
              if (!resp.ok) throw new Error((r && r.error) || ('HTTP ' + resp.status))
              setAdoptOpen(false); wfInstanceId = ''
              if (typeof wfListLoader === 'function') wfListLoader()
            } catch (e) { alert('采用失败: ' + (e && e.message ? e.message : String(e))) }
          }
          const adoptOverlay = !adoptOpen ? null : React.createElement('div', {
            style: { position: 'fixed', top: 0, right: 0, bottom: 0, left: 0, background: 'rgba(0,0,0,0.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50 },
            onClick: () => setAdoptOpen(false)
          }, React.createElement('div', {
            style: { background: 'var(--dsw-alias-bg-base, #1e293b)', color: 'var(--dsw-alias-label-primary, #e2e8f0)', borderRadius: 10, padding: 16, width: 420, maxWidth: '92vw', display: 'flex', flexDirection: 'column', gap: 8, fontSize: 12 },
            onClick: (e) => e.stopPropagation()
          }, [
            React.createElement('div', { key: 'tt', style: { fontSize: 13, fontWeight: 600 } }, '采用未绑定实例（绑定到本会话）'),
            (poolInstances.length === 0
              ? React.createElement('div', { key: 'e', style: { color: '#9ca3af', fontSize: 12 } }, '当前没有未绑定实例。请先「创建」一个新实例。')
              : React.createElement('div', { key: 'lst', style: { display: 'flex', flexDirection: 'column', gap: 6, maxHeight: 260, overflowY: 'auto' } },
                poolInstances.map(it => React.createElement('button', {
                  key: it.instanceId, onClick: () => doAdopt(it.instanceId),
                  style: { textAlign: 'left', border: '1px solid rgba(148,163,184,0.35)', background: 'transparent', color: 'inherit', borderRadius: 6, padding: '6px 10px', fontSize: 12, cursor: 'pointer' }
                }, it.workflowName + ' · ' + String(it.instanceId).slice(-8) + (it.poolNote ? ' · ' + it.poolNote : (it.stage ? ' · ' + it.stage : ' · 未启动')))))),
            React.createElement('button', { key: 'c', onClick: () => setAdoptOpen(false), style: btnStyle }, '取消'),
          ]))

          // Iter-23(A3)：Case I 停止无效提示条（状态触发非点击触发：绑定实例 RUNNING + 主会话
          // 空闲 + 子会话在跑时 /wf/list 返回 stopHint；状态解除自动消失）
          const stopHintBar = !wfStopHint ? null : React.createElement('div', {
            key: 'stopHint', role: 'status',
            style: { margin: '6px 12px 0', padding: '7px 12px', borderRadius: 8, fontSize: 12, lineHeight: '18px', border: '1px solid rgba(245,158,11,0.45)', background: 'rgba(245,158,11,0.08)', color: '#f59e0b' }
          }, '⏸ ' + (wfStopHint.message || '编排会话空闲等待中：会话内的停止按钮此刻无效。后台任务执行中——要停止工作流请点面板 Stop'))

          if (!hasData) {
            return React.createElement('div', {
              style: { display: 'flex', flexDirection: 'column', height: '100%', minHeight: 420, fontFamily: 'inherit', fontSize: 13 }
            },
              toolbar,
              stopHintBar,
              formOverlay,
            adoptOverlay,
              React.createElement('div', {
                style: { display: 'flex', alignItems: 'center', justifyContent: 'center', flex: 1, color: '#9ca3af', fontSize: 13, border: '1px dashed rgba(148,163,184,0.35)', borderRadius: 8, margin: 12, background: 'rgba(148,163,184,0.05)' }
              }, stateData && stateData.error ? 'Workflow Error: ' + stateData.error : (canCreate ? '尚未绑定工作流实例。点击「创建」新建，或「采用」绑定一个未绑定实例。' : 'Waiting for workflow...'))
            )
          }


          return React.createElement('div', {
            style: { display: 'flex', flexDirection: 'column', height: '100%', minHeight: 420, fontFamily: 'inherit', fontSize: 13 }
          },
            toolbar,
            stopHintBar,
            React.createElement(DagCanvas, {
              stage: stateData.stage,
              gateResult: stateData.gateResult || null,
              tasks,
              selectedId,
              onSelect: id => setSelectedId(prev => prev === id ? null : id),
              workflowName: stateData.workflow,
              retries: stateData.retries || 0,
              error: stateData.error || null,
            }),
            formOverlay,
            adoptOverlay
          )
          }
        }
        return React.createElement(WfComponent, { sessionId, isWorkflowSession, sessionCwd, parentSessionId, workspaceHook })
      },
    )
  })
}

    
    // Plugin code ends here
    
    function apply(ctx) {
      register(ctx);
    }
    
    const inject = ['slots'];
    
    exports.apply = apply;
    exports.inject = inject;
    
    return module.exports;
  }
});
