// @workflow-agent/client-ui-monitor - Client UI Plugin
// Auto-generated by build.js - DO NOT EDIT
window.__ModuleLoader__.load({
  id: "@workflow-agent/client-ui-monitor",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    
    const React = require("react");
    
    // Iter-5：不再 require host —— host 是动态插件闭包注入符号，
    // npm 包从 @deepseek-ai/dsh-client-runtime 无法获得。
    // Client 改用 fetch() 调用 Host 侧 webServer HTTP 路由（/wf/*）。
    
    // Plugin code starts here
    // Workflow Agent DAG 监控面板 - npm 包版本
// 从动态插件 wff-9/pkg-14 迁移而来

function register(ctx) {
  const slots = ctx.get('slots')
  if (!slots) return

  // ── 模块级数据层（防止 remount 闪烁）────────────────────────────
  let latest = null, lastError = null
  const listeners = new Set()
  let pollingActive = false, wfRoot = '', wfLoaded = false
  // Iter-12：cwd 跟随 + 实例列表（activeRoot=当前轮询锚点；wfInstanceId=面板选择）
  let activeRoot = null, wfInstances = [], wfInstanceId = ''
  // Iter-13：列表加载器引用（面板创建成功后即时刷新）
  let wfListLoader = null

  function fingerprint(state) {
    if (!state || !state.tasks) return ''
    const t = state.tasks.map(x => x.id + ':' + x.status).join(',')
    return [state.stage || '', state.gateResult || '', state.retries || 0, t].join('|')
  }

  function publish(state) {
    const fp = state ? fingerprint(state) : ''
    if (fp && latest && latest.__fp === fp) return
    if (state) state.__fp = fp
    latest = state; lastError = state ? null : 'disconnected'
    listeners.forEach(fn => { try { fn() } catch(e) {} })
  }

  // ── 实例列表轮询 ─────────────────────────────────────────────
  let listPollingTimer = null
  function startListPolling() {
    if (!activeRoot) return
    // 清理旧的轮询
    if (listPollingTimer) {
      clearInterval(listPollingTimer)
    }
    
    const loadList = async () => {
      if (!activeRoot) return
      try {
        const resp = await fetch('/wf/list?workspaceRoot=' + encodeURIComponent(activeRoot))
        const r = await resp.json()
        wfInstances = r && Array.isArray(r.instances) ? r.instances : []
        listeners.forEach(fn => { try { fn() } catch (e2) {} })
      } catch (e) {
        // 静默失败，下次轮询重试
      }
    }
    
    // 立即加载一次
    loadList()
    // 每 10 秒轮询
    listPollingTimer = setInterval(loadList, 10000)
  }

  // ── 轮询逻辑 ───────────────────────────────────────────────────
  ctx.effect(() => {
    if (pollingActive) return
    pollingActive = true
    let stop = false

    window.__wfSetRoot = r => { wfRoot = r }

    const refresh = async () => {
      if (stop) return
      try {
        // Iter-5：webServer HTTP 路由替代 harness RPC（host.call）
        // Iter-12：面板选择的实例（wfInstanceId）参与轮询；空=最新实例
        const q = '/wf/status?workspaceRoot=' + encodeURIComponent(wfRoot || '') + (wfInstanceId ? '&instanceId=' + encodeURIComponent(wfInstanceId) : '')
        const resp = await fetch(q)
        const s = await resp.json()
        if (!stop) publish(s)
      } catch(e) {
        if (!stop) {
          lastError = e && e.message ? e.message : String(e)
          listeners.forEach(fn => { try { fn() } catch(e2) {} })
        }
      }
    }

    refresh()
    // 浏览器原生定时器（npm 包 Client 半边无 timer 服务；官方 client 插件同用 setInterval）
    const d = window.setInterval(refresh, 2000)

    return () => {
      stop = true
      pollingActive = false
      window.clearInterval(d)
      delete window.__wfSetRoot
    }
  })

  // ── 颜色映射 ────────────────────────────────────────────────────
  const C = {
    PENDING: '#9ca3af',
    RUNNING: '#3b82f6',
    DONE: '#22c55e',
    FAILED: '#ef4444',
    SKIPPED: '#f59e0b'
  }

  // ── LoopGroup 节点组件 ─────────────────────────────────────────
  function LoopGroupNode(props) {
    const { x, y, gW, gH, group, selectedId, onSelect, isExpanded, onToggle } = props
    const items = group.items, total = items.length
    const counts = { PENDING: 0, RUNNING: 0, DONE: 0, FAILED: 0, SKIPPED: 0 }
    items.forEach(t => { counts[t.status] = (counts[t.status] || 0) + 1 })
    const aggStatus = counts.RUNNING > 0 ? 'RUNNING' : counts.FAILED > 0 ? 'FAILED' : counts.SKIPPED > 0 ? 'SKIPPED' : counts.DONE === total ? 'DONE' : 'PENDING'
    const mc = C[aggStatus] || C.PENDING
    const isSel = selectedId === group.key

    const segs = []
    const segTypes = ['DONE','RUNNING','FAILED','SKIPPED','PENDING']
    segTypes.forEach(st => { if (counts[st] > 0) segs.push({ c: C[st], n: counts[st] }) })

    const tx = x + 8, ty = y + 16, barY = y + 33, countY = y + 45
    const barW = gW - 16
    const els = [
      React.createElement('rect', {
        key: 'bg', x, y, width: gW, height: gH, rx: 8,
        fill: mc, opacity: 0.92,
        stroke: isSel ? '#fff' : 'transparent',
        strokeWidth: isSel ? 3 : 0,
        cursor: 'pointer',
        onClick: () => onSelect(group.key)
      }),
      React.createElement('text', {
        key: 'tt', x: tx, y: ty, fill: '#fff', fontSize: 11, fontWeight: 600
      }, (props.label || '\u21BB ') + group.name + ' (' + total + ')'),
    ]

    // 进度条
    if (segs.length > 0) {
      els.push(
        React.createElement('rect', {
          key: 'pb', x: tx, y: barY, width: barW, height: 6, rx: 3,
          fill: 'rgba(0,0,0,0.2)'
        })
      )
      let segX = tx
      segs.forEach((s, i) => {
        const segW = Math.max(s.n / total * barW, 8)
        els.push(React.createElement('rect', {
          key: 'ps' + i, x: segX, y: barY, width: segW, height: 6, rx: 3, fill: s.c
        }))
        segX += segW
      })
    }

    // 计数标签
    const countStr = ['DONE','RUNNING','FAILED','SKIPPED'].map(st => {
      const c = counts[st]
      if (!c) return ''
      const sym = st === 'DONE' ? '\u2713' : st === 'RUNNING' ? '\u25CF' : st === 'FAILED' ? '\u2717' : '\u23ED'
      return c + sym
    }).filter(Boolean).join(' ')
    els.push(React.createElement('text', {
      key: 'ct', x: tx, y: countY, fill: 'rgba(255,255,255,0.9)', fontSize: 9
    }, countStr))

    // 展开/折叠图标
    els.push(
      React.createElement('text', {
        key: 'ex', x: x + gW - 8, y: ty, textAnchor: 'end', fill: '#fff', fontSize: 11, cursor: 'pointer',
        onClick: (e) => { e.stopPropagation(); onToggle() }
      }, isExpanded ? '\u25B2' : '\u25B6'),
    )

    return els
  }

  // ── DAG 画布组件 ───────────────────────────────────────────────
  const DagCanvas = React.memo(function DagCanvas(props) {
    const { stage, gateResult, tasks, selectedId, onSelect, workflowName, retries, error } = props
    const mc = stage === 'COMPLETED' ? (gateResult === 'FAIL' ? C.FAILED : C.DONE) : stage === 'FAILED' ? C.FAILED : stage === 'RUNNING' ? C.RUNNING : C.PENDING

    // 构建流程节点：start + 普通task / 垂直组(dependsOn相同无框) / loop折叠框 / concurrent折叠框 + end（Iter-8）
    const flat = Array.isArray(tasks) ? tasks : []
    const flowNodes = [], loopGroups = [], concGroups = []
    const depKeyOf = (t) => JSON.stringify((t.dependsOn || []).slice().sort())

    // start 节点（流程起点）
    flowNodes.push({ type: 'start' })

    for (let gi = 0; gi < flat.length;) {
      const t = flat[gi]
      if (t._loopGroup) {
        // loop 折叠框
        const g = { key: t._loopGroup, name: t._loopGroupName || t._loopGroup, items: [] }
        while (gi < flat.length && flat[gi]._loopGroup === g.key) { g.items.push(flat[gi]); gi++ }
        loopGroups.push(g)
        flowNodes.push({ type: 'loop', group: g })
      } else if (t._concurrentGroup) {
        // Iter-8：concurrent 折叠框（⚡ 并发）
        const g = { key: t._concurrentGroup, name: t._concurrentGroupName || t._concurrentGroup, items: [] }
        while (gi < flat.length && flat[gi]._concurrentGroup === g.key) { g.items.push(flat[gi]); gi++ }
        concGroups.push(g)
        flowNodes.push({ type: 'concgroup', group: g })
      } else {
        // 垂直组：连续多个 dependsOn 相同的 task（无线框，垂直排列，可并发）
        const depKey = depKeyOf(t)
        let j = gi + 1
        while (j < flat.length && !flat[j]._loopGroup && !flat[j]._concurrentGroup && depKeyOf(flat[j]) === depKey) j++
        if (j - gi > 1) {
          flowNodes.push({ type: 'vertgroup', tasks: flat.slice(gi, j), key: 'vg-' + t.id })
          gi = j
        } else {
          flowNodes.push({ type: 'task', task: t })
          gi++
        }
      }
    }

    // end 节点（流程终点）
    flowNodes.push({ type: 'end' })

    const gW = 132, gH = 46, gHLoop = 64, gap = 44, pad = 24
    const gapV = 8, padV = 10 // Iter-7：并发组内垂直间隔 + 组框内 padding
    let svgX = pad
    const svgChildren = []

    // 展开状态
    const [expanded, setExpanded] = React.useState({})
    const toggleGroup = React.useCallback(key => {
      setExpanded(prev => {
        const n = {}
        for (const k in prev) n[k] = prev[k]
        n[key] = !prev[key]
        return n
      })
    }, [])

    // 最高节点高度（统一垂直中心 + SVG 高度）
    const nodeHeightOf = (fn) => {
      if (fn.type === 'loop' || fn.type === 'concgroup') return gHLoop
      if (fn.type === 'vertgroup') return 2 * padV + fn.tasks.length * gH + (fn.tasks.length - 1) * gapV
      return gH
    }
    const maxH = flowNodes.reduce((mx, fn) => Math.max(mx, nodeHeightOf(fn)), 0)
    const centerY = maxH / 2 + pad

    // 节点位置
    const nodePositions = []

    flowNodes.forEach((fn, fi) => {
      const h = nodeHeightOf(fn)
      const cy = fn.type === 'start' || fn.type === 'end' ? centerY - gH / 2 : centerY - h / 2

      if (fn.type === 'task') {
        const t = fn.task
        const isSel = selectedId === t.id
        svgChildren.push(
          React.createElement('rect', {
            key: 'r' + t.id, x: svgX, y: cy, width: gW, height: h, rx: 8,
            fill: C[t.status] || C.PENDING, opacity: 0.92,
            stroke: isSel ? '#fff' : 'transparent', strokeWidth: isSel ? 3 : 0,
            cursor: 'pointer', onClick: () => onSelect(t.id)
          }),
          React.createElement('text', {
            key: 't' + t.id, x: svgX + gW / 2, y: cy + h / 2 + 5,
            textAnchor: 'middle', fill: '#fff', fontSize: 12, fontWeight: 600
          }, t.name || t.id),
          React.createElement('text', {
            key: 'u' + t.id, x: svgX + gW / 2, y: cy + h / 2 + 18,
            textAnchor: 'middle', fill: 'rgba(255,255,255,0.85)', fontSize: 10
          }, t.id),
        )
      } else if (fn.type === 'start') {
        // start 节点（绿色实心小圆点，流程起点）
        const cx = svgX + gW / 2
        svgChildren.push(
          React.createElement('circle', { key: 'st', cx, cy: centerY, r: 12, fill: '#22c55e' }),
        )
      } else if (fn.type === 'end') {
        // end 节点（红色空心小圆圈，流程终点）
        const cx = svgX + gW / 2
        svgChildren.push(
          React.createElement('circle', { key: 'en', cx, cy: centerY, r: 12, fill: 'none', stroke: '#ef4444', strokeWidth: 3 }),
        )
      } else if (fn.type === 'loop') {
        // Loop 组节点
        const g = fn.group
        const lgEls = LoopGroupNode({
          x: svgX, y: cy, gW, gH: gHLoop, group: g,
          selectedId, onSelect, isExpanded: !!expanded[g.key], onToggle: () => toggleGroup(g.key)
        })
        svgChildren.push(...lgEls)
      } else if (fn.type === 'concgroup') {
        // Iter-8：concurrent 节点——复用 LoopGroupNode（实线 + 进度 + 状态 + 可展开），标注 ⚡ 并发
        const g = fn.group
        const cgEls = LoopGroupNode({
          x: svgX, y: cy, gW, gH: gHLoop, group: g,
          selectedId, onSelect, isExpanded: !!expanded['cc-' + g.key], onToggle: () => toggleGroup('cc-' + g.key),
          label: '\u26A1 并发 '
        })
        svgChildren.push(...cgEls)
      } else {
        // Iter-8：依赖同一前驱的节点——垂直并列，无线框（各自独立，可并发）
        fn.tasks.forEach((t, i) => {
          const ty = cy + padV + i * (gH + gapV)
          const isSel = selectedId === t.id
          svgChildren.push(
            React.createElement('rect', {
              key: 'r' + t.id, x: svgX + 4, y: ty, width: gW - 8, height: gH, rx: 6,
              fill: C[t.status] || C.PENDING, opacity: 0.92,
              stroke: isSel ? '#fff' : 'transparent', strokeWidth: isSel ? 3 : 0,
              cursor: 'pointer', onClick: () => onSelect(t.id)
            }),
            React.createElement('text', {
              key: 't' + t.id, x: svgX + gW / 2, y: ty + gH / 2 + 5,
              textAnchor: 'middle', fill: '#fff', fontSize: 12, fontWeight: 600
            }, t.name || t.id),
            React.createElement('text', {
              key: 'u' + t.id, x: svgX + gW / 2, y: ty + gH / 2 + 18,
              textAnchor: 'middle', fill: 'rgba(255,255,255,0.85)', fontSize: 10
            }, t.id),
          )
        })
      }

      nodePositions.push({
        x: svgX, w: gW, h,
        type: fn.type,
        key: fn.type === 'start' || fn.type === 'end' ? fn.type
          : fn.type === 'loop' || fn.type === 'concgroup' ? fn.group.key
          : fn.type === 'vertgroup' ? fn.key
          : fn.task.id
      })
      svgX += gW + gap

      // 箭头（统一 centerY，对准所有节点中心）
      if (fi < flowNodes.length - 1) {
        svgChildren.push(
          React.createElement('line', {
            key: 'a' + fi,
            x1: svgX - gap + 3, y1: centerY,
            x2: svgX - 3, y2: centerY,
            stroke: '#94a3b8', strokeWidth: 2, markerEnd: 'url(#da)'
          }),
        )
      }
    })

    // 箭头标记
    if (flowNodes.length > 0) {
      svgChildren.push(
        React.createElement('defs', { key: 'd' },
          React.createElement('marker', {
            id: 'da', viewBox: '0 0 10 10', refX: 9, refY: 5,
            markerWidth: 7, markerHeight: 7, orient: 'auto-start-reverse'
          },
          React.createElement('path', { d: 'M 0 0 L 10 5 L 0 10 z', fill: '#94a3b8' }))))
    }

    const svgW = flowNodes.length ? pad * 2 + flowNodes.reduce((s, fn, i) => s + (i > 0 ? gap : 0) + gW, 0) : 0
    const svgH = maxH + 2 * pad

    // 展开的列表（SVG 下方）
    const listElems = []
    loopGroups.forEach(g => {
      if (!expanded[g.key]) return
      const pos = nodePositions.find(p => p.type === 'loop' && p.key === g.key)
      if (!pos) return
      const listX = pos.x
      const listW = gW
      listElems.push(
        React.createElement('div', {
          key: 'll' + g.key,
          style: {
            marginLeft: listX + 'px',
            width: listW + 'px',
            background: 'rgba(148,163,184,0.05)',
            border: '1px solid rgba(148,163,184,0.2)',
            borderTop: 'none',
            borderBottomLeftRadius: 8, borderBottomRightRadius: 8,
            padding: '4px 0',
            fontSize: 12,
          },
        }, g.items.map((t, i) => {
          const sel = selectedId === t.id
          return React.createElement('div', {
            key: t.id, onClick: () => onSelect(t.id),
            style: {
              display: 'flex', alignItems: 'center', gap: 6, padding: '3px 10px',
              cursor: 'pointer', background: sel ? 'rgba(59,130,246,0.1)' : 'transparent',
            },
          }, [
            React.createElement('span', {
              style: { width: 8, height: 8, borderRadius: 4, background: C[t.status] || C.PENDING, flexShrink: 0 }
            }),
            React.createElement('span', { style: { flex: 1, color: '#475569' } }, (i + 1) + '. ' + (t.name || t.id)),
            React.createElement('span', { style: { color: '#64748b', fontSize: 11 } }, t.status),
          ])
        }))
      )
    })

    // Iter-8：concurrent 组展开列表（SVG 下方，同 loop）
    concGroups.forEach(g => {
      if (!expanded['cc-' + g.key]) return
      const pos = nodePositions.find(p => p.type === 'concgroup' && p.key === g.key)
      if (!pos) return
      const listX = pos.x
      const listW = gW
      listElems.push(
        React.createElement('div', {
          key: 'cl' + g.key,
          style: {
            marginLeft: listX + 'px',
            width: listW + 'px',
            background: 'rgba(59,130,246,0.05)',
            border: '1px solid rgba(59,130,246,0.2)',
            borderTop: 'none',
            borderBottomLeftRadius: 8, borderBottomRightRadius: 8,
            padding: '4px 0',
            fontSize: 12,
          },
        }, g.items.map((t, i) => {
          const sel = selectedId === t.id
          return React.createElement('div', {
            key: t.id, onClick: () => onSelect(t.id),
            style: {
              display: 'flex', alignItems: 'center', gap: 6, padding: '3px 10px',
              cursor: 'pointer', background: sel ? 'rgba(59,130,246,0.1)' : 'transparent',
            },
          }, [
            React.createElement('span', {
              style: { width: 8, height: 8, borderRadius: 4, background: C[t.status] || C.PENDING, flexShrink: 0 }
            }),
            React.createElement('span', { style: { flex: 1, color: '#475569' } }, (i + 1) + '. ' + (t.name || t.id)),
            React.createElement('span', { style: { color: '#64748b', fontSize: 11 } }, t.status),
          ])
        }))
      )
    })

    return React.createElement('div', { style: { padding: '14px 18px 10px' } }, [
      // 状态栏
      React.createElement('div', {
        key: 'sb',
        style: { display: 'flex', alignItems: 'center', gap: 14, marginBottom: 8, fontSize: 12, color: '#64748b', flexWrap: 'wrap' },
      }, [
        React.createElement('span', { key: 'w', style: { fontWeight: 600, color: '#334155' } }, workflowName || '-'),
        React.createElement('span', { key: 's' }, 'S: ', React.createElement('span', { style: { color: mc, fontWeight: 700 } },
          (stage || '-') + ' ' + (stage === 'PENDING' ? 'Pd' : stage === 'RUNNING' ? 'Rn' : stage === 'COMPLETED' ? 'Cp' : 'Fl'))),
        React.createElement('span', { key: 'g' }, 'G: ', gateResult
          ? React.createElement('span', { style: { color: gateResult === 'PASS' ? C.DONE : C.FAILED, fontWeight: 700 } }, gateResult)
          : '-'),
        retries > 0 ? React.createElement('span', { key: 'r' }, 'R: ' + retries) : null,
        error ? React.createElement('span', { key: 'e', style: { color: C.FAILED } }, error) : null,
      ]),
      // SVG 流程图
      flowNodes.length > 0 ? React.createElement('svg', {
        key: 'svg', width: svgW, height: svgH,
        xmlns: 'http://www.w3.org/2000/svg',
        style: { background: 'rgba(148,163,184,0.08)', borderRadius: 8, width: '100%', maxWidth: svgW, marginBottom: 0 },
      }, svgChildren) : null,
      // 展开的列表
      React.createElement('div', { key: 'lx', style: { position: 'relative', marginTop: -4 } }, listElems),
    ])
  })

  // ── Slot 注册 ──────────────────────────────────────────────────
  slots.inject('conversation.view', () => {
    return slots.register(
      { name: 'conversation.view', id: 'workflow', order: 25, label: () => 'Workflow' },
      function WorkflowViewFactory(props) {
        const workspaceHook = props.useWorkspaces
        const sessionId = props.sessionId
        const useSessions = props.useSessions
        // Iter-12：跟随当前 session 的 cwd（切 session → 实例目录跟随）
        const sessionCwd = useSessions
          ? useSessions((s) => (sessionId === undefined || sessionId === null) ? undefined : (s.byId && s.byId[sessionId] ? s.byId[sessionId].cwd : undefined))
          : undefined

        function WorkflowView() {
          const [, forceUpdate] = React.useReducer(x => x + 1, 0)
          const [selectedId, setSelectedId] = React.useState(null)

          React.useEffect(() => {
            listeners.add(forceUpdate)
            return () => listeners.delete(forceUpdate)
          }, [])

          // ── Iter-12：workspaceRoot 解析——session cwd 优先，回退当前工作区首项 ──
          React.useEffect(() => {
            let next = null
            if (typeof sessionCwd === 'string' && sessionCwd) {
              next = String(sessionCwd).replace(/\\/g, '/')
              // 如果是相对路径，转换为绝对路径
              if (!next.startsWith('/')) {
                next = '/home/zhaokai/Projects/dsh_projects/' + next
              }
            }
            if (!next && workspaceHook) {
              try {
                const wsList = workspaceHook()
                if (wsList && wsList.data && Array.isArray(wsList.data.items) && wsList.data.items.length > 0) {
                  next = String(wsList.data.items[0].path).replace(/\\/g, '/')
                }
              } catch (e) {}
            }
            if (!next || next === activeRoot) return
            activeRoot = next
            wfRoot = next
            wfLoaded = true
            latest = null; lastError = null
            wfInstances = []; wfInstanceId = ''
            if (typeof window.__wfSetRoot === 'function') window.__wfSetRoot(next)
            listeners.forEach(fn => { try { fn() } catch (e2) {} })
            // 启动实例列表轮询
            startListPolling()
          }, [sessionCwd, workspaceHook])

          // ── Iter-12：实例列表轮询（只读；选择经 wfInstanceId 参与 status 轮询）──
          // 注意：轮询在 workspaceRoot 解析 effect 里启动，不依赖 React state
          // 这里只负责清理
          React.useEffect(() => {
            return () => {
              if (wfListLoader) {
                wfListLoader.stop = true
                wfListLoader = null
              }
            }
          }, [])

          const snap = latest
          const stateData = (snap && snap.state) ? snap.state : null
          const tasks = stateData && Array.isArray(stateData.tasks) ? stateData.tasks : []
          const hasData = stateData && stateData.workflow

          // ── Iter-13：面板创建（"+" + 表单；hooks 全部置于条件返回之前）────
          const [formOpen, setFormOpen] = React.useState(false)
          const [tplOpts, setTplOpts] = React.useState([])
          const [tplSel, setTplSel] = React.useState('custom')
          const [yamlText, setYamlText] = React.useState('')
          const [pathText, setPathText] = React.useState('')
          const [paramsText, setParamsText] = React.useState('{}')
          const [busy, setBusy] = React.useState(false)
          const [formErr, setFormErr] = React.useState('')

          React.useEffect(() => {
            if (!formOpen || !activeRoot) return
            let stop = false
            fetch('/wf/templates?workspaceRoot=' + encodeURIComponent(activeRoot))
              .then(r => r.json())
              .then(r => {
                if (stop) return
                const opts = [{ v: 'custom', label: '自定义路径…' }]
                ;(r.builtin || []).forEach(t => opts.push({ v: 'builtin:' + t.name, label: '[内置] ' + (t.description || t.name), t }))
                ;(r.workspace || []).forEach(w => opts.push({ v: 'ws:' + w.path, label: '[工作区] ' + w.name }))
                setTplOpts(opts)
                if (opts.length > 1) { setTplSel(opts[1].v); setYamlText(opts[1].t ? opts[1].t.yaml : '') }
              })
              .catch(() => {})
            return () => { stop = true }
          }, [formOpen, activeRoot])

          const openForm = () => { setFormErr(''); setFormOpen(true) }
          const pickTpl = (v) => {
            setTplSel(v)
            const opt = tplOpts.find(o => o.v === v)
            setYamlText(opt && opt.t ? opt.t.yaml : '')
          }
          const submitCreate = async () => {
            setFormErr(''); setBusy(true)
            try {
              let params = {}
              try { params = paramsText.trim() ? JSON.parse(paramsText) : {} } catch (e) { throw new Error('params 不是合法 JSON') }
              const payload = { workspaceRoot: activeRoot, params }
              if (tplSel === 'custom') {
                if (!pathText.trim()) throw new Error('请填写 workflowPath')
                payload.workflowPath = pathText.trim()
              } else if (tplSel.startsWith('ws:')) {
                payload.workflowPath = tplSel.slice(3)
              } else if (tplSel.startsWith('builtin:')) {
                if (!yamlText.trim()) throw new Error('模板内容为空')
                payload.workflowText = yamlText
              }
              const resp = await fetch('/wf/create', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) })
              const r = await resp.json()
              if (!resp.ok) throw new Error((r && r.error) || ('HTTP ' + resp.status))
              setFormOpen(false)
              if (typeof wfListLoader === 'function') wfListLoader()
            } catch (e) {
              setFormErr(e && e.message ? e.message : String(e))
            } finally {
              setBusy(false)
            }
          }

          const fieldStyle = { border: '1px solid rgba(148,163,184,0.4)', borderRadius: 6, padding: '4px 8px', background: 'rgba(148,163,184,0.08)', color: 'inherit', fontSize: 12, width: '100%', boxSizing: 'border-box' }
          const monoStyle = Object.assign({}, fieldStyle, { fontFamily: 'monospace', resize: 'vertical' })
          const btnStyle = { border: '1px solid rgba(148,163,184,0.4)', background: 'transparent', color: 'inherit', borderRadius: 6, padding: '3px 12px', cursor: 'pointer', fontSize: 12 }

          // Iter-15：面板控制按钮（Start/Stop/Reset）
          const controlBtns = []
          const currentStage = stateData && stateData.stage
          const currentInstanceId = (snap && snap.instanceId) || wfInstanceId || (wfInstances[0] && wfInstances[0].instanceId) || ''
          
          // Start 按钮（CREATED 或无状态时显示）
          if (!currentStage || currentStage === 'CREATED') {
            controlBtns.push(React.createElement('button', {
              key: 'start', title: '启动实例',
              onClick: async () => {
                if (!currentInstanceId || !activeRoot) return
                try {
                  const resp = await fetch('/wf/start', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                      workspaceRoot: activeRoot, 
                      instanceId: currentInstanceId,
                      sessionId: sessionId // 传递当前 session ID
                    })
                  })
                  if (!resp.ok) {
                    const err = await resp.json()
                    alert('启动失败: ' + (err.error || '未知错误'))
                  }
                } catch (e) {
                  alert('启动失败: ' + e.message)
                }
              },
              style: { border: '1px solid rgba(34,197,94,0.5)', background: 'rgba(34,197,94,0.1)', color: '#22c55e', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'pointer' }
            }, '▶ Start'))
          }
          
          // Stop 按钮（PENDING 或 RUNNING 时显示）
          if (currentStage === 'PENDING' || currentStage === 'RUNNING') {
            controlBtns.push(React.createElement('button', {
              key: 'stop', title: '停止实例',
              onClick: async () => {
                if (!currentInstanceId || !activeRoot) return
                try {
                  const resp = await fetch('/wf/stop', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ workspaceRoot: activeRoot, instanceId: currentInstanceId })
                  })
                  if (!resp.ok) {
                    const err = await resp.json()
                    alert('停止失败: ' + (err.error || '未知错误'))
                  }
                } catch (e) {
                  alert('停止失败: ' + e.message)
                }
              },
              style: { border: '1px solid rgba(239,68,68,0.5)', background: 'rgba(239,68,68,0.1)', color: '#ef4444', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'pointer' }
            }, '⏹ Stop'))
          }
          
          // Reset 按钮（STOPPED、COMPLETED、FAILED 时显示）
          if (currentStage === 'STOPPED' || currentStage === 'COMPLETED' || currentStage === 'FAILED') {
            controlBtns.push(React.createElement('button', {
              key: 'reset', title: '重置实例（清空状态，保留产物）',
              onClick: async () => {
                if (!currentInstanceId || !activeRoot) return
                if (!confirm('确定要重置实例吗？状态将被清空，产物文件保留。')) return
                try {
                  const resp = await fetch('/wf/reset', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ workspaceRoot: activeRoot, instanceId: currentInstanceId })
                  })
                  if (!resp.ok) {
                    const err = await resp.json()
                    alert('重置失败: ' + (err.error || '未知错误'))
                  }
                } catch (e) {
                  alert('重置失败: ' + e.message)
                }
              },
              style: { border: '1px solid rgba(245,158,11,0.5)', background: 'rgba(245,158,11,0.1)', color: '#f59e0b', borderRadius: 6, padding: '1px 9px', fontSize: 12, cursor: 'pointer' }
            }, '↻ Reset'))
          }

          const plusBtn = React.createElement('button', {
            key: 'plus', title: '新建 workflow 实例（只创建，不启动）', onClick: openForm,
            style: { border: '1px solid rgba(148,163,184,0.35)', background: 'transparent', color: 'inherit', borderRadius: 6, padding: '1px 9px', fontSize: 14, cursor: 'pointer', lineHeight: '18px' }
          }, '+')
          const toolbar = React.createElement('div', {
            key: 'tb', style: { display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: 6, padding: '6px 12px 0' }
          }, [...controlBtns, plusBtn])

          const formOverlay = !formOpen ? null : React.createElement('div', {
            style: { position: 'fixed', top: 0, right: 0, bottom: 0, left: 0, background: 'rgba(0,0,0,0.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50 },
            onClick: () => setFormOpen(false)
          }, React.createElement('div', {
            style: { background: 'var(--dsw-alias-bg-base, #1e293b)', color: 'var(--dsw-alias-label-primary, #e2e8f0)', borderRadius: 10, padding: 16, width: 460, maxWidth: '92vw', display: 'flex', flexDirection: 'column', gap: 8, fontSize: 12 },
            onClick: (e) => e.stopPropagation()
          }, [
            React.createElement('div', { key: 't', style: { fontSize: 13, fontWeight: 600 } }, '新建 workflow 实例（只创建，不启动）'),
            React.createElement('label', { key: 'l1' }, '模板 / 来源'),
            React.createElement('select', { key: 's1', value: tplSel, onChange: e => pickTpl(e.target.value), style: fieldStyle },
              tplOpts.map(o => React.createElement('option', { key: o.v, value: o.v }, o.label))
            ),
            tplSel === 'custom' ? React.createElement('input', { key: 'p', value: pathText, onChange: e => setPathText(e.target.value), placeholder: 'workflow YAML 绝对路径', style: fieldStyle }) : null,
            tplSel.indexOf('builtin:') === 0 ? React.createElement('textarea', { key: 'y', value: yamlText, onChange: e => setYamlText(e.target.value), rows: 10, style: monoStyle, spellCheck: false }) : null,
            React.createElement('label', { key: 'l2' }, 'params（JSON，可选）'),
            React.createElement('textarea', { key: 'pj', value: paramsText, onChange: e => setParamsText(e.target.value), rows: 3, style: monoStyle, spellCheck: false }),
            formErr ? React.createElement('div', { key: 'err', style: { color: '#f87171', whiteSpace: 'pre-wrap' } }, formErr) : null,
            React.createElement('div', { key: 'btns', style: { display: 'flex', justifyContent: 'flex-end', gap: 8 } }, [
              React.createElement('button', { key: 'c', onClick: () => setFormOpen(false), style: btnStyle }, '取消'),
              React.createElement('button', { key: 'o', onClick: submitCreate, disabled: busy, style: Object.assign({}, btnStyle, { background: '#3b82f6', color: '#fff', border: 'none' }) }, busy ? '创建中…' : '创建'),
            ]),
          ]))

          if (!wfLoaded) {
            return React.createElement('div', {
              style: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', minHeight: 420, color: '#9ca3af', fontSize: 13 }
            }, '...')
          }

          if (!wfRoot) {
            return React.createElement('div', {
              style: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', minHeight: 420, color: '#9ca3af', fontSize: 13, flexDirection: 'column', gap: 8 }
            }, [
              React.createElement('span', { key: 'a' }, 'No workspace'),
              React.createElement('span', { key: 'b', style: { fontSize: 11 } }, 'Open a workspace first')
            ])
          }

          if (!hasData) {
            return React.createElement('div', {
              style: { display: 'flex', flexDirection: 'column', height: '100%', minHeight: 420, fontFamily: 'inherit', fontSize: 13 }
            },
              toolbar,
              formOverlay,
              React.createElement('div', {
                style: { display: 'flex', alignItems: 'center', justifyContent: 'center', flex: 1, color: '#9ca3af', fontSize: 13, border: '1px dashed rgba(148,163,184,0.35)', borderRadius: 8, margin: 12, background: 'rgba(148,163,184,0.05)' }
              }, stateData && stateData.error ? 'Workflow Error: ' + stateData.error : 'Waiting for workflow...')
            )
          }

          // ── Iter-12：实例切换条（>1 个实例才显示；空选=最新实例）────────
          const selectInstance = (id) => {
            wfInstanceId = id
            latest = null
            listeners.forEach(fn => { try { fn() } catch (e2) {} })
          }
          const defaultSel = wfInstanceId || (wfInstances[0] ? wfInstances[0].instanceId : '')
          const instBar = wfInstances.length > 1 ? React.createElement('div', {
            key: 'ib', style: { display: 'flex', flexWrap: 'wrap', gap: 6, padding: '8px 12px 0', alignItems: 'center' }
          }, wfInstances.map(it => {
            const isSel = defaultSel === it.instanceId
            return React.createElement('button', {
              key: it.instanceId,
              onClick: () => selectInstance(it.instanceId),
              style: {
                border: '1px solid ' + (isSel ? 'rgba(59,130,246,0.8)' : 'rgba(148,163,184,0.35)'),
                background: isSel ? 'rgba(59,130,246,0.12)' : 'transparent',
                color: 'inherit', borderRadius: 6, padding: '2px 8px', fontSize: 11, cursor: 'pointer'
              }
            }, it.workflowName + ' · ' + String(it.instanceId).slice(-6) + (it.stage ? ' · ' + it.stage : ''))
          })) : null

          return React.createElement('div', {
            style: { display: 'flex', flexDirection: 'column', height: '100%', minHeight: 420, fontFamily: 'inherit', fontSize: 13 }
          },
            toolbar,
            instBar,
            React.createElement(DagCanvas, {
              stage: stateData.stage,
              gateResult: stateData.gateResult || null,
              tasks,
              selectedId,
              onSelect: id => setSelectedId(prev => prev === id ? null : id),
              workflowName: stateData.workflow,
              retries: stateData.retries || 0,
              error: stateData.error || null,
            }),
            formOverlay
          )
        }

        return React.createElement(WorkflowView)
      },
    )
  })
}

    
    // Plugin code ends here
    
    function apply(ctx) {
      register(ctx);
    }
    
    const inject = ['slots'];
    
    exports.apply = apply;
    exports.inject = inject;
    
    return module.exports;
  }
});
